webos: webos.inc: drop 2nd param from get_metadata_git_* calls
:Release Notes:
Follow oe-core change:
https://git.openembedded.org/openembedded-core/commit/?id=9e03ce0426576ebef3739dc1dfec4f7cd73ae094

:Detailed Notes:
Fixes:

Parsing recipes...WARNING: /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime-clang_108.bb: Exception during build_dependencies for do_exportbuildscript
WARNING: /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime-clang_108.bb: Error during finalise of /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime-clang_108.bb
WARNING: /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_108.bb: Exception during build_dependencies for do_exportbuildscript
WARNING: /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_108.bb: Error during finalise of /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_108.bb
ERROR: ExpansionError during parsing /data001/jenkins/gecko/webos_qemux86-64/build/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_108.bb
Traceback (most recent call last):
  File "Var <WEBOS_DISTRO_TOPDIR_REVISION>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable WEBOS_DISTRO_TOPDIR_REVISION, expression was ${@oe.buildcfg.get_metadata_git_revision('/data001/jenkins/gecko/webos_qemux86-64/build', None).strip()} which triggered exception TypeError: get_metadata_git_revision() takes 1 positional argument but 2 were given
The variable dependency chain for the failure is: WEBOS_DISTRO_TOPDIR_REVISION -> do_exportbuildscript

ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I709b4088ab18f86448efb440f701acb599259990