webos: com.webos.service.camera=r*.2 (plugin: rename basename function to avoid conflict with the one from string.h)
:Release Notes:
I don't know why it defines this instead of using the standard one, but
at least use different name to avoid conflict.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1140890

FAILED: src/plugins/hal/v4l2/CMakeFiles/hal-v4l2.dir/v4l2_camera_plugin.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot -DDAC_ENABLED -DWEBOS_INSTALL_LIBDIR=\"/usr/lib\" -Dhal_v4l2_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/plugin -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/hal -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/notifier -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/solution -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/private -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/src/libs/include/private -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/src/plugins/hal/v4l2 -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git=/usr/src/debug/com.webos.service.camera/1.0.0-nanomedia.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git=/usr/src/debug/com.webos.service.camera/1.0.0-nanomedia.1  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/build=/usr/src/debug/com.webos.service.camera/1.0.0-nanomedia.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/build=/usr/src/debug/com.webos.service.camera/1.0.0-nanomedia.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -Wall -funwind-tables -Wall -rdynamic -lrt -Werror -Wno-psabi -lrt -lacl -Werror -Wno-psabi -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/include -g -std=gnu++17 -fPIC -MD -MT src/plugins/hal/v4l2/CMakeFiles/hal-v4l2.dir/v4l2_camera_plugin.cpp.o -MF src/plugins/hal/v4l2/CMakeFiles/hal-v4l2.dir/v4l2_camera_plugin.cpp.o.d -o src/plugins/hal/v4l2/CMakeFiles/hal-v4l2.dir/v4l2_camera_plugin.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/src/plugins/hal/v4l2/v4l2_camera_plugin.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/plugin/plugin.hpp:4,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/src/plugins/hal/v4l2/v4l2_camera_plugin.h:21,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/src/plugins/hal/v4l2/v4l2_camera_plugin.cpp:19:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/plugin/plugin_interface.hpp:8:20: error: declaration of 'const char* basename(const char*)' has a different exception specifier [-Werror]
    8 | inline const char *basename(const char *path)
      |                    ^~~~~~~~
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/include/c++/15.0.1/cstring:48,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/git/include/public/camera/plugin/plugin_interface.hpp:3:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.camera/1.0.0-nanomedia.1/recipe-sysroot/usr/include/string.h:537:26: note: from previous declaration 'const char* basename(const char*) noexcept'
  537 | extern "C++" const char *basename (const char *__filename)
      |                          ^~~~~~~~
cc1plus: all warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I98b9b0ad458a3f845de3408b82bf10f8b783be98