packagegroup-webos-extended: fix parsing for raspberrypi3(-64) MACHINEs
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: Nothing RPROVIDES '${CECSERVICE}' (but /data001/jenkins/gecko/webos_raspberrypi3-64/build/meta-lg-webos/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${CECSERVICE}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${CECSERVICE}']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', '${CECSERVICE}']
ERROR: Required build target 'webos-image-devel' has no buildable providers.
Missing or unbuildable dependency chain was: ['webos-image-devel', 'packagegroup-webos-extended', '${CECSERVICE}']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-16369] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I633ef51022893707986ad5d3e134316d14fa6f8c