webos-sota: inherit image-artifact-names for IMAGE_BASENAME
* otherwise all builds with meta-updater layer and sota enabled
  fail with:

ERROR: Sota's config sanity checker detected a potential misconfiguration.
Please fix the cause of this error then you can continue to build.
Following is the list of potential problems / advisories:

OSTREE_BRANCHNAME Should only contain characters from the character set [a-zA-Z0-9._-].

because OSTREE_BRANCHNAME will contain unexpanded '${IMAGE_BASENAME}' like this:
OSTREE_BRANCHNAME = "${IMAGE_BASENAME}-master"

Signed-off-by: Martin Jansa <martin.jansa@lge.com>