webos: node-gyp-native=v10.0.1 (upgrade for python 3.12 compatibility)
:Release Notes:
recipes using node-gyp-native fail to build after python3 was updated to 3.12 in:
https://git.openembedded.org/openembedded-core/commit/?id=716d82352545d3667a658b69d65d6127678dd150

:Detailed Notes:
we need the fix from:
https://github.com/nodejs/node-gyp/issues/2869

Fixes:
nodejs-module-webos-sysbus   http://gecko.lge.com:8000/Errors/Details/763462
nodejs-module-webos-pmlog    http://gecko.lge.com:8000/Errors/Details/763463
nodejs-module-webos-dynaload http://gecko.lge.com:8000/Errors/Details/763464

Traceback (most recent call last):
  File "nodejs-module-webos-dynaload/3.0.2-4/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "nodejs-module-webos-dynaload/3.0.2-4/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "nodejs-module-webos-dynaload/3.0.2-4/recipe-sysroot-native/usr/lib/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I5bbcf7246499edfaa6141890c70d0a7a257be36f