nodejs-module-usocket=v0.2.1
:Release Notes:
Upgrade to latest and unblacklist as the nodejs-module-nan-native was fixed

:Detailed Notes:
Fixes:
recipe-sysroot-native/usr/lib/node_modules/nan/nan_implementation_12_inl.h:103:42: error: cannot convert 'v8::Isolate*' to 'v8::Local<v8::Context>'
  103 |   return scope.Escape(v8::Function::New( isolate
recipe-sysroot-native/usr/lib/node_modules/nan/nan_implementation_12_inl.h:337:37: error: no matching function for call to 'v8::StringObject::New(v8::Local<v8::String>&)'
  337 |   return v8::StringObject::New(value).As<v8::StringObject>();

Fixes:
http://gecko.lge.com/Errors/Details/38163

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-117236] Upgrade to latest revisions from Yocto project and Open source
[PLAT-118616] CCC: Various build fixes

Change-Id: Ie74404009dd0e5833dabe9726afc1099830e772d