meta-webos-iot: don't add non-existent directory to LICENSE_PATH
:Release Notes:
Fixes:
http://gecko.lge.com/jenkins/job/webosiot-master-official-raspberrypi4/43/console

:Detailed Notes:
Fixes:
INFO: ======================================================================
INFO: ERROR: test_world (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 44, in test_world
    get_signatures(self.td['builddir'], failsafe=False)
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 281, in get_signatures
    check_command('Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.',
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Generating signatures failed. This might be due to some parse error and/or general layer incompatibilities.
Command: BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE BB_SIGNATURE_HANDLER" BB_SIGNATURE_HANDLER="OEBasicHash" bitbake -S none world
Output:
ERROR: Unable to parse Var <AVAILABLE_LICENSES[:=]>
Traceback (most recent call last):
  File "Var <AVAILABLE_LICENSES[:=]>", line 1, in <module>
  File "/OE/openembedded-core/meta/classes/license.bbclass", line 275, in available_licenses(d=<bb.data_smart.DataSmart object at 0x7fbd063e53d0>):
         for lic_dir in lic_dirs:
    >        licenses += os.listdir(lic_dir)

bb.data_smart.ExpansionError: Failure expanding variable AVAILABLE_LICENSES[:=], expression was ${@' '.join(available_licenses(d))} which triggered exception FileNotFoundError: [Errno 2] No such file or directory: '/OE/meta-webosose/meta-webos-iot/licenses'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: Idbb479612a8d9d9991694995f37d6b3c88bf1997