libtool: Update 0001-libtool-fix-clang-linking-with-fsanitize-address-or.patch
:Release Notes:
gatesgarth and hardknott are using libtool-2.4.6 like dunfell, but don't have
the patch which adds -f*-prefix-map* parameter in the same chunk:
  3dcc84e37c libtool: Fix lto option passing for reproducible builds
causing this patch to fail to apply. In honister this change needs to be
reverted and in kirkstone this patch gets removed completely as it's
already included in upstream version.

:Detailed Notes:
ERROR: libtool-native-2.4.6-r0 do_patch: Applying patch '0001-libtool-fix-clang-linking-with-fsanitize-address-or.patch' on target directory '/data001/jenkins/gecko/webos-pro_qemux86-64/build/BUILD/work/x86_64-linux/libtool-native/2.4.6-r0/libtool-2.4.6'
Command Error: 'quilt --quiltrc /data001/jenkins/gecko/webos-pro_qemux86-64/build/BUILD/work/x86_64-linux/libtool-native/2.4.6-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0001-libtool-fix-clang-linking-with-fsanitize-address-or.patch
patching file build-aux/ltmain.in
Hunk #1 FAILED at 5425.
1 out of 1 hunk FAILED -- rejects in file build-aux/ltmain.in
Patch 0001-libtool-fix-clang-linking-with-fsanitize-address-or.patch does not apply (enforce with -f)

stderr:
ERROR: Logfile of failure stored in: /data001/jenkins/gecko/webos-pro_qemux86-64/build/BUILD/work/x86_64-linux/libtool-native/2.4.6-r0/temp/log.do_patch.2957

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth

Change-Id: I937b738b706787c94ee751ffc950438ed6d35da7