webos: activitymanager=r17 (CMakeLists.txt: replace -std=c++11 with -std=c++17 for icu-75-1)
:Release Notes:
icu-75 now requires C++17 (up from C++11) and C11 (up from C99).
https://icu.unicode.org/download/75

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/854744

FAILED: src/activitymanager/CMakeFiles/activitymanager.dir/db/DB8Manager.cpp.o
ccache TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot/usr/include/mojodb -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/git/src/activitymanager -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/git/src/common -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/build/Configured/src/common -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/git=/usr/src/debug/activitymanager/3.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/git=/usr/src/debug/activitymanager/3.0.0-43  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/build=/usr/src/debug/activitymanager/3.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/build=/usr/src/debug/activitymanager/3.0.0-43  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot-native=  -fvisibility-inlines-hidden -DUSE_PMLOG_DECLARATION -DINIT_MANAGER_systemd -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/recipe-sysroot/usr/include -Wall -Wno-error=strict-aliasing -Wconversion -DMOJ_LINUX -DBOOST_SP_DISABLE_THREADS -DUSE_PMLOG -std=c++11 -Wl,--no-undefined -DNDEBUG -MD -MT src/activitymanager/CMakeFiles/activitymanager.dir/db/DB8Manager.cpp.o -MF src/activitymanager/CMakeFiles/activitymanager.dir/db/DB8Manager.cpp.o.d -o src/activitymanager/CMakeFiles/activitymanager.dir/db/DB8Manager.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/activitymanager/3.0.0-43/git/src/activitymanager/db/DB8Manager.cpp
In file included from ../recipe-sysroot/usr/include/boost/bind.hpp:30,
                 from ../git/src/activitymanager/Main.h:32,
                 from ../git/src/activitymanager/db/ICompletion.h:22,
                 from ../git/src/activitymanager/db/DB8Command.h:21,
                 from ../git/src/activitymanager/db/DB8CommandDB.h:20,
                 from ../git/src/activitymanager/db/DB8Manager.cpp:19:
../recipe-sysroot/usr/include/boost/bind.hpp:36:1: note: '#pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.'
   36 | BOOST_PRAGMA_MESSAGE(
      | ^~~~~~~~~~~~~~~~~~~~
In file included from ../recipe-sysroot/usr/include/unicode/uenum.h:25,
                 from ../recipe-sysroot/usr/include/unicode/uloc.h:27,
                 from ../recipe-sysroot/usr/include/unicode/ubrk.h:14,
                 from ../recipe-sysroot/usr/include/mojodb/db/MojDbTextTokenizer.h:24,
                 from ../recipe-sysroot/usr/include/mojodb/db/MojDbExtractor.h:24,
                 from ../recipe-sysroot/usr/include/mojodb/db/MojDbQuery.h:27,
                 from ../git/src/activitymanager/db/DB8Manager.cpp:21:
../recipe-sysroot/usr/include/unicode/localpointer.h:561:26: error: parameter declared 'auto'
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-23876] CCC: activitymanager=r17 (CMakeLists.txt: replace -std=c++11 with -std=c++17 for icu-75-1)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: Ife62c6f0ce96599c94957d27870f5cce44caf2ed
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/409768
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>