webos: webos.inc: webrtc-audio-processing-2 libsimplelog: disable return-type Werror
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1175904

FAILED: CMakeFiles/simplelog.dir/src/simplelog.o
TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-gcc --sysroot=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot -DUNIX_LINUX=1 -Dsimplelog_EXPORTS -ITOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git/./include -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables  --sysroot=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git=/usr/src/debug/libsimplelog/1.0.4+git  -fdebug-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git=/usr/src/debug/libsimplelog/1.0.4+git  -fmacro-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/build=/usr/src/debug/libsimplelog/1.0.4+git  -fdebug-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/build=/usr/src/debug/libsimplelog/1.0.4+git  -fdebug-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/recipe-sysroot-native=  -pipe  -fPIC -MD -MT CMakeFiles/simplelog.dir/src/simplelog.o -MF CMakeFiles/simplelog.dir/src/simplelog.o.d -o CMakeFiles/simplelog.dir/src/simplelog.o -c TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git/src/simplelog.c
TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git/src/simplelog.c: In function 'spl_trigger_routine':
TOPDIR/BUILD/work/dq1-webos-linux/libsimplelog/1.0.4+git/git/src/simplelog.c:1764:1: error: no return statement in function returning non-void [-Werror=return-type]
 1764 | }
      | ^

http://gecko.lge.com:8000/Errors/Details/1203899

FAILED: webrtc/modules/audio_processing/libwebrtc-audio-processing-2.so.1.p/agc2_rnn_vad_rnn_fc.cc.o
aarch64-webos-linux-g++ -mbranch-protection=standard -fstack-protector-all -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables --sysroot=TOPDIR/BUILD/work/raspberrypi0_2w_64-webos-linux/webrtc-audio-processing-2/2.1/recipe-sysroot -Iwebrtc/modules/audio_processing/libwebrtc-audio-processing-2.so.1.p -Iwebrtc/modules/audio_processing -I../webrtc-audio-processing-2.1/webrtc/modules/audio_processing -Iwebrtc -I../webrtc-audio-processing-2.1/webrtc -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O2 -g -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi0_2w_64-webos-linux/webrtc-audio-processing-2/2.1/webrtc-audio-processing-2.1=/usr/src/debug/webrtc-audio-processing-2/2.1 -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi0_2w_64-webos-linux/webrtc-audio-processing-2/2.1/build=/usr/src/debug/webrtc-audio-processing-2/2.1 -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi0_2w_64-webos-linux/webrtc-audio-processing-2/2.1/recipe-sysroot= -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi0_2w_64-webos-linux/webrtc-audio-processing-2/2.1/recipe-sysroot-native= -pipe -fvisibility-inlines-hidden -fPIC -DNOMINMAX -pthread -DWEBRTC_LIBRARY_IMPL -DWEBRTC_ENABLE_SYMBOL_EXPORT -D_WINSOCKAPI_ -DNDEBUG -DWEBRTC_POSIX -DWEBRTC_LINUX -DWEBRTC_ARCH_ARM64 -DWEBRTC_APM_DEBUG_DUMP=0 -MD -MQ webrtc/modules/audio_processing/libwebrtc-audio-processing-2.so.1.p/agc2_rnn_vad_rnn_fc.cc.o -MF webrtc/modules/audio_processing/libwebrtc-audio-processing-2.so.1.p/agc2_rnn_vad_rnn_fc.cc.o.d -o webrtc/modules/audio_processing/libwebrtc-audio-processing-2.so.1.p/agc2_rnn_vad_rnn_fc.cc.o -c ../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.cc
In file included from ../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.h:19,
                 from ../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.cc:11:
../webrtc-audio-processing-2.1/webrtc/api/function_view.h: In instantiation of 'rtc::FunctionView<RetT(ArgT ...)>::FunctionView(F&&) [with F = float (&)(float); typename std::enable_if<std::is_function<typename std::remove_pointer<typename std::remove_reference<_Up>::type>::type>::value>::type* <anonymous> = 0; RetT = float; ArgT = {float}]':
../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.cc:59:25:   required from here
   59 |       return ::rnnoise::TansigApproximated;
      |              ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
../webrtc-audio-processing-2.1/webrtc/api/function_view.h:80:17: warning: the compiler can assume that the address of 'f' will never be NULL [-Waddress]
   80 |       : call_(f ? CallFunPtr<typename std::remove_pointer<F>::type> : nullptr) {
      |               ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../webrtc-audio-processing-2.1/webrtc/api/function_view.h:79:20: note: 'f' declared here
   79 |   FunctionView(F&& f)
      |                ~~~~^
../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.cc: In function 'rtc::FunctionView<float(float)> webrtc::rnn_vad::{anonymous}::GetActivationFunction(webrtc::rnn_vad::ActivationFunction)':
../webrtc-audio-processing-2.1/webrtc/modules/audio_processing/agc2/rnn_vad/rnn_fc.cc:63:1: error: control reaches end of non-void function [-Werror=return-type]
   63 | }
      | ^
../webrtc-audio-processing-2.1/webrtc/api/function_view.h: In constructor 'rtc::FunctionView<RetT(ArgT ...)>::FunctionView(F&&) [with F = float (&)(float); typename std::enable_if<std::is_function<typename std::remove_pointer<typename std::remove_reference<_Up>::type>::type>::value>::type* <anonymous> = 0; RetT = float; ArgT = {float}]':
../webrtc-audio-processing-2.1/webrtc/api/function_view.h:80:17: warning: 'nonnull' argument 'f' compared to NULL [-Wnonnull-compare]
   80 |       : call_(f ? CallFunPtr<typename std::remove_pointer<F>::type> : nullptr) {
      |               ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: If50646eaa0579378dc74ae007ee2b6b8a44c8473