com.webos.*.swupdater: don't include in image for armv[45]
:Release Notes:
com.webos.service.swupdater inherits webos_enactjs_app.bbclass which sets this
restriction because of dependency on restricted webruntime.

:Detailed Notes:
Also drop executable permissions from this file.

Fixes:
https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-engineering-qemuarm/68/display/redirect

ERROR: Nothing RPROVIDES 'com.webos.app.swupdater' (but <https://jenkins-scm.lgsvl.net/job/jansa/job/webos-jansa-thud-engineering-qemuarm/ws/build/meta-lg-webos/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb> RDEPENDS on or otherwise requires it)
com.webos.app.swupdater was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'com.webos.app.swupdater' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['com.webos.app.swupdater']
NOTE: Runtime target 'packagegroup-webos-extended' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-extended', 'com.webos.app.swupdater']
ERROR: Required build target 'webos-image-devel' has no buildable providers.
Missing or unbuildable dependency chain was: ['webos-image-devel', 'packagegroup-webos-extended', 'com.webos.app.swupdater']

Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-98534] CCC: Various build fixes

Change-Id: Ibb66aad05642540ef3c2f7b41cdea887b8db1de8