webos: ostree: use bfd even with ld-is-gold
:Release Notes:
Remove RDEPENDS:${PN}-ptest:remove which was already resolved upstream.

:Detailed Notes:
Fails to build with gold:
http://gecko.lge.com:8000/Errors/Details/588441
./.libs/libostree-1.so: error: undefined reference to 'gpg_strerror_r'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: Id08b2728d8a7cbd3b68c11aa1ee4c6cfdae68a91