webos: busybox: update the patches to apply on 1.37.0 version from oe-core
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/999029

ERROR: Applying patch '0003-libedit-check-for-null-before-passing-cmdedit_prompt.patch' on target directory 'busybox/1.37.0/busybox-1.37.0'
CmdError('quilt --quiltrc 1.37.0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0003-libedit-check-for-null-before-passing-cmdedit_prompt.patch
patching file libbb/lineedit.c
Hunk #1 FAILED at 490.
1 out of 1 hunk FAILED -- rejects in file libbb/lineedit.c
Patch 0003-libedit-check-for-null-before-passing-cmdedit_prompt.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ife80afe5a6f0e972d00133cebe2df8b07d391352