webos-raspberrypi: u-boot: update patch to apply on v2023.10
:Release Notes:
Upgraded in oe-core with:
https://git.openembedded.org/openembedded-core/commit/?id=6fce7f99ff5bacf7ad4b1816f462260fe41b38ee

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/708301

ERROR: Applying patch '0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/2023.10/git'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/2023.10/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch
patching file configs/rpi_3_32b_defconfig
Hunk #1 FAILED at 14.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_32b_defconfig
patching file configs/rpi_3_b_plus_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_b_plus_defconfig
patching file configs/rpi_3_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_defconfig
patching file configs/rpi_4_32b_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_32b_defconfig
patching file configs/rpi_4_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_defconfig
patching file configs/rpi_arm64_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_arm64_defconfig
patching file include/configs/rpi.h
Hunk #1 FAILED at 60.
1 out of 1 hunk FAILED -- rejects in file include/configs/rpi.h
Patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch does not apply (enforce with -f)

DISTRO_DEFAULTS was removed in:
90f626a5d8 rpi: Disable DISTRO_DEFAULTS

environment moved from include/configs/rpi.h to board/raspberrypi/rpi/rpi.env in:
fc2af2d978 arm: rpi: Switch to a text environment

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I6eb47c5e242da4dad3d1fbe856c82ec9858386d3