webos: ostree=webos3 (use bfd even with ld-is-gold)
:Release Notes:
Remove RDEPENDS:${PN}-ptest:remove which was already resolved upstream.

:Detailed Notes:
Fails to build with gold:
http://gecko.lge.com:8000/Errors/Details/588441
./.libs/libostree-1.so: error: undefined reference to 'gpg_strerror_r'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16197] CCC: Upgrade to Yocto 4.2 Mickledore
[WRR-2118] Create GPVB with Yocto 4.2 Mickledore

Cherry-picked-from-commit: 8b0bcf75b32e90048638816165b7340bc4adddea
Cherry-picked-from-branch: