webos: bluez5 (refresh patches to apply on 5.71 version)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/748755

ERROR: Applying patch '0012-Support-enabling-avdtp-delayReport.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.71/bluez-5.71'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.71/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0012-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
patching file profiles/audio/a2dp.h
patching file profiles/audio/avdtp.c
patching file profiles/audio/avdtp.h
patching file profiles/audio/media.c
Hunk #1 succeeded at 133 (offset 1 line).
Hunk #2 succeeded at 1494 (offset 44 lines).
Hunk #3 succeeded at 3321 (offset 78 lines).
patching file profiles/audio/media.h
Hunk #2 succeeded at 25 with fuzz 2 (offset -1 lines).
patching file src/adapter.c
Hunk #2 succeeded at 288 (offset 2 lines).
Hunk #3 succeeded at 369 (offset 2 lines).
Hunk #4 succeeded at 576 (offset 2 lines).
Hunk #5 succeeded at 3516 (offset 8 lines).
Hunk #6 FAILED at 3933.
Hunk #7 succeeded at 5352 (offset 41 lines).
Hunk #8 succeeded at 6898 (offset 41 lines).
Hunk #9 succeeded at 6943 (offset 41 lines).
Hunk #10 succeeded at 6954 (offset 41 lines).
1 out of 10 hunks FAILED -- rejects in file src/adapter.c
patching file src/adapter.h
patching file src/btd.h
patching file src/main.c
Hunk #2 succeeded at 1037 (offset 4 lines).
patching file src/main.conf
Patch 0012-Support-enabling-avdtp-delayReport.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: If1e2b507096a953d3803c6e4edf22996a9ff4340