buildah, crun, freeglut, llvm: Various bitbake world fixes
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'libxi' (but /data001/jenkins/gecko/webos_qemux86-64/build/meta-oe/meta-oe/recipes-graphics/freeglut/freeglut_3.4.0.bb DEPENDS on or otherwise requires it)
libxi was skipped: missing required distro feature 'x11' (not in DISTRO_FEATURES)
WARNING: preferred version 16.0.1 of llvm-native not available (for item llvm-native)
WARNING: versions of llvm-native available: 15.0.7
ERROR: Nothing RPROVIDES 'freeglut' (but /data001/jenkins/gecko/webos_qemux86-64/build/meta-oe/meta-oe/recipes-graphics/freeglut/freeglut_3.4.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'freeglut'
NOTE: Runtime target 'freeglut' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freeglut']
ERROR: Nothing RPROVIDES 'freeglut-dev' (but /data001/jenkins/gecko/webos_qemux86-64/build/meta-oe/meta-oe/recipes-graphics/freeglut/freeglut_3.4.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'freeglut-dev'
NOTE: Runtime target 'freeglut-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['freeglut-dev']

WARNING: preferred version 16.0.1 of llvm not available (for item llvm)
WARNING: versions of llvm available: 15.0.7
WARNING: preferred version 16.0.1 of llvm not available (for item llvm-dev)
WARNING: versions of llvm available: 15.0.7
WARNING: preferred version 16.0.1 of llvm not available (for item llvm-bugpointpasses)
WARNING: versions of llvm available: 15.0.7
WARNING: preferred version 16.0.1 of llvm not available (for item llvm-llvmhello)
WARNING: versions of llvm available: 15.0.7
WARNING: preferred version 16.0.1 of llvm not available (for item llvm-liboptremarks)
WARNING: versions of llvm available: 15.0.7
WARNING: preferred version 16.0.1 of llvm not available (for item llvm)
WARNING: versions of llvm available: 15.0.7

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Change-Id: I4620705b2ee0037c18380ca9d746cc9762d6dac8