connman=webos14 (refresh patches to apply on 1.38 version)
:Release Notes:

:Detailed Notes:
0020-Add-p2p-changes.patch this massive patch doesn't apply and
needs to be re-worked, looks like wifi.c was also reordered a
bit in it, which makes conflict resolution unnecessary painful.

This p2p patch also uses __connman_storage_open_service API
which was already removed in 1.38, so we need to revert this
change from upstream until connectivity team properly updates
these p2p changes for newer connman.

It also probably unnecessary restores e.g. include/types.h which was
already removed in upstream in 2013 with:
  commit 86d25926c8b6ccf22f261cc17d30fbdb2e4d0d14
  Author: Daniel Wagner <daniel.wagner@bmw-carit.de>
  Date:   Tue Jul 23 09:11:07 2013 +0200

    build: Remove unsued types.h header

so I wonder how this patch was created.

ERROR: connman-1.38-r0 do_patch: Command Error: 'quilt --quiltrc /data001/jenkins/gecko/clean-engineering-webos/BUILD/work/raspberrypi4-webos-linux-gnueabi/connman/1.38-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0020-Add-p2p-changes.patch
patching file Makefile.am
Hunk #2 succeeded at 128 (offset -1 lines).
patching file gsupplicant/dbus.c
patching file gsupplicant/dbus.h
patching file gsupplicant/gsupplicant.h
Hunk #7 succeeded at 570 (offset 3 lines).
Hunk #8 succeeded at 593 (offset 3 lines).
Hunk #9 succeeded at 627 (offset 3 lines).
Hunk #10 succeeded at 646 (offset 3 lines).
Hunk #11 succeeded at 678 (offset 3 lines).
Hunk #12 succeeded at 697 (offset 3 lines).
patching file gsupplicant/supplicant.c
Hunk #18 succeeded at 1603 (offset 18 lines).
Hunk #19 succeeded at 1821 (offset 18 lines).
Hunk #20 succeeded at 1853 (offset 18 lines).
Hunk #21 succeeded at 1879 (offset 18 lines).
Hunk #22 succeeded at 1975 (offset 18 lines).
Hunk #23 succeeded at 2686 (offset 18 lines).
Hunk #24 succeeded at 2715 (offset 18 lines).
Hunk #25 succeeded at 3136 (offset 18 lines).
Hunk #26 succeeded at 3288 (offset 18 lines).
Hunk #27 succeeded at 3760 (offset 18 lines).
Hunk #28 succeeded at 3794 (offset 18 lines).
Hunk #29 succeeded at 3868 (offset 18 lines).
Hunk #30 succeeded at 3928 (offset 18 lines).
Hunk #31 succeeded at 3944 (offset 18 lines).
Hunk #32 succeeded at 4009 (offset 18 lines).
Hunk #33 succeeded at 4037 (offset 18 lines).
Hunk #34 succeeded at 4061 (offset 18 lines).
Hunk #35 succeeded at 4078 (offset 18 lines).
Hunk #36 succeeded at 4091 (offset 18 lines).
Hunk #37 succeeded at 4107 (offset 18 lines).
Hunk #38 succeeded at 4144 (offset 18 lines).
Hunk #39 succeeded at 4162 (offset 18 lines).
Hunk #40 succeeded at 4215 (offset 18 lines).
Hunk #41 succeeded at 4229 (offset 18 lines).
Hunk #42 succeeded at 4318 (offset 18 lines).
Hunk #43 succeeded at 4460 (offset 18 lines).
Hunk #44 succeeded at 4486 (offset 18 lines).
Hunk #45 succeeded at 4533 (offset 18 lines).
Hunk #46 succeeded at 4587 (offset 18 lines).
Hunk #47 succeeded at 4597 (offset 18 lines).
Hunk #48 succeeded at 4613 (offset 18 lines).
Hunk #49 succeeded at 9245 (offset 18 lines).
Hunk #50 succeeded at 9266 (offset 18 lines).
Hunk #51 succeeded at 9657 (offset 18 lines).
Hunk #52 succeeded at 9676 (offset 18 lines).
Hunk #53 succeeded at 9838 (offset 18 lines).
Hunk #54 succeeded at 9873 (offset 18 lines).
Hunk #55 succeeded at 10143 (offset 18 lines).
Hunk #56 succeeded at 10252 (offset 18 lines).
patching file include/dbus.h
patching file include/device.h
patching file include/group.h
patching file include/network.h
patching file include/peer.h
patching file include/sd.h
patching file include/technology.h
patching file include/types.h
patching file plugins/wifi.c
Hunk #2 succeeded at 63 with fuzz 2 (offset 2 lines).
Hunk #3 succeeded at 75 with fuzz 1 (offset 2 lines).
Hunk #4 succeeded at 177 (offset 2 lines).
Hunk #5 succeeded at 193 (offset 2 lines).
Hunk #6 succeeded at 213 (offset 2 lines).
Hunk #7 FAILED at 262.
Hunk #8 succeeded at 3720 (offset 2 lines).
Hunk #9 succeeded at 3736 (offset 2 lines).
Hunk #10 succeeded at 4063 (offset 2 lines).
Hunk #11 succeeded at 4085 (offset 2 lines).
Hunk #12 succeeded at 4114 (offset 2 lines).
1 out of 12 hunks FAILED -- rejects in file plugins/wifi.c
patching file src/connman.h
Hunk #2 succeeded at 464 (offset -1 lines).
Hunk #3 succeeded at 558 (offset -1 lines).
Hunk #4 succeeded at 574 (offset -1 lines).
Hunk #5 succeeded at 699 (offset -1 lines).
Hunk #6 succeeded at 851 (offset -1 lines).
Hunk #7 succeeded at 1007 (offset -1 lines).
Hunk #8 succeeded at 1024 (offset -1 lines).
Hunk #9 succeeded at 1117 (offset -1 lines).
patching file src/dbus.c
patching file src/device.c
patching file src/dhcp.c
patching file src/group.c
patching file src/ippool.c
patching file src/manager.c
patching file src/network.c
patching file src/p2pgo.c
patching file src/peer.c
patching file src/peer_service.c
patching file src/sd.c
patching file src/service.c
Hunk #1 succeeded at 7280 (offset 126 lines).
patching file src/storage.c
Hunk #1 succeeded at 263 (offset -22 lines).
Hunk #2 succeeded at 281 (offset -22 lines).
Hunk #3 succeeded at 465 (offset -22 lines).
patching file src/technology.c
patching file src/util.c
Patch 0020-Add-p2p-changes.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth
[PLAT-137851] CCC: connman=v1.39

Change-Id: Idda857654f73e2ae9523af5e036513b328ab734a