meta-webos-raspberrypi: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-raspberrypi failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...ERROR: ParseError at /OE/meta-webosose/meta-webos-raspberrypi/recipes-webos/videooutputd/videooutput-adaptation-layer-rpi.bb:14: Could not inherit file classes/webos_component.bbclass

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

INFO: ERROR: test_parse (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-raspberrypi failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
ERROR: No recipes in default available for:
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-bsp/bootfiles/rpi-config_git.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-bsp/rpi-u-boot-scr/rpi-u-boot-scr.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-connectivity/pi-bluetooth/pi-bluetooth_%.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-core/images/rpi-test-image.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-core/packagegroups/packagegroup-rpi-test.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-graphics/userland/userland_git.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-kernel/linux/linux-raspberrypi_%.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-kernel/linux/linux-raspberrypi_4.19.bbappend
  /OE/meta-webosose/meta-webos-raspberrypi/recipes-kernel/linux/linux-raspberrypi_5.4.bbappend
Parsing of 2783 .bb files complete (0 cached, 2783 parsed). 4276 targets, 295 skipped, 0 masked, 0 errors.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I937b5610d35760aff23dd4cf4a3ca76cbeb9df53