com.webos.app.{home,settings}: enable openssl-legacy-provider in nodejs
:Release Notes:

:Detailed Notes:
works around:
NOTE: Use ENACT_DEV_LEGACY
Creating an optimized production build...
0%  compiling
10%  building 0/0 modules
10%  building 0/1 modules  @enact/dev-utils/plugins/SnapshotPlugin/snapshot-helper.js /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/git
10%  building 1/1 modules
10%  building 1/2 modules  src/index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:471:10)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:503:5
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:358:12
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.home/0.1.0-19-r3/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

NOTE: Bundling Enact app to /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/image/usr/palm/applications/com.palm.app.settings
NOTE: Use ENACT_DEV
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Creating an optimized production build...
0%  compiling
10%  building 0/0 modules
10%  building 0/1 modules  @enact/dev-utils/plugins/SnapshotPlugin/snapshot-helper.js /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/git
10%  building 1/1 modules
10%  building 1/2 modules  src/index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.settings/1.1.0-19-r3/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

but surprisingly in these cases the do_install didn't fail and the build just
created PN with just empty directory, unlike e.g.
http://gecko.lge.com/Errors/Details/389014

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I8928c7be09e31a5db056f8a25e00ca6b693b5748