webos: qtbase=webos122
:Release Notes:
Respect DISTRO_FEATURES when setting PACKAGECONFIG and RRECOMMENDS.

:Detailed Notes:
ERROR: Nothing PROVIDES 'virtual/egl' (but
  meta-qt6/recipes-qt/qt6/qtbase_git.bb DEPENDS on or otherwise requires it)
vc-graphics PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics
vc-graphics-hardfp PROVIDES virtual/egl but was skipped: PREFERRED_PROVIDER_virtual/libgles2 set to mesa, not vc-graphics-hardfp
ERROR: Nothing PROVIDES 'virtual/egl-native' (but
  virtual:native:meta-qt6/recipes-qt/qt6/qtbase_git.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/libx11-native
  virtual/make-native
  virtual/mesa-native

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: qtbase=webos122
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Change-Id: If7bb1c4191a4f2a9f5dc82ee5747368af809d0fb
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/404111
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>