webruntime: add PACKAGECONFIG for gbm, drm, xcb, x11 auto-platform and enable gbm, drm by default
:Release Notes:
explicitly disable xcb to fix:
git/src/third_party/swiftshader/include/vulkan/vulkan.h:54:10: fatal error: xcb/xcb.h: No such file or directory

:Detailed Notes:
I've tried to enable drm ozone_platform in webruntime, but unfortunately
the ozone/aura_desktop integration doesn't seem to support it yet:

http://gecko.lge.com/Errors/Details/419040

FAILED: libcbe.so libcbe.so.TOC
TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysroot-native/usr/bin/python3-native/python3 "../../git/src/build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libcbe.so" --tocfile="./libcbe.so.TOC" --output="./libcbe.so" -- x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysroot -shared -Wl,-soname="libcbe.so" -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--threads -Wl,--thread-count=4 -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -LTOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/91.0.4472.114-18-r53.4/recipe-sysrootTOPDIR/BUILD/work/qemux86_64-webos-linux/webos-wayland-extensions/1.0.0-43-r6/recipe-sysroot/usr/lib -o "./libcbe.so" @"./libcbe.so.rsp"
obj/ozone/ui/desktop_aura/views_ozone_wayland/desktop_factory_ozone_list.o:desktop_factory_ozone_list.cc:ui::PlatformConstructorList<views::DesktopFactoryOzone>::kConstructors: error: undefined reference to 'views::CreateDesktopFactoryOzoneDrm()'
collect2: error: ld returned 1 exit status

There is CreateDesktopFactoryOzone only for Headless, Egltest, Wayland, Wayland_external platforms.

And even changing src/ui/ozone/generate_constructor_list.py to generate just for Headless instead
of all enabled ozone platforms has own issues as well, so maybe it's not worth spending more time
on this now. It isn't resolved in 94 version as well and upstream chromium doesn't have
src/ozone/ui/desktop_aura at all, only src/ui/views/widget/desktop_aura, maybe worth re-investigating
later when upgrading to chromium with ozone fully integrated in upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=578890
in LGE fork this src/ozone/ui comes from neva/chromium 1.5:
https://github.com/webosose/chromium91/commit/7cef9376f8f6f59d7dc8f572716c1aaf28b3d9b2
and there is e.g. src/ozone/patches/0002-Adapt-DesktopFactoryOzone-to-respect-ozone-platform-.patch from 2015:
https://github.com/webosose/chromium91/blob/master/src/ozone/patches/0001-Browser-Support-Desktop-Aura-creation-on-Ozone.patch
which probably needs to be refreshed as well.

This issue is AFAIK only reproducible on emulator, on rpi4 it
was working OK with new mesa-22.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I4f5c8a07ad94ff9a952235bbf6175d1e0929c464