base-passwd: add man:man and unblacklist a few recipes
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'libssh2' (but /data001/jenkins/gecko/webos_qemux86-64/build/oe-core/meta/recipes-devtools/rust/cargo_1.67.1.bb DEPENDS on or otherwise requires it)
libssh2 was skipped: Recipe will be skipped because: Depends on blacklisted man-db since https://git.openembedded.org/meta-openembedded/commit/?id=b3e9b51c9ba58b01e55c5b0a9a9bec3f7f06d07a
ERROR: Nothing RPROVIDES 'cargo' (but /data001/jenkins/gecko/webos_qemux86-64/build/oe-core/meta/recipes-core/packagegroups/packagegroup-rust-sdk-target.bb, /data001/jenkins/gecko/webos_qemux86-64/build/oe-core/meta/recipes-devtools/rust/cargo_1.67.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cargo'
NOTE: Runtime target 'cargo' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cargo']
NOTE: Runtime target 'packagegroup-rust-sdk-target' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-rust-sdk-target', 'cargo']
ERROR: Nothing RPROVIDES 'cargo-dev' (but /data001/jenkins/gecko/webos_qemux86-64/build/oe-core/meta/recipes-devtools/rust/cargo_1.67.1.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'cargo-dev'
NOTE: Runtime target 'cargo-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['cargo-dev']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12470] Update users and groups in the image
[WRP-12469] Bitbake world issues 2023-04-01

Change-Id: I4f9782984c118ab8a8b9ec181f49e166a5d5493e