com.webos.app.videocall: enable openssl-legacy-provider in nodejs
:Release Notes:

:Detailed Notes:
Works around issues like in:
NOTE: Bundling Enact app to /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/image/usr/palm/applications/com.webos.app.videocall
NOTE: Use ENACT_DEV
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Creating an optimized production build...
0%  compiling
10%  building 0/0 modules
10%  building 0/1 modules  @enact/dev-utils/plugins/SnapshotPlugin/snapshot-helper.js /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/git
10%  building 1/1 modules
10%  building 1/2 modules  src/index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:471:10)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:503:5
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/webpack/lib/NormalModule.js:358:12
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.videocall/0.0.1-1-r0/recipe-sysroot-native/opt/cli/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

until webpack is updated to some supported hash function.

This doesn't cause do_install to fail unfortunately, only results in do_convert_webos_preferred_gfx_image_format failure later:
http://gecko.lge.com:8000/Errors/Details/447574

DEBUG: Executing python function do_convert_webos_preferred_gfx_image_format
ERROR: Could not find com.webos.app.videocall:appinfo.json, no conversion will be performed
DEBUG: Python function do_convert_webos_preferred_gfx_image_format finished

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I6ba9f190b8c33855a5587bbd86ea93259638da5d