webos: fluentbit=r2 (use gnu17 even with gcc-15)
:Release Notes:
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/1139985
fluentbit/1.7.4/git/src/proxy/go/go.c:110:11: error: too many arguments to function 'plugin->cb_init'; expected 0, have 1
fluentbit/1.7.4/build/src/record_accessor/ra_parser.c:69:25: error: too many arguments to function 'flb_ra_lex'; expected 0, have 2
fluentbit/1.7.4/build/src/stream_processor/parser/sql_parser.c:69:25: error: conflicting types for 'flb_sp_lex'; have 'int(void)'
fluentbit/1.7.4/build/src/stream_processor/parser/sql_parser.c:69:25: error: too many arguments to function 'flb_sp_lex'; expected 0, have 2
fluentbit/1.7.4/git/include/fluent-bit/stream_processor/flb_sp_timeseries.h:330:5: error: initialization of 'struct timeseries * (*)(int)' from incompatible pointer type 'struct timeseries * (*)(void)' [-Wincompatible-pointer-types]
fluentbit/1.7.4/git/include/fluent-bit/stream_processor/flb_sp_timeseries.h:331:5: error: initialization of 'struct timeseries * (*)(int)' from incompatible pointer type 'struct timeseries * (*)(void)' [-Wincompatible-pointer-types]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I7426e13bf74ea393e87f5283a3af9a6f32121f14