webruntime: fix build with clang-17
:Release Notes:
Backport a patch from newer chromium to fix build with clang-17 now in
meta-clang/master.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/696394
FAILED: obj/base/neva/neva/neva_paths.o
../../git/src/third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/neva/neva/neva_paths.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_GAV=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DUSE_WEBRISK_DATABASE=1 -DUSE_NEVA_PUNCH_HOLE=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=43 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-14-init-1002-gb5e470aa-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DCR_SYSROOT_HASH=43a87bbebccad99325fdcf34166295b121ee15c7 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/abseil-cpp -Wno-unused-variable -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../git/src/tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -Wno-inline-asm -Wmax-tokens -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ptr-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti --sysroot=../../recipe-sysroot -fvisibility-inlines-hidden      -ITOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime-clang/94.0.4606.128-43/recipe-sysroot/usr/include/c++/v1       -ITOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime-clang/94.0.4606.128-43/recipe-sysroot/usr/include/cbe     -ITOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime-clang/94.0.4606.128-43/recipe-sysroot/usr/include/cbe/gmp     -ITOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime-clang/94.0.4606.128-43/recipe-sysroot/usr/include/media-resource-calculator-clang   -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -c ../../git/src/base/neva/neva_paths.cc -o obj/base/neva/neva/neva_paths.o
In file included from ../../git/src/base/neva/neva_paths.cc:20:
In file included from ../../git/src/base/files/file_util.h:21:
In file included from ../../git/src/base/containers/span.h:18:
../../git/src/base/containers/checked_iterators.h:241:8: error: no template named '__is_cpp17_contiguous_iterator'; did you mean '__libcpp_is_contiguous_iterator'?
struct __is_cpp17_contiguous_iterator<::base::CheckedContiguousIterator<T>>
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __libcpp_is_contiguous_iterator
TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime-clang/94.0.4606.128-43/recipe-sysroot/usr/include/c++/v1/__iterator/iterator_traits.h:482:8: note: '__libcpp_is_contiguous_iterator' declared here
struct __libcpp_is_contiguous_iterator : false_type {};
       ^
1 error generated.

The same error and the same fix is applicable for 108 version as well:
http://gecko.lge.com:8000/Errors/Details/696321

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-27901] CCC: Various build fixes

Change-Id: I22f694c956d3a8afad6eddacff54a484d383b005