webos: googletest-clang=r2 (rename to match googletest recipe name from meta-oe)
:Release Notes:
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_git.bb to _1.13.0.bb.

:Detailed Notes:
Fixes parsing error:

  Parsing recipes...
  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang.bb:5:
  Could not include required file recipes-test/googletest/googletest_git.bb

after:
https://git.openembedded.org/meta-openembedded/commit/?id=46266e59ff36b38f46a67573528cee658960c764

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16197] CCC: Upgrade to Yocto 4.2 Mickledore
[WRR-2118] Create GPVB with Yocto 4.2 Mickledore

Cherry-picked-from-commit: 49f7164fc723b89e963db30436fabb11cf5e71e6
Cherry-picked-from-branch: