Manually fix the conversion
:Release Notes:

:Detailed Notes:
ERROR: meta-webosose/meta-webos/recipes-webos/jemalloc/jemalloc.bb:
  Variable do_generate_toolchain_file_append contains an operation using the old override syntax.
  Please convert this layer/metadata before attempting to use with a newer bitbake.
ERROR: oe-core/meta/recipes-extended/iptables/iptables_1.8.7.bb:
  Variable RDEPENDS_${PN}-apply_append_class-target contains an operation using the old override syntax.
  Please convert this layer/metadata before attempting to use with a newer bitbake.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I8bd5a19d2547c4f3b6540dac7040b373c66ecb8c