webos: googleapis=r1 (remove cpp_features.pb.h as well)
:Release Notes:
It's provided by newer protobuf as well as shown after upgrade
to 4.25.2 in:
https://git.openembedded.org/meta-openembedded/commit/?id=4f75e957e75d231e9baad5f8ddf6402a64f1523b

:Detailed Notes:
Fixes libgoogleassistant:
http://gecko.lge.com:8000/Errors/Details/764492

DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['TOPDIR/meta-lg-webos/meta-webos/recipes-multimedia/pulseaudio-15/pulseaudio_15.0.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-upstreamable/googleapis/googleapis_git.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-upstreamable/snowboy/snowboy_1.3.0.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/cmake-modules-webos/cmake-modules-webos-native.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/pmloglib/pmloglib.bb:do_populate_sysroot', 'TOPDIR/meta-oe/meta-oe/recipes-devtools/grpc/grpc_1.60.0.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glib-2.0/glib-2.0_2.78.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glibc/glibc_2.38.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/cmake/cmake-native_3.27.7.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-cross_13.2.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-runtime_13.2.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/json-c/json-c_0.17.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ccache/ccache_4.9.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ninja/ninja_1.11.1.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot']
ERROR: The file /usr/include/google/protobuf/cpp_features.pb.h is installed by both protobuf and googleapis, aborting
DEBUG: Python function extend_recipe_sysroot finished

com.webos.service.tts:
http://gecko.lge.com:8000/Errors/Details/764493

DEBUG: Executing python function extend_recipe_sysroot
NOTE: Direct dependencies are ['TOPDIR/meta-lg-webos/meta-webos/recipes-multimedia/pulseaudio-15/pulseaudio_15.0.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-upstreamable/googleapis/googleapis_git.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/cmake-modules-webos/cmake-modules-webos-native.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/libpbnjson/libpbnjson.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/luna-service2/luna-service2.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/pmloglib/pmloglib.bb:do_populate_sysroot', 'TOPDIR/meta-oe/meta-oe/recipes-devtools/grpc/grpc_1.60.0.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glib-2.0/glib-2.0_2.78.3.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/glibc/glibc_2.38.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-core/systemd/systemd-systemctl-native.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/cmake/cmake-native_3.27.7.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-cross_13.2.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/gcc/gcc-runtime_13.2.bb:do_populate_sysroot', 'TOPDIR/oe-core/meta/recipes-devtools/json-c/json-c_0.17.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ccache/ccache_4.9.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/icecc-create-env/icecc-create-env_0.1.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ninja/ninja_1.11.1.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot']
ERROR: The file /usr/include/google/protobuf/cpp_features.pb.h is installed by both protobuf and googleapis, aborting
DEBUG: Python function extend_recipe_sysroot finished

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: Ia4a3f893fed0fe066bd03ecdabcc4d12a6fc07ab