webos: gstreamer1.0-plugins-bad: update patch to apply on 1.22.4 version
:Release Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=d7bf88db7f2f55540bf7891474a3a28f5681ddbb
backported to mickledore as well in:
https://git.openembedded.org/openembedded-core/commit/?h=mickledore&id=a071696747ece93409d533a2e966cd59195a056d

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/623492

ERROR: Applying patch '0004-waylandsink-remove-unsupported-subcompositor.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.4-r0/gst-plugins-bad-1.22.4'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/gstreamer1.0-plugins-bad/1.22.4-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0004-waylandsink-remove-unsupported-subcompositor.patch
patching file ext/wayland/gstwaylandsink.c
patching file ext/wayland/gstwaylandsink.h
patching file gst-libs/gst/wayland/gstwldisplay.c
patching file gst-libs/gst/wayland/gstwlwindow.c
Hunk #3 succeeded at 167 (offset 4 lines).
Hunk #4 succeeded at 187 (offset 4 lines).
Hunk #5 succeeded at 197 (offset 4 lines).
Hunk #6 succeeded at 207 (offset 4 lines).
Hunk #7 succeeded at 216 (offset 4 lines).
Hunk #8 succeeded at 271 (offset 4 lines).
Hunk #9 succeeded at 283 (offset 4 lines).
Hunk #10 succeeded at 303 (offset 4 lines).
Hunk #11 succeeded at 318 (offset 4 lines).
Hunk #12 succeeded at 348 (offset 4 lines).
Hunk #13 succeeded at 387 (offset 4 lines).
Hunk #14 succeeded at 402 (offset 4 lines).
Hunk #15 succeeded at 435 (offset 4 lines).
Hunk #16 succeeded at 458 (offset 4 lines).
Hunk #17 FAILED at 476.
Hunk #18 succeeded at 616 (offset 5 lines).
Hunk #19 succeeded at 669 (offset 5 lines).
1 out of 19 hunks FAILED -- rejects in file gst-libs/gst/wayland/gstwlwindow.c
Patch 0004-waylandsink-remove-unsupported-subcompositor.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-691] Create GPVB with Yocto 4.3 Nanbield
[WRQ-693] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I65381c6a3b7e0f65ceabf592d34d807972867b1c