webos: pulseaudio: add oss-output PACKAGECONFIG
:Release Notes:
Backport:
https://git.openembedded.org/openembedded-core/commit/?id=c74a7382f4e3c6516c97b1473731a27c57b4e0aa
to our copy of old .inc file.

:Detailed Notes:
The next commit:
https://git.openembedded.org/openembedded-core/commit/?id=67cbec2aa1e7dca1abacf39a22efe85fa47a468d
pulseaudio: Remove from time64.inc exception list

causes http://gecko.lge.com:8000/Errors/Details/886818
lib32-pulseaudio/15.0-39*/lib32-recipe-sysroot/usr/include/features-time64.h:26:5: error: #error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
   26 | #   error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
      |     ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I372902d28ad59aca705a28f6d6d907aa12036200