webos: bluez5 (refresh patches to apply on 5.83 version)
:Release Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=83d217503d565ba60dcec9382afb828deefa962b

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1212569

Applying patch 0006-recievePassThrough-commad-support-required-for-webos.patch
patching file profiles/audio/avctp.c
patching file src/device.c
Hunk #1 succeeded at 196 with fuzz 1 (offset 8 lines).
Hunk #2 succeeded at 311 (offset 11 lines).
Hunk #3 succeeded at 1575 (offset 88 lines).
Hunk #4 succeeded at 1605 (offset 88 lines).
Hunk #5 succeeded at 1619 (offset 88 lines).
Hunk #6 succeeded at 2480 (offset 98 lines).
Hunk #7 succeeded at 3726 (offset 122 lines).
Hunk #8 succeeded at 4922 (offset 228 lines).
patching file src/device.h
Hunk #1 succeeded at 219 (offset 3 lines).

Now at patch 0006-recievePassThrough-commad-support-required-for-webos.patch

ERROR: Applying patch '0007-Added-dbus-signal-for-MediaPlayRequest.patch' on target directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/bluez5/5.83/bluez-5.83'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/qemux86_64-webos-linux/bluez5/5.83/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0007-Added-dbus-signal-for-MediaPlayRequest.patch
patching file profiles/audio/avrcp.c
patching file profiles/audio/media.c
Hunk #1 succeeded at 2057 (offset 23 lines).
patching file src/device.c
Hunk #1 succeeded at 2489 (offset 98 lines).
Hunk #2 succeeded at 3621 (offset 116 lines).
Hunk #3 FAILED at 4704.
1 out of 3 hunks FAILED -- rejects in file src/device.c
patching file src/device.h
Hunk #1 succeeded at 221 (offset 3 lines).
Patch 0007-Added-dbus-signal-for-MediaPlayRequest.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I1445cdb7fa3a9f032e48b8e31a2f6c3c99e07270