node-gyp-native: upgrade to 6.1.0 to support python3
see https://github.com/webOS-ports/meta-webos-ports/commit/8be4140a19e19e1e613ae049134ef566d7201b77

* building iwht older node-gyp-native-4.0.0 and python3native fails:
ERROR: nodejs-module-webos-pmlog-3.0.1-1+gitAUTOINC+8ebc759caf-r0
do_configure: Execution of
'/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/temp/run.do_configure.16893'
failed with exit code 1:
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.14.1 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Python executable
"/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/recipe-sysroot-native/usr/bin/python3-native/python3"
is v3.8.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >=
v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion
(/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/recipe-sysroot-native/usr/lib/node_modules/node-gyp/lib/configure.js:494:19)
gyp ERR! stack     at PythonFinder.<anonymous>
(/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/recipe-sysroot-native/usr/lib/node_modules/node-gyp/lib/configure.js:476:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:286:7)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous>
(internal/child_process.js:430:11)
gyp ERR! stack     at Socket.emit (events.js:223:5)
gyp ERR! stack     at Pipe.<anonymous> (net.js:664:12)
gyp ERR! System Linux 5.3.0-26-generic
gyp ERR! command
"/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/recipe-sysroot-native/usr/bin/node"
"/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/recipe-sysroot-native/usr/bin/node-gyp"
"--arch" "x86_64" "--nodedir"
"/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/node-v10.15.3"
"configure"
gyp ERR! cwd
/OE/build/luneos-master/webos-ports/tmp-glibc/work/core2-64-webos-linux/nodejs-module-webos-pmlog/3.0.1-1+gitAUTOINC+8ebc759caf-r0/git
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

* this check was moved from configure.js to separate find-python.js in
5.0.3
  nodejs/node-gyp@7e7fce3#diff-7ad6309831a48a234780b58baca65710
* and python3 was conditionally enabled in 5.0.3:
  nodejs/node-gyp@66ad305#diff-84cf2fbe4f6499183110a28ad194d0a4
* and since 6.0.0 python3 is used by default:
  nodejs/node-gyp@3d1c60a#diff-84cf2fbe4f6499183110a28ad194d0a4

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

Change-Id: Iedb491a05d12a154cceb4fb9bfdb0589e6cf9804
Signed-off-by: Martin Jansa <martin.jansa@lge.com>