webos: wireguard-tools=webos2 (respect VIRTUAL-RUNTIME_bash in PACKAGECONFIG)
:Release Notes:
After:
https://git.openembedded.org/meta-openembedded/commit/?id=865411fbde1f3489e77ad186e669b5c315485ce1
this fails again with:
ERROR: QA Issue: lib32-wireguard-tools rdepends on lib32-bash, but it isn't a build dependency, missing lib32-bash in DEPENDS or PACKAGECONFIG? [build-deps]
in multilib builds.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/730044

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: b661ec067c9bb36539974a36876394d02106849e
Cherry-picked-from-branch: