webos.inc: packagegroup-core-buildessential mark as MACHINE_ARCH
:Release Notes:
Change it back from TUNE_PKGARCH to MACHINE_ARCH.

:Detailed Notes:
As detected by:
oe-core/scripts/sstate-diff-machines.sh --tmpdir=BUILD --machines="qemux86 qemux86copy qemuarm" --targets=packagegroup-core-buildessential --analyze

 === Comparing signatures for task do_package_write_ipk.sigdata between qemux86 and qemux86copy ===
ERROR: packagegroup-core-buildessential different signature for task do_package_write_ipk.sigdata between qemux86 and qemux86copy
NOTE: Starting bitbake server...
Hash for dependent task pkgconfig/pkgconfig_git.bb:do_packagedata changed from 4caf0b6e809f10311dcb8c8396249532c477f77b32c262e18611bd36388a9afc to a50cef2f73fb4839df9a5f0374d71e308968e74d05ffd2a3fa0dbe9e2c60a5e8
Unable to find matching sigdata for /jenkins/home/anaconda/build-webos-kirkstone/build/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_packagedata with hashes 4caf0b6e809f10311dcb8c8396249532c477f77b32c262e18611bd36388a9afc or a50cef2f73fb4839df9a5f0374d71e308968e74d05ffd2a3fa0dbe9e2c60a5e8

Further analysis show why:

$ bitbake-diffsigs BUILD/sstate-diff/1638404008/qemux86*/*/packagegroup-core-buildessential/*do_package_write*
Hash for dependent task pkgconfig/pkgconfig_git.bb:do_packagedata changed from a50cef2f73fb4839df9a5f0374d71e308968e74d05ffd2a3fa0dbe9e2c60a5e8 to 4caf0b6e809f10311dcb8c8396249532c477f77b32c262e18611bd36388a9afc
Unable to find matching sigdata for /jenkins/mjansa/build/webos/kirkstone/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_packagedata with hashes a50cef2f73fb4839df9a5f0374d71e308968e74d05ffd2a3fa0dbe9e2c60a5e8 or 4caf0b6e809f10311dcb8c8396249532c477f77b32c262e18611bd36388a9afc

$ bitbake-diffsigs BUILD/sstate-diff/1638404008/qemux86*/*/pkgconfig/*do_packagedata*
Hash for dependent task pkgconfig/pkgconfig_git.bb:do_package changed from 4d75db6f6d3180273071b8a9f875135b792ee8c1fc9d463be00b9d5f47ded907 to 0ba1221c9a5e1733a9119896edad8b8112c4d83220b9042c9da6c0ad58fd90e6
Unable to find matching sigdata for /jenkins/mjansa/build/webos/kirkstone/oe-core/meta/recipes-devtools/pkgconfig/pkgconfig_git.bb:do_package with hashes 4d75db6f6d3180273071b8a9f875135b792ee8c1fc9d463be00b9d5f47ded907 or 0ba1221c9a5e1733a9119896edad8b8112c4d83220b9042c9da6c0ad58fd90e6

$ bitbake-diffsigs BUILD/sstate-diff/1638404008/qemux86*/*/pkgconfig/*do_prepare_rec*
Hash for dependent task libtool/libtool-cross_2.4.6.bb:do_populate_sysroot changed from 327c754837bcffe1b782b0c51b63ea2bc15173a06e7fea0556a32cb25c4b8ced to a1811b497929ef230
d0aca5d550edf8fad2e6720f71256a1c0333bb1b723107c
Unable to find matching sigdata for /jenkins/mjansa/build/webos/kirkstone/oe-core/meta/recipes-devtools/libtool/libtool-cross_2.4.6.bb:do_populate_sysroot with hashes 327c75
4837bcffe1b782b0c51b63ea2bc15173a06e7fea0556a32cb25c4b8ced or a1811b497929ef230d0aca5d550edf8fad2e6720f71256a1c0333bb1b723107c

$ bitbake-diffsigs BUILD/sstate-diff/1638404008/qemux86*/*/libtool-cross/*do_deploy_source*
basehash changed from f163be276ca34f2fb6bd417df4ed3c89bd632822256a9c30a364412992acf8e7 to a732e04772b288f435eedcbd67e0607616fa3a702ff7f5ed95778cbbfce240c6
Variable MACHINE value changed from 'qemux86copy' to 'qemux86'
Variable SSTATE_MANMACH value changed from 'qemux86copy' to 'qemux86'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone