webos: audiod=r38
:Release Notes:
Fix build error

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1095506

FAILED: CMakeFiles/audiod.dir/src/PulseAudioLink.cpp.o
..
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/recipe-sysroot/usr/include/lttng/tracepoint-rcu.h:10,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/recipe-sysroot/usr/include/lttng/tracepoint.h:13,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/git/include/pmtrace_audiod_provider.h:31,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/git/include/audiodTracer.h:22,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/git/include/PulseAudioLink.h:28,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/git/src/PulseAudioLink.cpp:18:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/audiod/1.0.0-77/recipe-sysroot/usr/include/urcu/compiler.h:205:1: error: template with C linkage

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-20814] [NANO] CCC: audiod=r38
[WRR-17603] Fix build with liburcu-0.15.0

Change-Id: I94b1506d7017d5b71e8f980d7eca56c0fbfeaccd