webos: opencv: rename bbappend and remove 1 backported patch
:Release Notes:
It was backported from v4.6.0 which is already in langdale since:
https://git.openembedded.org/meta-openembedded/commit/?h=langdale&id=703b3c511b52a99185a62f3d8a4ec8d6ec388daa
But for v4.6.0 we need to backport different change to fix build
with newer ffmpeg.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/642905

FAILED: modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ -DCVAPI_EXPORTS -DENABLE_PLUGINS -DHAVE_CAMV4L2 -DHAVE_FFMPEG -DHAVE_GPHOTO2 -DHAVE_GSTREAMER -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/build/modules/videoio -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/core/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/imgproc/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/imgcodecs/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/include/eigen3 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/build -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/3rdparty/include/opencl/1.2 -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot/usr/include/gphoto2 -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -ITOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/include  -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git=/usr/src/debug/opencv/4.6.0-r0  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git=/usr/src/debug/opencv/4.6.0-r0  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/build=/usr/src/debug/opencv/4.6.0-r0  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/build=/usr/src/debug/opencv/4.6.0-r0  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden    -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -mssse3 -DNDEBUG  -DNDEBUG -fPIC -std=c++11 -MD -MT modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o -MF modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o.d -o modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_ffmpeg.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/cap_ffmpeg.cpp
In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/cap_ffmpeg_impl.hpp:81,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/cap_ffmpeg.cpp:50:
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:80:6: warning: "LIBAVCODEC_VERSION_INT" is not defined, evaluates to 0 [-Wundef]
   80 | #if (LIBAVCODEC_VERSION_INT <= AV_VERSION_INT(54, 51, 100))
      |      ^~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:270:5: warning: "LIBAVCODEC_VERSION_INT" is not defined, evaluates to 0 [-Wundef]
  270 | #if LIBAVCODEC_VERSION_INT>0x000409
      |     ^~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:277:5: warning: "LIBAVCODEC_VERSION_INT" is not defined, evaluates to 0 [-Wundef]
  277 | #if LIBAVCODEC_VERSION_INT>((50<<16)+(1<<8)+0)
      |     ^~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:286:5: warning: "LIBAVCODEC_VERSION_INT" is not defined, evaluates to 0 [-Wundef]
  286 | #if LIBAVCODEC_VERSION_INT>((51<<16)+(11<<8)+0)
      |     ^~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:295:5: warning: "LIBAVCODEC_VERSION_INT" is not defined, evaluates to 0 [-Wundef]
  295 | #if LIBAVCODEC_VERSION_INT>=((51<<16)+(49<<8)+0)
      |     ^~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:81:26: error: 'CODEC_ID_H264' was not declared in this scope; did you mean 'AV_CODEC_ID_H264'?
   81 | #define AV_CODEC_ID_H264 CODEC_ID_H264
      |                          ^~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/opencv/4.6.0-r0/git/modules/videoio/src/ffmpeg_codecs.hpp:81:26: note: in definition of macro 'AV_CODEC_ID_H264'
   81 | #define AV_CODEC_ID_H264 CODEC_ID_H264
      |                          ^~~~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-597] Create GPVB with Yocto 4.1 Langdale

Change-Id: I6f8a2419a9bd7cd94d01c39ca2e7c75d680068be