solana: move to meta-webos/dynamic-layers/clang-layer
:Release Notes:
solana and sugar depends on clang-native which is provided by meta-clang

:Detailed Notes:
Fixes:
ERROR: Nothing PROVIDES 'clang-native' (but
  meta-webos/recipes-upstreamable/sugar/sugar_1.1.0.bb,
  meta-webos/recipes-upstreamable/solana/solana-cli_1.14.5.bb,
  meta-webos/recipes-upstreamable/solana-program-library/solana-program-library_git.bb,
  meta-webos/recipes-upstreamable/solana/solana-keygen_1.14.5.bb
  DEPENDS on or otherwise requires it).
Close matches:
  glslang-native
  slang-native
  tclap-native
without meta-clang in the build.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Change-Id: I875f1fe259a65f437341646dba4d61997ec46163