webos: libedgetpu=11 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:

http://gecko.lge.com:8000/Errors/Details/1142324

TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/libedgetpu/grouper/git/makefile_build/../driver/usb/usb_device_interface.h:131:5: error: 'uint8_t' does not name a type
  131 |     uint8_t request_type;
      |     ^~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I5b937b547ebf7dbe0db079715812fcd99b367e7f