libcyusbserial: fix installed-vs-shipped QA issue with multilib
:Release Notes:
Backport changes from
https://lists.openembedded.org/g/openembedded-devel/message/104698

:Detailed Notes:
testing ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR} existence
doesn't really work in cross compilation and on some hosts was causing:

ERROR: QA Issue: libcyusbserial: Files/directories were installed but not shipped in any package:
  /usr/lib/libcyusbserial.so.1
  /usr/lib/libcyusbserial.so
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
libcyusbserial: 2 installed and not shipped files. [installed-vs-shipped]

with multilib using /usr/lib32 or /usr/lib64 when the same didn't
exist on host

Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-20118] Bitbake world issues 2023-07
[WRP-26053] CCC: Various build fixes

Change-Id: I60f262ec26efefa9b6a9852626c44dd1f8e84ffc