webos: qttools: disable clang support even when meta-clang is included
:Release Notes:
Fails with clang-19

:Detailed Notes:
Avoids
http://gecko.lge.com:8000/Errors/Details/953040
qttools-native/6.7.2/git/src/linguist/lupdate/clangtoolastreader.cpp:785:73: error: <C3><A2><C2><80><C2><98>const class clang::FileEntry has no member named getName

FileEntry::GetName() was deprecated since clang-17 and removed in clang-19 with:
https://github.com/llvm/llvm-project/commit/6c1dbd5359c4336d03b11faeaea8459b421f2c5c

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I925830cf4f849f51c17b52e26e9c50712022961c