webos.inc: Add webos_oss_pkg_info to IMAGE_CLASSES only in webos_image
:Release Notes:
In small images which don't include any webos components this causes
do_write_oss_pkg_info task to fail.

:Detailed Notes:
e.g. meta-updater/recipes-core/images/initramfs-ostree-image.bb fails with:
ERROR: initramfs-ostree-image-1.0-r0 do_write_oss_pkg_info: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:do_write_oss_pkg_info(d)
     0003:
File: '/data002/jenkins/gecko/clean-engineering-webos/meta-lg-webos/meta-webos/classes/webos_oss_pkg_info.bbclass', lineno: 24, function: do_write_oss_pkg_info
     0020:    oss_filename = d.getVar("OSS_FILENAME")
     0021:    manifest     = os.path.join(os.path.join(d.getVar("OSS_DEPLOY_DIR"), "%s-%s" % (imagename, machine)), "license.manifest")
     0022:
     0023:    if os.path.isfile(manifest):
 *** 0024:        with open(os.path.join(d.getVar("DEPLOY_DIR_IMAGE"), imagename+'-'+oss_filename), "w") as output:
     0025:            """ Extract recipe names from license manifest """
     0026:            tmp = []
     0027:            with open(manifest) as input:
     0028:                for line in input:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/data002/jenkins/gecko/clean-engineering-webos/BUILD/deploy/images/raspberrypi3/initramfs-ostree-image-oss-pkg-info.yaml'

ERROR: Logfile of failure stored in: /data002/jenkins/gecko/clean-engineering-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/initramfs-ostree-image/1.0-r0/temp/log.do_write_oss_pkg_info.11525
NOTE: recipe initramfs-ostree-image-1.0-r0: task do_write_oss_pkg_info: Failed

:Testing Performed:
Build tested.

:QA Notes:
None.

:Issues Addressed:
[PLAT-111903] Create GPVB with Yocto 3.1 dunfell

Change-Id: I4a345de8c833a46642382377b2ac0210a79a24ee