webos: systemd-boot: switch SECURITY_STACK_PROTECTOR back to strong from all
:Release Notes:
-fstack-protector-all was added globally in:
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/426367
webos: webos.inc: Enable security setting with -fstack-protector-all
[WRQ-31843] CCC: webos.inc: Enable security setting with
            -fstack-protector-all
[WRQ-26796] Patch for security vulnerabilities
but systemd-boot fails to build since then.

:Detailed Notes:
Works around:
http://gecko.lge.com:8000/Errors/Details/922859

Checking if "linker supports -static-pie" : links: NO
git/src/boot/efi/meson.build:231:8: ERROR: Problem encountered: Linker does not support -static-pie.

from the meson-log.txt:

Command line: `x86_64-webos-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-all -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot /OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/build/meson-private/tmphnazhkuk/testfile.c -o /OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/build/meson-private/tmphnazhkuk/output.exe -O2 -g -fcanon-prefix-map -fmacro-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/git=/usr/src/debug/systemd-boot/256 -fdebug-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/git=/usr/src/debug/systemd-boot/256 -fmacro-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/build=/usr/src/debug/systemd-boot/256 -fdebug-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/build=/usr/src/debug/systemd-boot/256 -fdebug-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot= -fmacro-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot= -fdebug-prefix-map=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot-native= -pipe -D_FILE_OFFSET_BITS=64 -O0 -std=gnu11 -nostdlib -Wl,--fatal-warnings -static-pie -fuse-ld=bfd --sysroot=/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now -fuse-ld=bfd` -> 1
stderr:
/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/14.2.0/ld.bfd: /tmp/ccZ7aif2.o: in function `a':
/usr/src/debug/systemd-boot/256/meson-private/tmphnazhkuk/testfile.c:1:(.text+0x28): undefined reference to `__stack_chk_fail'
/OE/lge/build/webos/styhead/BUILD/work/qemux86_64-webos-linux/systemd-boot/256/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/14.2.0/ld.bfd: /tmp/ccZ7aif2.o: in function `_start':
/usr/src/debug/systemd-boot/256/meson-private/tmphnazhkuk/testfile.c:1:(.text+0x5b): undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status                                                                                                                                                                                                    -----------                                                                                                                                                                                                                                   Checking if "linker supports -static-pie" : links: NO                                                                                                                                                                                                                                                                                                                                                                                                                                       ../git/src/boot/efi/meson.build:235:8: ERROR: Problem encountered: Linker does not support -static-pie.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: ec7c16733e7db36cff430ab009d8a475d7853d89
Cherry-picked-from-branch: