webos: webos.inc: disable return-type Werror for rust-llvm
:Release Notes:
Introduced with the rust upgrade to 1.74.1

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/755893

FAILED: lib/ExecutionEngine/JITLink/CMakeFiles/LLVMJITLink.dir/aarch32.cpp.o
ccache TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ITOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/build/lib/ExecutionEngine/JITLink -ITOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm/lib/ExecutionEngine/JITLink -ITOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/build/include -ITOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm/include -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot  -O2 -pipe  -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm=/usr/src/debug/rust-llvm/1.74.1  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm=/usr/src/debug/rust-llvm/1.74.1  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/build=/usr/src/debug/rust-llvm/1.74.1  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/build=/usr/src/debug/rust-llvm/1.74.1  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/recipe-sysroot-native=  -fvisibility-inlines-hidden  -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT lib/ExecutionEngine/JITLink/CMakeFiles/LLVMJITLink.dir/aarch32.cpp.o -MF lib/ExecutionEngine/JITLink/CMakeFiles/LLVMJITLink.dir/aarch32.cpp.o.d -o lib/ExecutionEngine/JITLink/CMakeFiles/LLVMJITLink.dir/aarch32.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp
TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp: In function 'bool llvm::jitlink::aarch32::writeRegister(WritableThumbRelocation&, HalfWords)':
TOPDIR/BUILD/work/qemux86_64-webos-linux/rust-llvm/1.74.1/rustc-1.74.1-src/src/llvm-project/llvm/lib/ExecutionEngine/JITLink/aarch32.cpp:182:1: error: no return statement in function returning non-void [-Werror=return-type]
  182 | }
      | ^
cc1plus: some warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I51bdc2bb25b92b07eb8796887d3bc6c1f863a0a2