qt3d: fix build with gcc-13
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/598007

TOPDIR/BUILD/work/qemux86_64-webos-linux/qt3d/6.5.0-r0/git/src/3rdparty/assimp/src/code/AssetLib/FBX/FBXBinaryTokenizer.cpp: In function 'void Assimp::FBX::TokenizeBinary(TokenList&, const char*, size_t)':
TOPDIR/BUILD/work/qemux86_64-webos-linux/qt3d/6.5.0-r0/git/src/3rdparty/assimp/src/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:475:61: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
  475 |         if (!is64bits && (length > std::numeric_limits<std::uint32_t>::max())) {
      |                                                             ^~~~~~~~
      |                                                             wint_t
TOPDIR/BUILD/work/qemux86_64-webos-linux/qt3d/6.5.0-r0/git/src/3rdparty/assimp/src/code/AssetLib/FBX/FBXBinaryTokenizer.cpp:475:69: error: template argument 1 is invalid
  475 |         if (!is64bits && (length > std::numeric_limits<std::uint32_t>::max())) {
      |                                                                     ^

Submitted in:
https://codereview.qt-project.org/c/yocto/meta-qt6/+/477944

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I3943413ff987452c1c0e367dabf7b9271da463d5