webos: webos.inc: disable return-type Werror for python3-fastnumbers
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/749006

src/cpp/parser.cpp: In member function 'virtual NumberFlags CharacterParser::get_number_type() const':
src/cpp/parser.cpp:463:1: error: control reaches end of non-void function [-Werror=return-type]
  463 | }
      | ^
cc1plus: some warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: 8025a083693fadf875065baa8676f22e542079de
Cherry-picked-from-branch: