webos: googletest-clang: rename to match googletest recipe name from meta-oe
:Release Notes:
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_git.bb to _1.13.0.bb.

:Detailed Notes:
Fixes parsing error:

  Parsing recipes...
  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang.bb:5:
  Could not include required file recipes-test/googletest/googletest_git.bb

after:
https://git.openembedded.org/meta-openembedded/commit/?id=46266e59ff36b38f46a67573528cee658960c764

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I1c8fb2de921320a98317de300c03f663e53a9a79