webos: webos.inc: disable return-type Werror for cppgenerate
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/926532

FAILED: CMakeFiles/objlib.dir/cppgenerate/printer.cpp.o
ccache cppgenerate/0.3/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/recipe-sysroot   -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables  --sysroot=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/git=/usr/src/debug/cppgenerate/0.3  -fdebug-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/git=/usr/src/debug/cppgenerate/0.3  -fmacro-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/build=/usr/src/debug/cppgenerate/0.3  -fdebug-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/build=/usr/src/debug/cppgenerate/0.3  -fdebug-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -std=gnu++11 -fPIC -MD -MT CMakeFiles/objlib.dir/cppgenerate/printer.cpp.o -MF CMakeFiles/objlib.dir/cppgenerate/printer.cpp.o.d -o CMakeFiles/objlib.dir/cppgenerate/printer.cpp.o -c TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/git/cppgenerate/printer.cpp
TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/git/cppgenerate/printer.cpp: In member function 'cppgenerate::Printer& cppgenerate::Printer::print()':
TOPDIR/BUILD/work/mach-webos-linux/cppgenerate/0.3/git/cppgenerate/printer.cpp:47:1: error: no return statement in function returning non-void [-Werror=return-type]
   47 | }
      | ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I9cf906d550247c578f79613fa891f35126c7a853