audiod=r31 (move /media/internal/systemsounds to /usr/share/systemsounds)
:Release Notes:
/media directory isn't handled by OTA and should be empty
as new empty-dirs QA checks.

:Detailed Notes:
Fixes:
NOTE: Running task 1613 of 1615 (/jenkins/mjansa/build/webos/kirkstone/meta-lg-webos/meta-webos/recipes-multimedia/audiod/audiod.bb:do_package_qa)
NOTE: recipe audiod-1.0.0-33-r30: task do_package_qa: Started
ERROR: audiod-1.0.0-33-r30 do_package_qa: QA Issue: audiod installs files in /media, but it is expected to be empty [empty-dirs]
ERROR: audiod-1.0.0-33-r30 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/webos/kirkstone/BUILD/work/qemux86-webos-linux/audiod/1.0.0-33-r30/temp/log.do_package_qa.1239246
NOTE: recipe audiod-1.0.0-33-r30: task do_package_qa: Failed
ERROR: Task (/jenkins/mjansa/build/webos/kirkstone/meta-lg-webos/meta-webos/recipes-multimedia/audiod/audiod.bb:do_package_qa) failed with exit code '1'

Also remove 2 unused patches which were removed from SRC_URI in:
commit 810fa42572ed7469e40737aaf301a82080c75bbe
Author: Velicheti Sita <velicheti.sita@lge.com>
Date:   Thu Aug 13 17:33:55 2020 +0000

    ose: audiod=19-r29 pulseaudio=22-r23

And remove /data and ${datadir}/alsa from FILES:${PN}, these don't
exist.

:Testing Performed:
Only build tested.

:QA Notes:
None.

:Issues Addressed:
[WRN-10062] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell
[PLAT-86306] [webOS OSE]: Error text "Invalid 'name' string parameter is displayed".

Change-Id: I2a977cecfbc56bec2250817c778ba585e1d684a4