webos: db8=r42 (test: Don't use long deprecated boost::filesystem::path::leaf)
:Release Notes:
It was replaced with filename() in 2008:
https://github.com/boostorg/filesystem/commit/fb65347b54bb9e027ef18b5ef80b2c509f90efe9
and is deprecated since then until finally removed in
boost 1.85.0:
https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/854668

In file included from ../git/test/performance/testsuite.cpp:18:
../git/test/performance/report.h: In function 'MojErr combineAvgNumbers2Report(const boost::filesystem::path&, const std::map<unsigned int, std::vector<boost::chrono::duration<long int, std::ratio<1, 1000000000> > > >&)':
../git/test/performance/report.h:40:34: error: 'class boost::filesystem::path' has no member named 'leaf'
   40 |     if (reportPath.parent_path().leaf().compare("1")) {
      |                                  ^~~~
../git/test/performance/report.h:52:50: warning

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-23876] CCC: db8=r42 (test: Don't use long deprecated boost::filesystem::path::leaf)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: I248d161951782b038d2e961d227d58207176de59
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/409759
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>