webos: gator-mod: gator_fs: Fix build with linux-6.10 and newer
:Release Notes:
In linux commit 12cd44023651666bd44baa36a5c999698890debb:
https://github.com/torvalds/linux/commit/12cd44023651666bd44baa36a5c999698890debb

i_atime and i_mtime were renamed to avoid direct access

with additional changes in:
https://lore.kernel.org/all/20240517-amtime-v1-1-7b804ca4be8f@kernel.org/

:Detailed Notes:
fixes:
http://gecko.lge.com:8000/Errors/Details/926806

../../../work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c: In function 'gatorfs_get_inode':
../../../work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c:48:16: error: 'struct inode' has no member named 'i_atime'; did you mean '__i_atime'?
   48 |         inode->i_atime = inode->i_mtime = current_time(inode);
      |                ^~~~~~~
      |                __i_atime
../../../work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c:48:33: error: 'struct inode' has no member named 'i_mtime'; did you mean '__i_mtime'?
   48 |         inode->i_atime = inode->i_mtime = current_time(inode);
      |                                 ^~~~~~~
      |                                 __i_mtime
../../../work/qemux86_64-webos-linux/gator-mod/6.7+git/git/driver/gator_fs.c:49:45: error: 'struct inode' has no member named 'i_mtime'; did you mean '__i_mtime'?
   49 |         inode_set_ctime_to_ts(inode, inode->i_mtime);
      |                                             ^~~~~~~
      |                                             __i_mtime

after linux-libc-headers were updated to v6.10 in:
https://git.openembedded.org/openembedded-core/commit/?id=3f852c2c958c80c652e902ab0532cefdc82e6549

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead
[WRP-32155] Fix gator to build with 6.10 kernel