ntopng, linuxconsole, influxdb, libpam, spirv-tools, rpm, android-tools, perf: fix build-deps QA issue with bash
:Release Notes:

:Detailed Notes:
rpm: bash dependency moved from PN to PN-build in:
https://git.openembedded.org/openembedded-core/commit/?id=0dea6cccc1c638078846e6eb8e48e8ef69c87618

android-tools runtime dependency on bash was moved from PN to BPN in:
  commit d36e527a406b241dbfaae2ce9e84fa4cfb27a81e
  Author: lumag <dbaryshkov@gmail.com>
  Date:   Mon Dec 21 02:27:00 2020 +0300

    android-tools: fix package split

causing:
ERROR: android-tools-5.1.1.r37-r0 do_package_qa: QA Issue: android-tools-fstools rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

bash added to another perf package for v5.12-rc5+ kernels:
https://git.openembedded.org/openembedded-core/commit/?h=hardknott&id=159cdb159ad0e9d3ed73cfc07f9acd5c0b608e7b
ERROR: QA Issue: perf-tests rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: Iebd488550b3f3a178bdd72026751ddd19cfacba1