webos-sota.inc: inherit image-artifact-names through IMAGE_CLASSES
:Release Notes:
Just like in buildhistory:
https://git.openembedded.org/openembedded-core/commit/?id=4fdda4d6bd434c240ec1dfdbfc6eb7e25e2db1f3

:Detailed Notes:
Fixes:
ERROR: ParseError at meta-webos/conf/distro/include/webos-sota.inc:11: Could not inherit file classes/image-artifact-names.bbclass

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale

Change-Id: I63182ec8a24abb8dcf8de20660789ff8d48ff521