webos: wayland: update 0003-Enhance-Wayland-debug-print.patch to apply on 1.23.1
:Release Notes:
Small conflict from upstream commit:
  commit c5c418de035913dc34f4842f7ba822b9ed165109
  Author: Sebastian Wick <sebastian.wick@redhat.com>
  Date:   Fri Jul 26 16:35:15 2024 +0200

    client: Handle proxies with no queue

    wl_proxy_get_queue can return NULL if the queue of the proxy was already
    destroyed with wl_event_queue_destroy. In this case, the queue also has
    no name anymore.

:Detailed Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=d929508fe77f1dc158cd5656721bcfbf105c07d7

Fixes:
http://gecko.lge.com:8000/Errors/Details/942989

ERROR: Applying patch '0003-Enhance-Wayland-debug-print.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wayland/1.23.1/wayland-1.23.1'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/wayland/1.23.1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0003-Enhance-Wayland-debug-print.patch
patching file meson.build
patching file meson_options.txt
patching file src/connection.c
patching file src/meson.build
patching file src/wayland-client.c
Hunk #1 FAILED at 931.
Hunk #2 succeeded at 1664 (offset 4 lines).
Hunk #3 succeeded at 1677 (offset 4 lines).
1 out of 3 hunks FAILED -- rejects in file src/wayland-client.c
patching file src/wayland-private.h
patching file src/wayland-server.c
patching file src/wayland-util.c
patching file src/wayland-version.h.in
Patch 0003-Enhance-Wayland-debug-print.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I831ab5329a700ee9e16e6ea4e9df0a03a2da9f0f