bluez5: update the patches to apply on 5.56 version from oe-core
:Release Notes:
Resolve conflicts mostly from these 2 upstream changes:
commit c4ef8f8d048a30304ba4cb1b83bfe39b55c13ba7
Author: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Date:   Wed Oct 28 14:53:36 2020 -0700

    core: Rename hcid.h to btd.h

    Since we use btd term for daemon APIs it makes sense to use it also
    for the header name instead of hcid.

commit 01d035d33886b13cd6dc361f994ce22ad47daf61
Author: Luiz Augusto von Dentz <luiz.von.dentz@intel.com>
Date:   Wed Oct 28 14:50:00 2020 -0700

    core: Rename main_opts to btd_opts

    Use btd_ prefix since this is a daemon API.

:Detailed Notes:
Fixes:
NOTE: --- Patch fuzz start ---
Applying patch 0011-Fix-volume-level-notification-not-appearing-after-12.patch
patching file profiles/audio/media.c
Hunk #1 succeeded at 1235 (offset 1 line).
patching file profiles/audio/transport.c
Hunk #1 succeeded at 656 (offset -13 lines).
Hunk #2 succeeded at 932 with fuzz 1 (offset -10 lines).

Now at patch 0011-Fix-volume-level-notification-not-appearing-after-12.patch

NOTE: Applying patch '0012-Support-enabling-avdtp-delayReport.patch' (meta-webosose/meta-webos/recipes-connectivity/bluez5/bluez5/0012-Support-enabling-avdtp-delayReport.patch)
ERROR: Command Error: 'quilt --quiltrc TOPDIR/BUILD/work/raspberrypi3-webos-linux-gnueabi/bluez5/5.56-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0012-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
Hunk #1 succeeded at 2194 (offset 34 lines).
patching file profiles/audio/a2dp.h
Hunk #1 succeeded at 77 (offset -13 lines).
patching file profiles/audio/avdtp.c
Hunk #1 succeeded at 469 (offset -9 lines).
patching file profiles/audio/avdtp.h
Hunk #1 succeeded at 306 (offset -8 lines).
patching file profiles/audio/media.c
Hunk #1 succeeded at 120 (offset -12 lines).
Hunk #2 succeeded at 813 (offset 1 line).
Hunk #3 succeeded at 2430 (offset 1 line).
patching file profiles/audio/media.h
Hunk #1 succeeded at 10 (offset -13 lines).
Hunk #2 succeeded at 23 (offset -13 lines).
patching file src/adapter.c
Hunk #1 FAILED at 78.
Hunk #2 succeeded at 224 (offset -19 lines).
Hunk #3 succeeded at 291 (offset -15 lines).
Hunk #4 succeeded at 497 with fuzz 2 (offset -15 lines).
Hunk #5 succeeded at 3194 with fuzz 2 (offset -17 lines).
Hunk #6 succeeded at 3539 (offset 22 lines).
Hunk #7 succeeded at 4867 (offset -6 lines).
Hunk #8 succeeded at 6319 (offset -6 lines).
Hunk #9 FAILED at 6366.
Hunk #10 succeeded at 6367 (offset -6 lines).
2 out of 10 hunks FAILED -- rejects in file src/adapter.c
patching file src/adapter.h
Hunk #1 succeeded at 25 (offset -8 lines).
Hunk #2 succeeded at 69 (offset -8 lines).
can't find file to patch at input line 302
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
  --------------------------
  |diff --git a/src/hcid.h b/src/hcid.h
  |index 3624ba6ea..8f77184ed 100644
  |--- a/src/hcid.h
  |+++ b/src/hcid.h
  --------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file src/main.c
Hunk #1 succeeded at 76 (offset -12 lines).
Hunk #2 succeeded at 709 with fuzz 2 (offset 74 lines).
patching file src/main.conf
Patch 0012-Support-enabling-avdtp-delayReport.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: Ifab5a609426b27fd06f7d47ed162769984c2315a