webos: blacklist xtf due to xen-tools
:Release Notes:
xtf was added in honister with:
http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/recipes-extended/xen/xtf_git.bb?id=5f51e806b8f56c30eb160c21d241c73268a4dedf

:Detailed Notes:
Depends on already blacklisted xen-tools, causing:
ERROR: Nothing RPROVIDES 'xen-tools-xl' (but /jenkins/mjansa/build/webos/honister/meta-virtualization/recipes-extended/xen/xtf_git.bb RDEPENDS on or otherwise requires it)
xen-tools RPROVIDES xen-tools-xl but was skipped: Recipe is blacklisted: Fails to build with gold, details in https://lists.yoctoproject.org/g/meta-virtualization/message/5202
xen-tools RPROVIDES xen-tools-xl but was skipped: Recipe is blacklisted: Fails to build with gold, details in https://lists.yoctoproject.org/g/meta-virtualization/message/5202
xen-tools RPROVIDES xen-tools-xl but was skipped: Recipe is blacklisted: Fails to build with gold, details in https://lists.yoctoproject.org/g/meta-virtualization/message/5202
NOTE: Runtime target 'xen-tools-xl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['xen-tools-xl']
ERROR: Required build target 'xtf' has no buildable providers.
Missing or unbuildable dependency chain was: ['xtf', 'xen-tools-xl']

But only in qemux86-64 builds, because xtf itself is restricted:
COMPATIBLE_HOST = '(x86_64.*).*-linux'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I248a9dfdf83250f922ed56686944310f4b3c704e