webos: sp-memusage=r8 (remove autotools inherit from recipes which don't use configure)
:Release Notes:
Missing configure is fatal after oe-core autotools change:
https://git.openembedded.org/openembedded-core/commit/?id=6d327a39befae44a88a812bdf4acde800dcee57b

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1138542

DEBUG: Executing shell function do_configure
ERROR: no configure script found at ./configure

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ib7594bc35affb1c125c433fd48ab0505a840e351