luna-init: chown the unpackaged font files
see https://github.com/webOS-ports/meta-webos-ports/commit/e7bc1a8a0d5d29c3c51d4563c4365776637338d7

* the files in the tarball are owned by roger:roger (1001:1001) and they
  should be owned by root:root in the target image
* it doesn't trigger host-user-contaminated QA issue as long as your
  build user doesn't have 1001 UID, but with OEOuthashBasic enabled by
  default in our master builds it fails like this:
  http://jenkins.nas-admin.org/job/LuneOS/view/unstable/job/luneos-unstable_qemux86-64/88/consoleFull

ERROR: luna-init-2.0.1-10+gitAUTOINC+9f0d2b6e31-r0 do_package: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_report_unihash(d)
     0003:
File: '/home/jenkins/workspace/luneos-unstable/webos-ports/openembedded-core/meta/classes/sstate.bbclass', lineno: 833, function: sstate_report_unihash
     0829:    report_unihash = getattr(bb.parse.siggen, 'report_unihash', None)
     0830:
     0831:    if report_unihash:
     0832:        ss = sstate_state_fromvars(d)
 *** 0833:        report_unihash(os.getcwd(), ss['task'], d)
     0834:}
     0835:
     0836:#
     0837:# Shell function to decompress and prepare a package for installation
File: '/home/jenkins/workspace/luneos-unstable/webos-ports/bitbake/lib/bb/siggen.py', lineno: 512, function: report_unihash
     0508:
     0509:            if "." in self.method:
     0510:                (module, method) = self.method.rsplit('.', 1)
     0511:                locs['method'] = getattr(importlib.import_module(module), method)
 *** 0512:                outhash = bb.utils.better_eval('method(path, sigfile, task, d)', locs)
     0513:            else:
     0514:                outhash = bb.utils.better_eval(self.method + '(path, sigfile, task, d)', locs)
     0515:
     0516:            try:
File: '/home/jenkins/workspace/luneos-unstable/webos-ports/bitbake/lib/bb/utils.py', lineno: 421, function: better_eval
     0417:    if extraglobals:
     0418:        ctx = copy.copy(ctx)
     0419:        for g in extraglobals:
     0420:            ctx[g] = extraglobals[g]
 *** 0421:    return eval(source, ctx, locals)
     0422:
     0423:@contextmanager
     0424:def fileslocked(files):
     0425:    """Context manager for locking and unlocking file locks."""
File: '<string>', lineno: 1, function: <module>
  File "<string>", line 1, in <module>

File: '/home/jenkins/workspace/luneos-unstable/webos-ports/openembedded-core/meta/lib/oe/sstatesig.py', lineno: 582, function: OEOuthashBasic
     0578:            process(root)
     0579:            for f in files:
     0580:                if f == 'fixmepath':
     0581:                    continue
 *** 0582:                process(os.path.join(root, f))
     0583:    finally:
     0584:        os.chdir(prev_dir)
     0585:
     0586:    return h.hexdigest()
File: '/home/jenkins/workspace/luneos-unstable/webos-ports/openembedded-core/meta/lib/oe/sstatesig.py', lineno: 544, function: process
     0540:                else:
     0541:                    add_perm(stat.S_IXOTH, 'x')
     0542:
     0543:                if include_owners:
 *** 0544:                    update_hash(" %10s" % pwd.getpwuid(s.st_uid).pw_name)
     0545:                    update_hash(" %10s" % grp.getgrgid(s.st_gid).gr_name)
     0546:
     0547:                update_hash(" ")
     0548:                if stat.S_ISBLK(s.st_mode) or stat.S_ISCHR(s.st_mode):
Exception: KeyError: 'getpwuid(): uid not found: 1001'

ERROR: Logfile of failure stored in: /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/all-webos-linux/luna-init/2.0.1-10+gitAUTOINC+9f0d2b6e31-r0/temp/log.do_package.20631

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>

[PLAT-48507] pseudo: random package_qa failures

Change-Id: I07337365593f1bd007ff968c7307f946c43ac721