webos: webos-virtualization: docker-moby=webosvirt5 (remove seccomp from REQUIRED_DISTRO_FEATURES)
:Release Notes:
We do disable the PACKAGECONFIG but as the commit says:
  Without these (and their associated packageconfig options) docker
  may build, but it won't run correctly.
we should double check that it works in runtime for us and consider
just enabling seccomp DISTRO_FEATURE if needed.

:Detailed Notes:
Fixes:
ERROR: Nothing RPROVIDES 'docker-moby' (but /home/worker/swarm_root/gecko/nano-ai_qcs8550-aihub/build/meta-lg-webos/meta-nano-ai/recipes-core/images/nano-ai-image.bb RDEPENDS on or otherwise requires it)
docker-moby was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'docker-moby' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-moby']
ERROR: Nothing RPROVIDES 'nano-ai-image'
No eligible RPROVIDERs exist for 'nano-ai-image'
NOTE: Runtime target 'nano-ai-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nano-ai-image']
ERROR: Nothing RPROVIDES 'docker' (but /home/worker/swarm_root/gecko/nano-ai_qcs8550-aihub/build/meta-virtualization/recipes-containers/docker-compose/docker-compose_git.bb RDEPENDS on or otherwise requires it)
docker-moby RPROVIDES docker but was skipped: missing required distro feature 'seccomp' (not in DISTRO_FEATURES)
NOTE: Runtime target 'docker' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker']
NOTE: Runtime target 'docker-compose' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-compose', 'docker']
ERROR: Nothing RPROVIDES 'docker-compose-dev' (but /home/worker/swarm_root/gecko/nano-ai_qcs8550-aihub/build/meta-virtualization/recipes-containers/docker-compose/docker-compose_git.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'docker-compose-dev'
NOTE: Runtime target 'docker-compose-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['docker-compose-dev']

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I8a9b6789a5d7d220fcddffa927584b06e85cf1fe