webos: webos-image=r5 (use UNPACKDIR)
:Release Notes:
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/850849

Exception: FileNotFoundError: [Errno 2] No such file or directory: 'webos-image/1.0/smack_labels_default'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-22934] CCC: webos-image=r5 (use UNPACKDIR)
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: Id771daf71398f738a5e95ee76927e41cce73a319
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/408921
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>