webos-raspberrypi: raspi-utils=webos1 (fix file-rdeps QA issue about /bin/bash)
:Release Notes:
Added in:
https://github.com/agherzan/meta-raspberrypi/commit/49a2d124890b96d28a590e52e6d0dd611c114f6b
and backported to scarthgap in:
https://github.com/agherzan/meta-raspberrypi/commit/1f2045321afd6ef20b457266ac3e97c8577eb1c4

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1261205
ERROR: QA Issue: raspi-utils-raspinfo rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-4944] [NANO] CCC: Yocto 5.0 Scarthgap

Change-Id: I22a6b0fbe5966e238207ec88cc0046eeb26c6578