webos: googletest-clang: rename to match googletest recipe name from meta-oe
:Release Notes:
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_1.15.2.bb to _1.16.0.bb.

:Detailed Notes:
Fixes parsing error:

  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang_1.15.2.bb:5:
  Could not include required file recipes-test/googletest/googletest_1.15.2.bb
  ERROR: Parsing halted due to errors, see error messages above

after:
https://git.openembedded.org/meta-openembedded/commit/?id=375549bdbfa130a07ed4daddb7f8fa9a89da4964

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Id4f42f615ea3b10b9635dc838f59e50269de64f3