gstreamer1.0-plugins-bad=webosrpi4 (update patches to apply on 1.16.3)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: gstreamer1.0-plugins-bad-1.16.3-r0 do_patch: Fuzz detected:

Applying patch 0001-waylandsink-remove-unsupported-subcompositor.patch
patching file ext/wayland/gstwaylandsink.c
patching file ext/wayland/gstwaylandsink.h
patching file ext/wayland/wldisplay.c
patching file ext/wayland/wldisplay.h
patching file ext/wayland/wlwindow.c
Hunk #13 succeeded at 437 with fuzz 2 (offset 4 lines).
Hunk #14 succeeded at 451 (offset 4 lines).
patching file ext/wayland/wlwindow.h

The context lines in the patches can be updated with devtool:

    devtool modify gstreamer1.0-plugins-bad
    devtool finish --force-patch-refresh gstreamer1.0-plugins-bad <layer_path>

Don't forget to review changes done by devtool!

ERROR: gstreamer1.0-plugins-bad-1.16.3-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

but the patches needed to be manually fixed after refreshing them
with devtool to remove area_surface_wrapper also from this new code
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/commit/24456ea8500b1d3f42ea4340f223311506e5127d
because 0001-waylandsink-remove-unsupported-subcompositor.patch removes
area_surface_wrapper and without this change do_compile fails with:
http://gecko.lge.com:8000/Errors/Details/72226

../gst-plugins-bad-1.16.3/ext/wayland/wlwindow.c:436:32: error: 'GstWlWindow' {aka 'struct _GstWlWindow'} has no member named 'area_surface_wrapper'; did you mean 'video_surface_wrapper'?
  436 |     wl_surface_attach (window->area_surface_wrapper, NULL, 0, 0);
      |                                ^~~~~~~~~~~~~~~~~~~~
      |                                video_surface_wrapper
../gst-plugins-bad-1.16.3/ext/wayland/wlwindow.c:437:32: error: 'GstWlWindow' {aka 'struct _GstWlWindow'} has no member named 'area_surface_wrapper'; did you mean 'video_surface_wrapper'?
  437 |     wl_surface_commit (window->area_surface_wrapper);
      |                                ^~~~~~~~~~~~~~~~~~~~
      |                                video_surface_wrapper