webos: com.webos.service.location=r6 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1155077

FAILED: CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot -DUSE_PMLOG_DECLARATION -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/include -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git=/usr/src/debug/com.webos.service.location/1.0.0-108  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git=/usr/src/debug/com.webos.service.location/1.0.0-108  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/build=/usr/src/debug/com.webos.service.location/1.0.0-108  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/build=/usr/src/debug/com.webos.service.location/1.0.0-108  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -Wall -std=c++11 -DNDEBUG   -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -pthread -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -pthread -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/json-c -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/libxml2 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include/loc-utils -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/recipe-sysroot/usr/include -MD -MT CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o -MF CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o.d -o CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/src/handler/lbs/geoservices/MapServicesImpl.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/include/MapServicesInterface.h:25,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/include/MapServicesImpl.h:28,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/src/handler/lbs/geoservices/MapServicesImpl.cpp:18:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/include/location_errors.h:25:9: error: 'uint32_t' does not name a type
   25 | typedef uint32_t LocationError_t;
      |         ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.location/1.0.0-108/git/include/location_errors.h:1:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
  +++ |+#include <cstdint>
    1 | // Copyright (c) 2020 LG Electronics, Inc.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2742] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ib001f59e4c32ea1c1b328df08901d8fbbddd91ab