meta-webos-smack: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-smack failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...ERROR: ParseError at /OE/meta-webosose/meta-webos-smack/recipes-webos/com.webos.app.test.smack.native/com.webos.app.test.smack.native.bb:10: Could not inherit file classes/webos_enhanced_submissions.bbclass

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-smack failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
ERROR: No recipes in default available for:
  /OE/meta-webosose/meta-webos-smack/recipes-security/smack/smack_%.bbappend
Parsing of 2780 .bb files complete (0 cached, 2780 parsed). 4273 targets, 292 skipped, 0 masked, 0 errors.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I39b294caaf9577ec50321e0d73d78d1532dd3619