webos: webos-connman-adapter=r20 (use gnu17 even with gcc-15)
:Release Notes:
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/1139929
webos-connman-adapter/1.1.0-242.apollo.18/git/src/main.c:47:5: error: conflicting types for 'initialize_wifi_ls2_calls'; have 'int(void)'
webos-connman-adapter/1.1.0-242.apollo.18/git/src/main.c:86:13: error: too many arguments to function 'initialize_wifi_ls2_calls'; expected 0, have 2

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ib32def01f6b2b51bc5f524a4920cc908e7690565