webos: googletest-clang: rename to match googletest recipe name from meta-oe
:Release Notes:
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_1.14.0.bb to _1.15.2.bb.

:Detailed Notes:
Fixes parsing error:

  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang_1.14.0.bb:5:
  Could not include required file recipes-test/googletest/googletest_1.14.0.bb
  ERROR: Parsing halted due to errors, see error messages above

after:
https://git.openembedded.org/meta-openembedded/commit/?id=64ecdaaa85ac4394cdd6a763a6752501be5af31e

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead