pmtrace: disable, not compatible with lttng-ust-2.13
:Release Notes:
I've tried to enable old API, but unfortunatelly this isn't enough
and it still fails, so disable WEBOS_LTTNG_ENABLED until it's resolved,
which removes most of the build failures except pmtrace where we
disable libmemtracker which is failing.

:Detailed Notes:
http://gecko.lge.com/Errors/Details/241643
FAILED: src/libmemtracker/liblttng-ust-mtrace-malloc/CMakeFiles/lttng-ust-mtrace-malloc.dir/lttng-ust-mtrace-malloc.c.o
TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-gcc -Dlttng_ust_mtrace_malloc_EXPORTS -ITOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/include -ITOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-malloc -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11=/usr/src/debug/pmtrace/1.0.0-9-r11                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11=/usr/src/debug/pmtrace/1.0.0-9-r11                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot-native=    -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot -DNDEBUG -fPIC -Wl,--no-as-needed -MD -MT src/libmemtracker/liblttng-ust-mtrace-malloc/CMakeFiles/lttng-ust-mtrace-malloc.dir/lttng-ust-mtrace-malloc.c.o -MF src/libmemtracker/liblttng-ust-mtrace-malloc/CMakeFiles/lttng-ust-mtrace-malloc.dir/lttng-ust-mtrace-malloc.c.o.d -o src/libmemtracker/liblttng-ust-mtrace-malloc/CMakeFiles/lttng-ust-mtrace-malloc.dir/lttng-ust-mtrace-malloc.c.o -c TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-malloc/lttng-ust-mtrace-malloc.c
In file included from TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/recipe-sysroot/usr/include/lttng/tracepoint-event.h:69,
                 from TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-malloc/ust_mtrace_malloc.h:98,
                 from TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-malloc/lttng-ust-mtrace-malloc.c:29:
TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-malloc/./ust_mtrace_malloc.h:41:9: error: static assertion failed: "Non-integer type `bt` not supported as element of LTTNG_UST_FIELD_ARRAY or LTTNG_UST_FIELD_SEQUENCE"
   41 |         ctf_sequence(void *, bt, bt, size_t, depth)
      |         ^~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-new/./ust_mtrace_new.h: In function 'void lttng_ust__event_probe__mtrace_new___new(void*, size_t, void*, void*, void*, size_t)':
TOPDIR/BUILD/work/qemux86-webos-linux/pmtrace/1.0.0-9-r11/git/src/libmemtracker/liblttng-ust-mtrace-new/./ust_mtrace_new.h:26:1: error: expected primary-expression before ')' token
   26 | TRACEPOINT_EVENT(mtrace_new, new,
      | ^~~~~~~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I4eb608918cb6a40e6a222e53bb6b6b8151076288