webos: bluez5=webos37 (refresh patches to apply on 5.72 version)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/766738

ERROR: Applying patch '0010-Fix-volume-property-not-able-to-set.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.72/bluez-5.72'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.72/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0010-Fix-volume-property-not-able-to-set.patch
patching file profiles/audio/transport.c
Hunk #1 FAILED at 1176.
1 out of 1 hunk FAILED -- rejects in file profiles/audio/transport.c
Patch 0010-Fix-volume-property-not-able-to-set.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: 63393015ecf1f6bf7f9e11601380a2261b011238
Cherry-picked-from-branch: