meta-webos-iot: define VIRTUAL-RUNTIME_nyx_modules_providers before use
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
WARNING: No bb files in default matched BBFILE_PATTERN_meta-qt5-compat '^/OE/meta-webosose/meta-qt5-compat/'
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for initscripts (initscripts, webos-initscripts)
Consider defining a PREFERRED_PROVIDER entry to match initscripts
ERROR: Nothing RPROVIDES '${VIRTUAL-RUNTIME_nyx_modules_providers}' (but /OE/meta-webosose/meta-webos-iot/recipes-core/packagegroups/packagegroup-webos-iot-core.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${VIRTUAL-RUNTIME_nyx_modules_providers}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${VIRTUAL-RUNTIME_nyx_modules_providers}']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-webos-iot-core', '${VIRTUAL-RUNTIME_nyx_modules_providers}']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I1986f5674cb886d685d6d8b76fc8e5bf2e0be191