webos: half: don't use S = WORKDIR
:Release Notes:
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
it's fatal error since:
https://git.openembedded.org/openembedded-core/commit/?h=master&id=32cba1cc916ad530c5e6630a927e74ca6f06289b

:Detailed Notes:
Fixes:
Parsing recipes...
ERROR: meta-webos/recipes-upstreamable/half/half_2.1.0.bb: Using S = ${WORKDIR} is no longer supported
ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I39d61322f16ad54898b90a92e925314084c5bf19