webos: bluez5 (refresh patches to apply on 5.66 version)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:80/Builds/Details/1243568
ERROR: Applying patch '0012-Support-enabling-avdtp-delayReport.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.66-r0/bluez-5.66'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/bluez5/5.66-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0012-Support-enabling-avdtp-delayReport.patch
patching file profiles/audio/a2dp.c
patching file profiles/audio/a2dp.h
patching file profiles/audio/avdtp.c
patching file profiles/audio/avdtp.h
patching file profiles/audio/media.c
Hunk #1 succeeded at 128 (offset 8 lines).
Hunk #2 succeeded at 1327 with fuzz 2 (offset 507 lines).
Hunk #3 succeeded at 3066 (offset 623 lines).
patching file profiles/audio/media.h
patching file src/adapter.c
Hunk #2 succeeded at 281 (offset 9 lines).
Hunk #3 succeeded at 361 (offset 27 lines).
Hunk #4 succeeded at 568 (offset 27 lines).
Hunk #5 succeeded at 3487 (offset 164 lines).
Hunk #6 FAILED at 3749.
Hunk #7 succeeded at 5292 (offset 166 lines).
Hunk #8 succeeded at 6826 (offset 169 lines).
Hunk #9 succeeded at 6871 (offset 173 lines).
Hunk #10 FAILED at 6706.
2 out of 10 hunks FAILED -- rejects in file src/adapter.c
patching file src/adapter.h
patching file src/btd.h
patching file src/main.c
patching file src/main.conf
Patch 0012-Support-enabling-avdtp-delayReport.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14883] Create GPVB with Yocto 4.2 Mickedore