rpi: u-boot: update patch to apply on v2023.04
:Release Notes:
Upgraded in oe-core with;
https://git.openembedded.org/openembedded-core/commit/?id=57003af06d50fbbb33b94a4b10ea6c77fa294027

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/580975

ERROR: Applying patch '0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/1_2023.04-r0/git'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/1_2023.04-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch
patching file configs/rpi_3_32b_defconfig
Hunk #1 FAILED at 13.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_32b_defconfig
patching file configs/rpi_3_b_plus_defconfig
Hunk #1 FAILED at 12.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_b_plus_defconfig
patching file configs/rpi_3_defconfig
Hunk #1 FAILED at 12.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_defconfig
patching file configs/rpi_4_32b_defconfig
Hunk #1 FAILED at 10.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_32b_defconfig
patching file configs/rpi_4_defconfig
Hunk #1 FAILED at 10.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_defconfig
patching file configs/rpi_arm64_defconfig
Hunk #1 FAILED at 10.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_arm64_defconfig
patching file include/configs/rpi.h
Patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I2697e23b373390bcc6eb45fd3f8540f0c4d3dc1b