meta-webos-iot: respect VIRTUAL-RUNTIME_org.ocf.webossample
:Release Notes:
Like
meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb
does.

:Detailed Notes:
NOTE: Multiple providers are available for initscripts (initscripts, webos-initscripts)
Consider defining a PREFERRED_PROVIDER entry to match initscripts
ERROR: Nothing RPROVIDES 'org.ocf.webossample.occlientbasicops' (but /OE/meta-webosose/meta-webos-iot/recipes-core/packagegroups/packagegroup-webos-iot.bb RDEPENDS on or otherwise requires it)
org.ocf.webossample.occlientbasicops was skipped: incompatible with machine qemux86-64 (not in COMPATIBLE_MACHINE)
NOTE: Runtime target 'org.ocf.webossample.occlientbasicops' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['org.ocf.webossample.occlientbasicops']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-webos-iot', 'org.ocf.webossample.occlientbasicops']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I746910d787ca2755ea919b894deafa5d33fc9d01