tensorflow-lite: try to upgrade flatbuffers to v2.0.6
:Release Notes:
flatbuffers in meta-oe were updated from 2.0.0 to 2.0.6 in:
https://git.openembedded.org/meta-openembedded/commit/?id=0b32f0000ce6b93306db7f0d2d72c36b5270e2ab
and now components which are using system flatbuffers
(e.g. armnn, tflite-auto-delegation, aiservice) are
failing to build because old tensorflow-lite v2.6.2 is
using flatbuffers v1.2.0 and the
recipe-sysroot/usr/include/tensorflow/lite/schema/schema_generated.h
from tensorflow-lite is not compatible with newer flatbuffers.

:Detailed Notes:
armnn: http://gecko.lge.com:8000/Errors/Details/432726
tflite-auto-delegation: http://gecko.lge.com:8000/Errors/Details/432725
aiservice: http://gecko.lge.com:8000/Errors/Details/432724

in all cases it's caused by errors like:
recipe-sysroot/usr/include/tensorflow/lite/schema/schema_generated.h:3310:32: error: no matching function for call to 'tflite::QuantizationParameters::VerifyField<uint8_t>(flatbuffers::Verifier&, tflite::QuantizationParameters::FlatBuffersVTableOffset) const'
 3310 |            VerifyField<uint8_t>(verifier, VT_DETAILS_TYPE) &&
      |            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

backport the updates to 2.0.5 from:
https://github.com/tensorflow/tensorflow/commit/625a4045bc0728c0f3d1b63e05749201f8b401dd
and 2.0.6 from:
https://github.com/tensorflow/tensorflow/commit/bf0901b663e87f081c7a317fe1ac705ab1a2df8b

armnn needs to be patched as well for flatbuffers-v2.0.6:
https://github.com/ARM-software/armnn/issues/644
https://github.com/ARM-software/armnn/commit/f74937eca3eece3ccd439933306ac0f32415390e

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale

Change-Id: Ibd0eecd1586969bf6c8dd201d602919f9a4d2487