media-codec-interface=r9 (fix build with gcc-13)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529559

FAILED: src/CMakeFiles/media-codec-impl.dir/impl/v4l2/v4l2_video_decoder.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ -Dmedia_codec_impl_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot/usr/include/gstreamer-1.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot/usr/include/orc-0.4 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/build/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/. -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/./api -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/./base -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/./impl -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/./resource -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot/usr/include/media-resource-calculator -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git=/usr/src/debug/media-codec-interface/1.0.0-18-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git=/usr/src/debug/media-codec-interface/1.0.0-18-r8  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/build=/usr/src/debug/media-codec-interface/1.0.0-18-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/build=/usr/src/debug/media-codec-interface/1.0.0-18-r8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++14 -DNDEBUG -fPIC -MD -MT src/CMakeFiles/media-codec-impl.dir/impl/v4l2/v4l2_video_decoder.cpp.o -MF src/CMakeFiles/media-codec-impl.dir/impl/v4l2/v4l2_video_decoder.cpp.o.d -o src/CMakeFiles/media-codec-impl.dir/impl/v4l2/v4l2_video_decoder.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/impl/v4l2/v4l2_video_decoder.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/impl/v4l2/v4l2_video_decoder.h:12,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/impl/v4l2/v4l2_video_decoder.cpp:5:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/media-codec-interface/1.0.0-18-r8/git/src/./base/thread.h:47:15: error: field 'thread_name_' has incomplete type 'std::string' {aka 'std::__cxx11::basic_string<char>'}
   47 |   std::string thread_name_;
      |               ^~~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes:Release Notes: