webos: com.webos.service.tts: fix build with grpc-1.66.1
:Release Notes:
Update 0001-google-add-gpr-lib-to-TTS_ENGINE-call.patch

:Detailed Notes:
Add absl_log_internal_check_op as well to fix
http://gecko.lge.com:8000/Errors/Details/948399

FAILED: tts-service
: && TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -DUSE_PMLOG_DECLARATION -DUSE_PMLOG -std=c++17 -Wall -DNDEBUG  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -Wl,-z,relro,-z,now -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/git=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/build=/usr/src/debug/com.webos.service.tts/1.0.0-31  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native=  -Wl,-z,relro,-z,now   -rdynamic CMakeFiles/tts-service.dir/src/core/AudioEngineFactory.cpp.o CMakeFiles/tts-service.dir/src/core/EngineHandler.cpp.o CMakeFiles/tts-service.dir/src/core/RequestHandler.cpp.o CMakeFiles/tts-service.dir/src/core/RequestQueue.cpp.o CMakeFiles/tts-service.dir/src/core/StatusHandler.cpp.o CMakeFiles/tts-service.dir/src/core/TTSEngineFactory.cpp.o CMakeFiles/tts-service.dir/src/core/TTSManager.cpp.o CMakeFiles/tts-service.dir/src/core/TTSRequest.cpp.o CMakeFiles/tts-service.dir/src/luna/TTSLunaService.cpp.o CMakeFiles/tts-service.dir/src/tts_main.cpp.o CMakeFiles/tts-service.dir/src/utils/ParameterListManager.cpp.o CMakeFiles/tts-service.dir/src/utils/TTSConfig.cpp.o CMakeFiles/tts-service.dir/src/utils/TTSErrors.cpp.o CMakeFiles/tts-service.dir/src/utils/TTSLog.cpp.o CMakeFiles/tts-service.dir/src/utils/TTSParameters.cpp.o CMakeFiles/tts-service.dir/src/utils/TTSUtils.cpp.o CMakeFiles/tts-service.dir/src/engines/tts/google/GoogleTTSEngine.cpp.o CMakeFiles/tts-service.dir/src/engines/tts/google/GoogleTTSEngineFactory.cpp.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/annotations.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/annotations.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/auth.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/auth.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/backend.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/backend.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/billing.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/billing.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/config_change.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/config_change.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/consumer.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/consumer.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/context.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/context.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/control.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/control.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/distribution.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/distribution.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/documentation.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/documentation.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/endpoint.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/endpoint.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/experimental/authorization_config.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/experimental/authorization_config.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/experimental/experimental.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/experimental/experimental.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/http.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/http.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/httpbody.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/httpbody.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/label.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/label.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/launch_stage.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/launch_stage.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/log.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/log.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/logging.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/logging.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/metric.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/metric.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/monitored_resource.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/monitored_resource.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/monitoring.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/monitoring.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/quota.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/quota.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/service.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/service.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/source_info.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/source_info.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/system_parameter.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/system_parameter.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/usage.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/api/usage.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/cloud/texttospeech/v1/cloud_tts.grpc.pb.cc.o CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/cloud/texttospeech/v1/cloud_tts.pb.cc.o CMakeFiles/tts-service.dir/src/engines/audio/pulse/PulseAudioEngine.cpp.o CMakeFiles/tts-service.dir/src/engines/audio/pulse/PulseAudioEngineFactory.cpp.o -o tts-service  -LTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib  -lluna-service2++  -lluna-service2  -lPmLogLib  -lpbnjson_cpp  -lpbnjson_c  -LTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib  -lglib-2.0  -LTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib  -lPmLogLib  -lgpr  -labsl_city  -labsl_cord  -labsl_cordz_info  -labsl_cordz_functions  -labsl_log_internal_message  -labsl_log_internal_nullguard  -labsl_synchronization  -labsl_hash  -lgrpc  -lgrpc++  -lprotobuf  -LTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib  -lpulse-mainloop-glib  -pthread  -lglib-2.0  -lpulse-simple  -pthread  -lpulse  -pthread  -LTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib  -lpbnjson_cpp  -lpbnjson_c  -lpthread  -Wl,--no-as-needed  -lPmLogLib  -lglib-2.0  -lgpr  -labsl_city  -labsl_cord  -labsl_cordz_info  -labsl_cordz_functions  -labsl_log_internal_message  -labsl_log_internal_nullguard  -labsl_synchronization  -labsl_hash  -lgrpc  -lgrpc++  -lprotobuf  -lpulse-mainloop-glib  -lpulse-simple  -lpulse  -lpthread && :
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/14.2.0/ld: CMakeFiles/tts-service.dirTOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/include/google/cloud/texttospeech/v1/cloud_tts.grpc.pb.cc.o: undefined reference to symbol '_ZN4absl12lts_2024011612log_internal17MakeCheckOpStringIPKvS4_EEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'
TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot-native/usr/bin/x86_64-webos-linux/../../libexec/x86_64-webos-linux/gcc/x86_64-webos-linux/14.2.0/ld: TOPDIR/BUILD/work/qemux86_64-webos-linux/com.webos.service.tts/1.0.0-31/recipe-sysroot/usr/lib/libabsl_log_internal_check_op.so.2401.0.0: error adding symbols: DSO missing from command line

after grpc was upgraded to 1.66.1 in:
https://git.openembedded.org/meta-openembedded/commit/?id=cfd5a02d269e2b0103bd9ca03574481134ff3b76

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I9585495c69b556988b16347f74b2743e97c2246f