webos: libpng=webos1 (fix file-rdeps QA issue about /bin/bash)
:Release Notes:
Added in:
https://git.openembedded.org/openembedded-core/commit/?id=8dca5305c950e6a06b3f344ffdbbb7386d802095
and backported to scarthgap in:
https://git.openembedded.org/openembedded-core/commit/?h=scarthgap&id=1b52b7ebe5f8fb490088622181cdb95e6b7f5a29

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1219896
ERROR: QA Issue: libpng-ptest rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-4702] [NANO] CCC: Yocto 5.0 Scarthgap

Change-Id: I211314f27bb53d711a1735665905f805a7e6fb10
Reviewed-on: http://kairos-git.lge.com/c/webos-pro/meta-lg-webos/+/474280
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Youngseok Jeong <youngseok1.jeong@lge.com>