webos-backports-4.1: npm.bbclass: backport fix to remove /usr/lib/node symlink
:Release Notes:
Backport this change from langdale:
  commit 9896a7e3a9bdbc6bf3bb67b5f5d5c8ae8225ed0f
  Author: Zolt??????n B??????sz??????rm??????nyi <zboszor@gmail.com>
  Date:   Fri May 13 17:30:30 2022 +0200

    npm.bbclass: Don't create /usr/lib/node symlink

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/783217

NOTE: Direct dependencies are ['TOPDIR/meta-lg-webos/meta-webos/recipes-webos/enact-dev/enact-dev-native.bb:do_populate_sysroot', 'TOPDIR/meta-lg-webos/meta-webos/recipes-webos/enact-dev/jsdoc-to-ts-native.bb:do_populate_sysroot', 'virtual:native:TOPDIR/meta-oe/meta-oe/recipes-devtools/nodejs/nodejs_16.20.2.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/ccache/ccache_4.6.bb:do_populate_sysroot', 'virtual:native:TOPDIR/oe-core/meta/recipes-devtools/pseudo/pseudo_git.bb:do_populate_sysroot']
ERROR: The file /usr/lib/node is installed by both jsdoc-to-ts-native and enact-dev-native, aborting

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-12001] CCC: webos-backports-4.1: npm.bbclass: backport fix to remove /usr/lib/node symlink
[WRO-5448] Nodejs recipes should use bitbake fetcher to fetch
           sources in do_fetch instead of npm fetching them in
           do_install

Change-Id: I40c8cff4e51d82f3579e767cd167edcc611b9c96