webos: wolfssl=webos2 (fix file-rdeps QA issue fix about /bin/bash)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: wolfssl-5.7.2-r0 do_package_qa: QA Issue: wolfssl-ptest rdepends on bash, but it isn't a build dependency, missing bash in DEPENDS or PACKAGECONFIG? [build-deps]
added in meta-oe with:
06a5e82a83 Wolfssl: add ptest
which was backported to scartgap with:
7bc1db1659 Wolfssl: add ptest

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2742] [NANO] CCC: Yocto 5.0 Scarthgap

Change-Id: If591b1bcbc36986806aad058976f9b6023555c9b