webos: userland=webosrpi7 (use gnu17 even with gcc-15)
:Release Notes:
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/1155076
http://gecko.lge.com:8000/Errors/Details/1140017
userland/20230419/git/interface/vmcs_host/vc_vchi_gpuserv.c:204:13: error: too many arguments to function 'c->func'; expected 0, have 1
userland/20230419/git/interface/vchiq_arm/vchiq_lib.c:534:1: error: conflicting types for 'vchiq_bulk_receive_handle'; have 'VCHIQ_STATUS_T(VCHIQ_SERVICE_HANDLE_T,  VCHI_MEM_HANDLE_T,  void *, int,  void *, VCHIQ_BULK_MODE_T,  int (*)(void))' {aka 'VCHIQ_STATUS_T(unsigned int,  int,  void *, int,  void *, VCHIQ_BULK_MODE_T,  int (*)(void))'}

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2742] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I25725b5a264a1f4b952c13d98d0fb71cf975879a