busybox: update the patches to apply on 1.34.0 version from oe-core
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: busybox-1.34.0-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/busybox/1.34.0-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0003-libedit-check-for-null-before-passing-cmdedit_prompt.patch
patching file libbb/lineedit.c
Hunk #1 FAILED at 460.
1 out of 1 hunk FAILED -- rejects in file libbb/lineedit.c
Patch 0003-libedit-check-for-null-before-passing-cmdedit_prompt.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I1edd9164533a34c208e6535fb18122a1153bcdbf