*-clang: skip these recipes when WEBRUNTIME_TOOLCHAIN isn't set to -clang
:Release Notes:
Make the recipes mutualy exclusive, so that bitbake will remove the
unselected one before building the selected one.

:Detailed Notes:
This only skips the *-clang versions for now, because I think both versions
are pulled into the build.

Fixes:
ERROR: Nothing PROVIDES 'clang' (but
  meta-webos/recipes-devtools/jsoncpp/jsoncpp-clang_1.9.5.bb,
  meta-webos/recipes-test/googletest/googletest-clang.bb,
  meta-webos/recipes-webos/media-resource-calculator/media-resource-calculator-clang.bb,
  meta-webos/recipes-multimedia/g-media-pipeline/g-media-pipeline-clang.bb,
  meta-webos/recipes-multimedia/media-codec-interface/media-codec-interface-clang.bb,
  meta-webos/recipes-webos/libpbnjson/libpbnjson-clang.bb,
  meta-webos/recipes-webos/umediaserver/umediaserver-clang.bb
  DEPENDS on or otherwise requires it).
Close matches:
  slang
  wam-clang

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-12446] CCC: Various build fixes
[WRP-12469] Bitbake world issues 2023-04-01

Change-Id: I0000a2e3c1226354745331011d398d7adfb5ca79