linux-yocto=webos10 (enable profiling)
:Release Notes:
Otherwise gator fails to build.

:Detailed Notes:
Nobody will probably use ARM gator on x86, but there is no COMPATIBLE_MACHINE
restriction in gator recipe and currently it fails for qemux86 with:
work/qemux86-webos-linux/gator/6.7+gitAUTOINC+3ff46fedd4-r2/git/driver/gator_main.c:54:2: error: #error gator requires the kernel to have CONFIG_PROFILING defined
   54 | #error gator requires the kernel to have CONFIG_PROFILING defined
      |  ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-121806] CCC: various build issues

Change-Id: I05bcc892a596198f3233707ced6cad8e463c904c