webos: qtwayland-webos=r21
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtwayland' (but
  meta-webos/recipes-webos/qtwayland-webos/qtwayland-webos.bb
  DEPENDS on or otherwise requires it)
qtwayland was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'qtwayland-native' (but
  meta-webos/recipes-webos/qtwayland-webos/qtwayland-webos.bb
  DEPENDS on or otherwise requires it)
qtwayland-native was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: qtwayland-webos=r21
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Change-Id: Ia5552fed100e7cae0b850ae9dc316158bd150c86
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/403348
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>