webruntime: don't enable neva-webrtc
* fix e.g. qemuarm builds which started to fail now when neva-webrtc has a dependency on unavailable g-camera-pipeline:

  ERROR: Nothing PROVIDES 'g-camera-pipeline' (but meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_79.bb DEPENDS on or otherwise requires it)
  g-camera-pipeline was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)

* most of the builds were removing neva-webrtc from PACKAGECONFIG, so just don't enable
  it in the default value and enable it only for raspberrypi4 builds

* using _remove operator is bad practise when there is better way to set it (because it's
  impossible to undo _remove from another bbappend)

Change-Id: Ic085d7b456c2ab888b425e844a218aa97c9dc84f
Signed-off-by: Martin Jansa <martin.jansa@lge.com>