webos: solana* sugar: delete the recipes
:Release Notes:
We don't care webOS legacy anymore.

:Detailed Notes:
soana* and sugar are broken again after rust upgrade to 1.86.0 in:

https://git.openembedded.org/openembedded-core/commit/?id=c064ef18343a956aea397d36d2e7665d6c8afd7d

as shown in http://gecko.lge.com:8000/Builds/Details/3089840

error: older versions of the `wasm-bindgen` crate are incompatible with current versions of Rust; please update to `wasm-bindgen` v0.2.88

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: Ic05504351586615809405ad54acf17a4ca63c265