webos: com.webos.service.storageaccess=r11 (fix build with curl-8.13.0 and newer)
:Release Notes:
CURLUSESSL_TRY is no longer curl_usessl since:
https://github.com/curl/curl/commit/7b0240c07799c28dc84272f9e38e1092ce4cc498

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1211993

FAILED: CMakeFiles/storageaccess.dir/src/utils/CurlClient.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot -DNOT_SUPPORT_GFLAGS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/libxml2 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/gupnp-1.6 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/gssdp-1.6 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/libsoup-3.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/libmount -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot/usr/include/blkid -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/providers/gdrive/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/providers/internal -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/providers/upnp -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/providers/network -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot  -O2 -g  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git=/usr/src/debug/com.webos.service.storageaccess/1.0.0-30  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/build=/usr/src/debug/com.webos.service.storageaccess/1.0.0-30  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot=  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -pthread -DUSE_PMLOG_DECLARATION -DUSE_PMLOG -std=c++17 -Wall -DNDEBUG -MD -MT CMakeFiles/storageaccess.dir/src/utils/CurlClient.cpp.o -MF CMakeFiles/storageaccess.dir/src/utils/CurlClient.cpp.o.d -o CMakeFiles/storageaccess.dir/src/utils/CurlClient.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.cpp:1:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.h: In constructor 'OC::Bridging::CurlClient::CurlClient()':
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.h:53:32: error: invalid conversion from 'long int' to 'curl_usessl' [-fpermissive]
   53 |                     m_useSsl = CURLUSESSL_TRY;
      |                                ^~~~~~~~~~~~~~
      |                                |
      |                                long int
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.h: In constructor 'OC::Bridging::CurlClient::CurlClient(CurlMethod, const std::string&)':
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.storageaccess/1.0.0-30/git/src/utils/CurlClient.h:67:32: error: invalid conversion from 'long int' to 'curl_usessl' [-fpermissive]
   67 |                     m_useSsl = CURLUSESSL_TRY;
      |                                ^~~~~~~~~~~~~~
      |                                |
      |                                long int

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I12115ce185a43a51db72f2f0f399ac1537adc838