webruntime=r50.* (inherit pkgconfig)
:Release Notes:
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through pkgconfig.bbclass as
we're using it here.

:Detailed Notes:
Fixes:
  BUILD_TARGETS are webos:weboswebruntime app_shell
  ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
      pkgresult = exec_script(pkg_config_script, args, "value")
                  ^----------
  Current dir: /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/build/Release/
  Command: python /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/git/src/build/config/linux/pkg-config.py -s /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/recipe-sysroot -a x86 --system_libdir lib xkbcommon
  Returned 1.
  stderr:

  Traceback (most recent call last):
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/git/src/build/config/linux/pkg-config.py", line 253, in <module>
      sys.exit(main())
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/git/src/build/config/linux/pkg-config.py", line 148, in main
      prefix = GetPkgConfigPrefixToStrip(options, args)
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/git/src/build/config/linux/pkg-config.py", line 87, in GetPkgConfigPrefixToStrip
      "--variable=prefix"] + args, env=os.environ).decode('utf-8')
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 216, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 394, in __init__
      errread, errwrite)
    File "/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/webruntime/87.0.4280.88-8-r49.2/recipe-sysroot-native/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
      raise child_exception
  OSError: [Errno 2] No such file or directory

  See //ui/events/ozone/layout/BUILD.gn:12:3: whence it was called.
    pkg_config("xkbcommon") {
    ^------------------------
  See //ui/events/BUILD.gn:74:15: which caused the file to be included.
      deps += [ "//ui/events/ozone/layout" ]
                ^-------------------------

:Testing Performed:
Only build tested.

:QA Notes:
No change to the image.

:Issues Addressed:
[WRN-7597] CCC: Various build fixes

Change-Id: Ie4f1000feedb6ea029b80285585bde53fa2d3a7a