webos: leveldb-tl: disable building tests, fail with gcc-15
:Release Notes:
Didn't fail with gcc-15.0.1 but does with gcc-15.1.0.

:Detailed Notes:
Avoid:
http://gecko.lge.com:8000/Errors/Details/1181161

leveldb-tl/0.1.6/git/test/util.hpp: In function 'constexpr bool hostIsNetwork()':
leveldb-tl/0.1.6/git/test/util.hpp:42:11: error: 'reinterpret_cast' is not a constant expression [-Werror=invalid-constexpr]
   42 | { return *reinterpret_cast<const short*>("\x01\x02") == 0x0102; }
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: Icfbeef47353168c828825838bc0c8b55b109d09a