webos: webos.inc: clang lldb: disable return-type Werror
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1186664
work-shared/llvm-project-source-20.1.3-r0/llvm-project-20.1.3.src/lldb/source/DataFormatters/TypeSummary.cpp: In member function 'virtual std::string lldb_private::TypeSummaryImpl::GetSummaryKindName()':
work-shared/llvm-project-source-20.1.3-r0/llvm-project-20.1.3.src/lldb/source/DataFormatters/TypeSummary.cpp:62:1: error: control reaches end of non-void function [-Werror=return-type]
   62 | }
      | ^
cc1plus: some warnings being treated as errors

http://gecko.lge.com:8000/Errors/Details/1252508
FAILED: [code=1] source/DataFormatters/CMakeFiles/lldbDataFormatters.dir/TypeSummary.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot -DHAVE_ROUND -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/build/source/DataFormatters -ITOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/source/DataFormatters -ITOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/build/include -ITOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/tools/clang/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/build/../clang/include -ITOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/source -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/build/source -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot/usr/include/libxml2 -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot  -O2 -g  -ffile-prefix-map=TOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src=/usr/src/debug/lldb/20.1.7  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/build=/usr/src/debug/lldb/20.1.7  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot=  -ffile-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/lldb/20.1.7/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -Wimplicit-fallthrough -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-stringop-truncation -std=c++17 -MD -MT source/DataFormatters/CMakeFiles/lldbDataFormatters.dir/TypeSummary.cpp.o -MF source/DataFormatters/CMakeFiles/lldbDataFormatters.dir/TypeSummary.cpp.o.d -o source/DataFormatters/CMakeFiles/lldbDataFormatters.dir/TypeSummary.cpp.o -c TOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/source/DataFormatters/TypeSummary.cpp
TOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/source/DataFormatters/TypeSummary.cpp: In member function 'virtual std::string lldb_private::TypeSummaryImpl::GetSummaryKindName()':
TOPDIR/BUILD/work-shared/llvm-project-source-20.1.7-r0/sources/llvm-project-20.1.7.src/lldb/source/DataFormatters/TypeSummary.cpp:62:1: error: control reaches end of non-void function [-Werror=return-type]
   62 | }
      | ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I7709d5df463f026ec04906a38136ecfe614d50e0