webos: luna-surfacemanager=r62
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'qtwayland' (but
  meta-webos/recipes-webos/luna-surfacemanager/luna-surfacemanager.bb
  DEPENDS on or otherwise requires it)
qtwayland was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
ERROR: Nothing PROVIDES 'qtwayland-native' (but
  meta-webos/recipes-webos/luna-surfacemanager/luna-surfacemanager.bb
  DEPENDS on or otherwise requires it)
qtwayland-native was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: luna-surfacemanager=r62
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Change-Id: Iaf5874da88eb548a62edeadc4ba4b466f966a184
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/404110
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>