webos: nodejs: update patch to apply on v18.12.1 version
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: nodejs-native-18.12.1-r0 do_patch: QA Issue: Fuzz detected:

Applying patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch
patching file src/inspector_io.cc
patching file src/node_internals.h
Hunk #1 succeeded at 91 with fuzz 2.
patching file src/util.cc

The context lines in the patches can be updated with devtool:

    devtool modify nodejs-native
    devtool finish --force-patch-refresh nodejs-native <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I3139c301ae2d4491457c134404dc1111dd7ed004