WIP: webos: com.webos.service.mediarecorder: remove build-media-recorder and test-apps PACKAGECONFIGs to work around build failure with gcc-15
:Release Notes:
It might be false-positive as reported in:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115048
but it's not yet confirmed.

:Detailed Notes:
Avoids triggering:
FAILED: CMakeFiles/com.webos.service.mediarecorder.dir/src/media_recorder.cpp.o
/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot  -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/glib-2.0 -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/include -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/ls_connector -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/error_manager -I/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/process -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git=/usr/src/debug/com.webos.service.mediarecorder/1.0.0-17  -fdebug-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git=/usr/src/debug/com.webos.service.mediarecorder/1.0.0-17  -fmacro-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/build=/usr/src/debug/com.webos.service.mediarecorder/1.0.0-17  -fdebug-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/build=/usr/src/debug/com.webos.service.mediarecorder/1.0.0-17  -fdebug-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot=  -fmacro-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot=  -fdebug-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot-native=  -fmacro-prefix-map=/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -Wall -funwind-tables -Wall -rdynamic -lrt -Werror -Wno-psabi -DUSE_PMLOG_DECLARATION -std=c++14 -g -std=gnu++17 -MD -MT CMakeFiles/com.webos.service.mediarecorder.dir/src/media_recorder.cpp.o -MF CMakeFiles/com.webos.service.mediarecorder.dir/src/media_recorder.cpp.o.d -o CMakeFiles/com.webos.service.mediarecorder.dir/src/media_recorder.cpp.o -c /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp
In file included from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/x86_64-webos-linux/bits/c++allocator.h:33,
                 from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/allocator.h:46,
                 from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/string:45,
                 from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/error_manager/error.h:3,
                 from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.h:20,
                 from /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp:18:
In member function 'void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = audio_support_list_t]',
    inlined from 'static void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = audio_support_list_t]' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/alloc_traits.h:649:23,
    inlined from 'void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(pointer, std::size_t) [with _Tp = audio_support_list_t; _Alloc = std::allocator<audio_support_list_t>]' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/stl_vector.h:393:19,
    inlined from 'void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(pointer, std::size_t) [with _Tp = audio_support_list_t; _Alloc = std::allocator<audio_support_list_t>]' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/stl_vector.h:389:7,
    inlined from 'std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = audio_support_list_t; _Alloc = std::allocator<audio_support_list_t>]' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/stl_vector.h:372:15,
    inlined from 'std::vector<_Tp, _Alloc>::~vector() [with _Tp = audio_support_list_t; _Alloc = std::allocator<audio_support_list_t>]' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/stl_vector.h:806:7,
    inlined from 'ErrorCode isSupportedAudioFormat(const std::string&, unsigned int, unsigned int, unsigned int)' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp:196:1,
    inlined from 'ErrorCode MediaRecorder::setAudioFormat(std::string&, uint32_t, uint32_t, uint32_t)' at /OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp:594:31:
/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/recipe-sysroot/usr/include/c++/15.0.1/bits/new_allocator.h:172:66: error: 'void operator delete(void*, std::size_t)' called on pointer '__result' with nonzero offset 104 [-Werror=free-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                                                  ^
/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp: In member function 'ErrorCode MediaRecorder::setAudioFormat(std::string&, uint32_t, uint32_t, uint32_t)':
/OE/lge/build/webosose/whinlatter/BUILD/work/qemux86_64-webos-linux/com.webos.service.mediarecorder/1.0.0-17/git/src/media_recorder.cpp:578:11: note: declared here
  578 | ErrorCode MediaRecorder::setAudioFormat(std::string &audioCodec, uint32_t sampleRate,
      |           ^~~~~~~~~~~~~

which happens only when building for qemux86-64, raspberrypi4-64
builds don't fail surprisingly even when building the same
media_recorder.cpp and preprocessor output looks almost identical.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I1ca133d67b96c0870a471ffbd06aeed25df05f1b