webos: busybox: disable CONFIG_TC, CONFIG_FEATURE_TC_INGRESS
:Release Notes:
It doesn't build with newer linux-libc-headers v6.9 from:
https://git.openembedded.org/openembedded-core/commit/?id=78dac2c1f037921c58ccc6efcbf540a92d0fcfcf
as reported in:
http://lists.busybox.net/pipermail/busybox-cvs/2024-January/041752.html
http://lists.busybox.net/pipermail/busybox-cvs/2024-January/041751.html

poky-tiny had similar issue:
https://git.yoctoproject.org/poky/commit/?id=8fc598580e0222c022fedec79233b6de2320b0c4

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/855100

which shows that both got enabled with our old defconfig:

Value of CONFIG_TC is redefined by fragment .config.app.nosuid:
Previous value: # CONFIG_TC is not set
New value: CONFIG_TC=y

Value of CONFIG_FEATURE_TC_INGRESS is redefined by fragment .config.app.nosuid:
Previous value: # CONFIG_FEATURE_TC_INGRESS is not set
New value: CONFIG_FEATURE_TC_INGRESS=y

networking/tc.c: In function 'cbq_print_opt':
networking/tc.c:236:27: error: 'TCA_CBQ_MAX' undeclared (first use in this function); did you mean 'TCA_CBS_MAX'?
  236 |         struct rtattr *tb[TCA_CBQ_MAX+1];
      |                           ^~~~~~~~~~~
      |                           TCA_CBS_MAX

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: I8c02edd6054725a51ccaee02a001dbd3241f2100