webos: nodejs: update patch to apply on v18.18.2 version
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/705485

ERROR: Applying patch '0001-Use-human-readable-process-name-for-chrome-inspector.patch' on target directory 'TOPDIR/BUILD/work/x86_64-linux/nodejs-native/20.5.1/node-v20.5.1'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/x86_64-linux/nodejs-native/20.5.1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch
patching file src/inspector_io.cc
patching file src/node_internals.h
Hunk #1 succeeded at 94 (offset 3 lines).
patching file src/util.cc
Hunk #1 FAILED at 164.
1 out of 1 hunk FAILED -- rejects in file src/util.cc
Patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch does not apply (enforce with -f)

And the same with v18.18.2 version backported to mickledore in:
https://git.openembedded.org/meta-openembedded/commit/?h=mickledore&id=5529546039e77320668396a24ff22cf7d9568b6a

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I7aae02973f5bcd8efbb4e5b07d7da20d429a655c