webruntime=r38.*-webosrpi7 (don't enable neva-webrtc)
:Release Notes:
Fix e.g. qemuarm builds which started to fail now when neva-webrtc has a dependency on unavailable g-camera-pipeline:

ERROR: Nothing PROVIDES 'g-camera-pipeline' (but meta-webos/recipes-webos/chromium/webruntime_79.bb DEPENDS on or otherwise requires it)
g-camera-pipeline was skipped: incompatible with machine qemuarm (not in COMPATIBLE_MACHINE)

:Detailed Notes:
Most of the builds were removing neva-webrtc from PACKAGECONFIG, so just don't enable
it in the default value and enable it only for raspberrypi4 builds

Using _remove operator is bad practise when there is better way to set it (because it's
impossible to undo _remove from another bbappend)

:Testing Performed:

:QA Notes:

:Issues Addressed:
[PLAT-121667] CCC: webruntime cleanup

Change-Id: Ia3ce04b8a711f64a833470dc4b57112854ba54ba