localization-tool-native=r8 (don't install /opt/js-loctool/node_modules/node-expat/build/node_gyp_bins)
:Release Notes:
node-gyp v9.1.0 now installs python3 symlink in
node_modules/node-expat/build/node_gyp_bins pointing to absolute
path of python3 in PATH (${HOSTTOOLS}/python3). It was introduced in:
https://github.com/nodejs/node-gyp/commit/b9ddcd5bbd93b05b03674836b6ebdae2c2e74c8c
but if such python3 script ends in target package it will point
to wrong python3 and even for native it might point to wrong RSS
when python3native.bbclass is used, for now just delete the directory
to avoid this error.

:Detailed Notes:
Fixes:
ERROR: localization-tool-native-1.7.0-r7 do_populate_sysroot: sstate found an absolute path symlink /data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/work/x86_64-linux/localization-tool-native/1.7.0-r7/sysroot-destdir/data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/work/x86_64-linux/localization-tool-native/1.7.0-r7/recipe-sysroot-native/opt/js-loctool/node_modules/node-expat/build/node_gyp_bins/python3 pointing at /data001/jenkins/gecko/webos_raspberrypi4-64/build/BUILD/hosttools/python3. Please replace this with a relative link.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14883] Create GPVB with Yocto 4.2 Mickedore

Change-Id: Iaa11229dd16d5db3b6cd0c05a8c71dac6ff61c6a