webos: qtshadertools=webos1 (glslang: fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:
FAILED: src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvBuilder.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot -DGLSLANG_OSINCLUDE_UNIX -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_QASCONST -DQT_NO_QEXCHANGE -DQT_NO_QSNPRINTF -DQT_USE_QSTRINGBUILDER -D_GLIBCXX_ASSERTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/build/src/glslang/BundledGlslang_Spirv_autogen/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git/src/glslang/../3rdparty/glslang -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot/usr/lib/mkspecs/linux-g++ -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git=/usr/src/debug/qtshadertools/6.8.1  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/build=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/build=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native=   -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/image=  -pipe -fvisibility-inlines-hidden  -DNDEBUG -O2 -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -w -fno-exceptions -U_FORTIFY_SOURCE -Wsuggest-override -D_FORTIFY_SOURCE=3 -ftrivial-auto-var-init=pattern -fstack-protector-strong -fstack-clash-protection -MD -MT src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvBuilder.cpp.o -MF src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvBuilder.cpp.o.d -o src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvBuilder.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.cpp
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.cpp:48:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.h:247:30: error: 'uint32_t' has not been declared
  247 |     Id makeDebugLexicalBlock(uint32_t line);
      |                              ^~~~~~~~
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.h:64:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   63 | #include <stack>
  +++ |+#include <cstdint>
   64 | #include <unordered_map>

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2742] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I6c57a8d7ffc6c0b5517d7274180e1a854de685b1