webos: tensorflow-lite=r11 (fix build with gcc-14)
:Release Notes:
Backport fix from newer flatbuffers.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/821692

ccache TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot -DEIGEN_MPL2_ONLY -DNOMINMAX=1 -Dtensorflow_lite_EXPORTS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/git/tensorflow/lite/schema -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/git -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/vulkan_headers/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/opengl_headers/api -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/egl_headers/api -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/eigen -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/neon2sse -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/farmhash/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/flatbuffers/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/gemmlowp/public -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/gemmlowp -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build/ruy -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/git=/usr/src/debug/tensorflow-lite/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/git=/usr/src/debug/tensorflow-lite/2.9.3  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build=/usr/src/debug/tensorflow-lite/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/build=/usr/src/debug/tensorflow-lite/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/recipe-sysroot-native=  -fvisibility-inlines-hidden -DNDEBUG -std=c++17 -fPIC -DGPU_DELEGATE_ONLY_GL -DEGL_NO_X11 -DTFLITE_BUILD_WITH_XNNPACK_DELEGATE -pthread -MD -MT CMakeFiles/tensorflow-lite.dir/delegates/gpu/common/task/tensor_linear_desc.cc.o -MF CMakeFiles/tensorflow-lite.dir/delegates/gpu/common/task/tensor_linear_desc.cc.o.d -o CMakeFiles/tensorflow-lite.dir/delegates/gpu/common/task/tensor_linear_desc.cc.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/tensorflow-lite/2.9.3/git/tensorflow/lite/delegates/gpu/common/task/tensor_linear_desc.cc
In file included from flatbuffers/include/flatbuffers/array.h:21,
                 from flatbuffers/include/flatbuffers/flatbuffers.h:22,
                 from ../git/tensorflow/lite/delegates/gpu/common/task/serialization_base_generated.h:21,
                 from ../git/tensorflow/lite/delegates/gpu/common/task/gpu_object_desc.h:28,
                 from ../git/tensorflow/lite/delegates/gpu/common/task/tensor_linear_desc.h:24,
                 from ../git/tensorflow/lite/delegates/gpu/common/task/tensor_linear_desc.cc:16:
flatbuffers/include/flatbuffers/stl_emulation.h: In member function 'constexpr flatbuffers::span<T, Extent>& flatbuffers::span<T, Extent>::operator=(const flatbuffers::span<T, Extent>&)':
flatbuffers/include/flatbuffers/stl_emulation.h:386:12: error: assignment of read-only member 'flatbuffers::span<T, Extent>::count_'
  386 |     count_ = other.count_;
      |     ~~~~~~~^~~~~~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Cherry-picked-from-commit: 81cb58725e01ae6494b29103b57956d8fb74ea6d
Cherry-picked-from-branch: