webos: webos.inc: use IMAGE_VERSION_SUFFIX_DATETIME in IMAGE_VERSION_SUFFIX
:Release Notes:

:Detailed Notes:
The DATETIME is no longer excluded from vardeps of whole IMAGE_VERSION_SUFFIX causing:

ERROR: When reparsing /OE/lge/build/webos/scarthgap/meta-lg-webos/meta-webos/recipes-core/images/webos-image.bb:do_image_wic, the basehash value changed from 4cffe5685f99f4db24cd6641d0af114300ea9936c94f1299ec277f37d9bf8562 to 84b79be0874def2dcb7523a5eee7a07e30b952d39895f9f6529504720c97ab13. The metadata is not deterministic and this needs to be fixed.
ERROR: The following commands may help:
ERROR: $ bitbake webos-image -cdo_image_wic -Snone
ERROR: Then:
ERROR: $ bitbake webos-image -cdo_image_wic -Sprintdiff