meta-webos-virtualization: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-virtualization failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
ERROR: No recipes in default available for:
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/containerd/containerd-docker_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/containerd/containerd-opencontainers_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/docker/docker-ce_%.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/docker/docker-moby.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/lxc/lxc_%.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/runc/runc-docker_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/runc/runc-opencontainers_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-containers/singularity/singularity_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-core/packagegroups/packagegroup-webos-extended.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-devtools/go/go-systemd_%.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-extended/hyperstart/hyperstart_git.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-extended/libvirt/libvirt_%.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-extended/xen/xen-tools_%.bbappend
  /OE/meta-webosose/meta-webos-virtualization/recipes-networking/openvswitch/openvswitch_git.bbappend
Parsing of 2613 .bb files complete (0 cached, 2613 parsed). 4086 targets, 277 skipped, 0 masked, 0 errors.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

INFO: test_parse (common.CommonCheckLayer)
INFO:  ... ERROR
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-virtualization failed to parse.
Command: bitbake -p
Output:
WARNING: You have included the meta-virtualization layer, but 'virtualization' has not been enabled in your DISTRO_FEATURES. Some bbappend files may not take effect. See the meta-virtualization README for details on enabling virtualization support.
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
ERROR: No recipes in default available for:
  /OE/meta-webosose/meta-webos-virtualization/recipes-core/packagegroups/packagegroup-webos-extended.bbappend
Parsing of 2874 .bb files complete (0 cached, 2874 parsed). 4423 targets, 303 skipped, 0 masked, 0 errors.

Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I03dbad449dbfe0d3c185408974f75a8e87b93ad0