webos: qtshadertools: glslang: fix build with gcc-15
* fixes:
FAILED: src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvPostProcess.cpp.o
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot -DGLSLANG_OSINCLUDE_UNIX -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_QASCONST -DQT_NO_QEXCHANGE -DQT_NO_QSNPRINTF -DQT_USE_QSTRINGBUILDER -D_GLIBCXX_ASSERTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/build/src/glslang/BundledGlslang_Spirv_autogen/include -I/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/glslang/../3rdparty/glslang -I/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot/usr/lib/mkspecs/linux-g++ -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git=/usr/src/debug/qtshadertools/6.8.1  -fmacro-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/build=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/build=/usr/src/debug/qtshadertools/6.8.1  -fdebug-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot=  -fmacro-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot=  -fdebug-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native=  -fmacro-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/recipe-sysroot-native=   -fmacro-prefix-map=/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/image=  -pipe -fvisibility-inlines-hidden -DNDEBUG -O2 -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -w -fno-exceptions -U_FORTIFY_SOURCE -Wsuggest-override -fcf-protection=full -D_FORTIFY_SOURCE=3 -ftrivial-auto-var-init=pattern -fstack-protector-strong -fstack-clash-protection -MD -MT src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvPostProcess.cpp.o -MF src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvPostProcess.cpp.o.d -o src/glslang/CMakeFiles/BundledGlslang_Spirv.dir/__/3rdparty/glslang/SPIRV/SpvPostProcess.cpp.o -c /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvPostProcess.cpp
In file included from /OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvPostProcess.cpp:46:
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.h:247:30: error: 'uint32_t' has not been declared
  247 |     Id makeDebugLexicalBlock(uint32_t line);
      |                              ^~~~~~~~
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.h:64:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   63 | #include <stack>
  +++ |+#include <cstdint>
   64 | #include <unordered_map>
/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/qtshadertools/6.8.1/git/src/3rdparty/glslang/SPIRV/SpvBuilder.h:444:28: error: 'uint32_t' has not been declared
  444 |     void enterLexicalBlock(uint32_t line);
      |                            ^~~~~~~~