webos: systemd=webos22 (update patches to apply on v253.7)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/650050

NOTE: --- Patch fuzz start ---
Applying patch 0001-systemd-oomd-depend-on-swap-on.patch
patching file units/systemd-oomd.service.in
Hunk #1 succeeded at 13 with fuzz 1 (offset 1 line).

Now at patch 0001-systemd-oomd-depend-on-swap-on.patch

--- Patch fuzz end ---
NOTE: Applying patch '0002-Add-webos-interface.patch' (meta-lg-webos/meta-webos/recipes-core/systemd/systemd/0002-Add-webos-interface.patch)
NOTE: --- Patch fuzz start ---
Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
patching file src/oom/oomd-manager.c
Hunk #3 succeeded at 520 with fuzz 2.
patching file src/oom/oomd.c
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in
Hunk #1 succeeded at 28 (offset 1 line).

Now at patch 0002-Add-webos-interface.patch

--- Patch fuzz end ---
NOTE: Applying patch '0003-systemd-oomd-modify-oomd.conf.patch' (meta-lg-webos/meta-webos/recipes-core/systemd/systemd/0003-systemd-oomd-modify-oomd.conf.patch)
NOTE: Applying patch '0004-oomd-to-some.patch' (meta-lg-webos/meta-webos/recipes-core/systemd/systemd/0004-oomd-to-some.patch)
NOTE: Applying patch '0005-oomd-change-duration.patch' (meta-lg-webos/meta-webos/recipes-core/systemd/systemd/0005-oomd-change-duration.patch)
NOTE: Applying patch '0006-Change-ownership-of-media-directory-to-support-non-r.patch' (meta-lg-webos/meta-webos/recipes-core/systemd/systemd/0006-Change-ownership-of-media-directory-to-support-non-r.patch)
DEBUG: Python function patch_do_patch finished
DEBUG: Python function do_patch finished
DEBUG: Executing python function do_qa_patch
ERROR: QA Issue: Fuzz detected:

Applying patch 0001-systemd-oomd-depend-on-swap-on.patch
patching file units/systemd-oomd.service.in
Hunk #1 succeeded at 13 with fuzz 1 (offset 1 line).

Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
patching file src/oom/oomd-manager.c
Hunk #3 succeeded at 520 with fuzz 2.
patching file src/oom/oomd.c
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in
Hunk #1 succeeded at 28 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify systemd
    devtool finish --force-patch-refresh systemd <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16198] CCC: Upgrade to Yocto 4.3 Nanbield
[WRR-2119] Create GPVB with Yocto 4.3 Nanbield

Cherry-picked-from-commit: 909ed77f6bc96117439be9080dd06c35b2678e69
Cherry-picked-from-branch: