umediaserver=r17 (Fix the patches)
:Release Notes:
Fix the changes from:
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/315473

:Detailed Notes:
No wrong patch file is being applied for wrong build causing
it to fail again when using newer boost:

qemux86-webos-linux/umediaserver/1.0.0-24.gav.19-r17/git/src/resource_manager/AppLifeManager.cpp:79:20: error: 'find_if' was not declared in this scope; did you mean 'boost::mpl::find_if'?
   79 |         auto itr = find_if(_apps.begin(), _apps.end(), func);
      |                    ^~~~~~~
      |                    boost::mpl::find_if

This should be really integrated in umediaserver repo, but
media team didn't have time to do that since Jun 2020 when this
patch file was added, because they are busy adding more and more
umediaserver forks instead :(.

:Testing Performed:
Only build tested.

:QA Notes:
No change to the image.

:Issues Addressed:
[WRN-7597] CCC: Various build fixes

Change-Id: I819e7a31d8089d53439b35a0bcf58b1b93aa4c49