nodejs: update patch to apply on new 16.18.1 version
:Release Notes:
Upgraded in:
https://git.openembedded.org/meta-openembedded/commit/?id=c4829fa338dae008c75cfffd4a712813a99c33c4

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/490007
ERROR: Applying patch '0001-Use-human-readable-process-name-for-chrome-inspector.patch' on target directory 'TOPDIR/BUILD/work/x86_64-linux/nodejs-native/16.18.1-r0/node-v16.18.1'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/x86_64-linux/nodejs-native/16.18.1-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch
patching file src/inspector_io.cc
Hunk #1 succeeded at 361 (offset -1 lines).
patching file src/node_internals.h
patching file src/util.cc
Hunk #1 FAILED at 164.
1 out of 1 hunk FAILED -- rejects in file src/util.cc
Patch 0001-Use-human-readable-process-name-for-chrome-inspector.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14883] Create GPVB with Yocto 4.2 Mickedore

Change-Id: I4253c1dfaabf4af5381ebfb3ae8dbf358187ae79