iotop: remove bbappend
:Release Notes:
The python implementation was replced with activelly maintained C port in:
https://github.com/openembedded/meta-openembedded/commit/b298118df9cc1b633df82f06c485d489429428f7
and the patch doesn't apply anymore

:Detailed Notes:
Fixes:
ERROR: iotop-1.20-r0 do_patch: Applying patch 'iotop_not_disappear_result_when_exited_thread.patch' on target directory '/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/iotop/1.20-r0/iotop-1.20'
CmdError('quilt --quiltrc /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/iotop/1.20-r0/recipe-sysroot-native/etc/quiltrc push', 0, "stdout: Applying patch iotop_not_disappear_result_when_exited_thread.patch
can't find file to patch at input line 15
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 118dc100098c768906f9bb7ee6706491f666c984 Mon Sep 17 00:00:00 2001
|From: Martin Jansa <martin.jansa@lge.com>
|Date: Sun, 26 Jan 2020 01:42:46 -0800
|Subject: [PATCH] don't let result disappear when thread exits
|
|Signed-off-by: Martin Jansa <martin.jansa@lge.com>
|---
| iotop/data.py | 35 ++++++++++++++++++++++++++++-------
| 1 file changed, 28 insertions(+), 7 deletions(-)
|
|diff --git a/iotop/data.py b/iotop/data.py
|index 3874974..864d28c 100644
|--- a/iotop/data.py
|+++ b/iotop/data.py
--------------------------
No file to patch.  Skipping patch.
8 out of 8 hunks ignored
Patch iotop_not_disappear_result_when_exited_thread.patch does not apply (enforce with -f)

stderr: ")
ERROR: Logfile of failure stored in: /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/iotop/1.20-r0/temp/log.do_patch.1938256

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: Id6afcb3d2ee175ff2cab9f34021ea2a55d011bb4