webos: com.webos.service.hfp=r10 (use python3native and depend on python3-packaging-native)
:Release Notes:
python3-packaging-native is used by gdbus-codegen. Fix it
similarly as gattlib in:
https://git.openembedded.org/meta-openembedded/commit/?id=8c5720df4a1f4ea0f72196029aae495fd58565b2

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/788245

Traceback (most recent call last):
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.hfp/1.0.0-34/recipe-sysroot-native/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.hfp/1.0.0-34/recipe-sysroot-native/usr/share/glib-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.hfp/1.0.0-34/recipe-sysroot-native/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.hfp/1.0.0-34/recipe-sysroot-native/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
CMake Error at CMakeLists.txt:73 (message):
  Error in generating code for ofono dbus interface using gdbus-codegen

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16199] CCC: Upgrade to Yocto 5.0 Scarthgap
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Cherry-picked-from-commit: 2409d57371c9defa8ad4192a3aa672718bbd9c05
Cherry-picked-from-branch: