com.webos.service.mediacontroller: temporarily disable branch check
* there is fetching issue in com.webos.service.mediacontroller:

WARNING: com.webos.service.mediacontroller-1.0.0-24-r3 do_fetch: Failed to fetch URL git://github.com/webosose/com.webos.service.mediacontroller;branch=master;protocol=https, attempting MIRRORS if available
ERROR: com.webos.service.mediacontroller-1.0.0-24-r3 do_fetch: Fetcher failure: Unable to find revision 363fbf2f0fbb2d0f3dc746e23a62bafb0acfee4d in branch master even from upstream

the tag submissions/24 is there, but not included in any branch:

mjansa@kangaroo-build:~/mjansa/com.webos.service.mediacontroller$ git branch -a --contains 363fbf2f0fbb2d0f3dc746e23a62bafb0acfee4d
mjansa@kangaroo-build:~/mjansa/com.webos.service.mediacontroller$ git sr 24
363fbf2f0fbb2d0f3dc746e23a62bafb0acfee4d refs/tags/submissions/24
9d7ef4747bc7d44ef427f4c200e254cf4921b63c refs/tags/submissions/24^{}

Last 2 commits from internal build are missing on github:

698de06 (HEAD -> master, gpro/master, gpro/HEAD) Merge remote-tracking branch 'origin/@develop'
9d7ef47 (tag: submissions/24, gpro/@develop) Fix play/pause/next/previous functionalities not working through connected BT device in rpi4-64 bit environment
5689ee1 (github/master) Merge remote-tracking branch 'origin/@develop'
eb13c76 (tag: submissions/23) Fix Position logs are not changed when enter key is pressed

Signed-off-by: Martin Jansa <martin.jansa@lge.com>