solana-crates.inc: refresh with checksums for duplicates
:Release Notes:
Some of these crates use different version, which is handled correctly by
the bbclass when multiple versions are used from the same Cargo.lock file,
but in this case there are cases where there is only version per Cargo.lock
(so it doesn't get the name parameter), but then different version in other
Cargo.lock file processed into the same .inc file (and the checksums overwrite
each other), see:
https://lists.openembedded.org/g/openembedded-core/message/179358

:Detailed Notes:
This is first batch of manually added ;name= params for:
arrayvec, async-stream, async-stream-impl, axum, base64ct, bitflags, bumpalo
but I'm giving up and will rather update the bbclass to do this, because
there are many more like this:

grep crate:// meta-webos/recipes-upstreamable/solana/solana-crates.inc  | sort -u | grep -v ';name=' | sed 's@/[^/]*$@@g' | uniq -c | sort | grep -v " 1 "
      2     crate://crates.io/autocfg
      2     crate://crates.io/byteorder
      2     crate://crates.io/bytes
      2     crate://crates.io/cfg-if
      2     crate://crates.io/clang-sys
      2     crate://crates.io/clap_derive
      2     crate://crates.io/core-foundation
      2     crate://crates.io/crc32fast
      2     crate://crates.io/crossbeam-utils
      2     crate://crates.io/derive_more
      2     crate://crates.io/ed25519
      2     crate://crates.io/either
      2     crate://crates.io/encoding_rs
      2     crate://crates.io/filetime
      2     crate://crates.io/fixedbitset
      2     crate://crates.io/goblin
      2     crate://crates.io/hash32
      2     crate://crates.io/hashbrown
      2     crate://crates.io/heck
      2     crate://crates.io/httparse
      2     crate://crates.io/humantime
      2     crate://crates.io/indexmap
      2     crate://crates.io/instant
      2     crate://crates.io/ipnet
      2     crate://crates.io/jobserver
      2     crate://crates.io/libc
      2     crate://crates.io/libm
      2     crate://crates.io/libz-sys
      2     crate://crates.io/log
      2     crate://crates.io/memchr
      2     crate://crates.io/minimal-lexical
      2     crate://crates.io/multimap
      2     crate://crates.io/native-tls
      2     crate://crates.io/nom
      2     crate://crates.io/ntapi
      2     crate://crates.io/num-derive
      2     crate://crates.io/num-integer
      2     crate://crates.io/num_threads
      2     crate://crates.io/openssl-probe
      2     crate://crates.io/os_str_bytes
      2     crate://crates.io/pin-project
      2     crate://crates.io/pin-project-internal
      2     crate://crates.io/pkg-config
      2     crate://crates.io/proc-macro2
      2     crate://crates.io/quinn-udp
      2     crate://crates.io/remove_dir_all
      2     crate://crates.io/rustix
      2     crate://crates.io/ryu
      2     crate://crates.io/scroll
      2     crate://crates.io/scroll_derive
      2     crate://crates.io/security-framework
      2     crate://crates.io/security-framework-sys
      2     crate://crates.io/sharded-slab
      2     crate://crates.io/signature
      2     crate://crates.io/slab
      2     crate://crates.io/smallvec
      2     crate://crates.io/syn
      2     crate://crates.io/synstructure
      2     crate://crates.io/terminal_size
      2     crate://crates.io/thiserror
      2     crate://crates.io/thiserror-impl
      2     crate://crates.io/tikv-jemalloc-sys
      2     crate://crates.io/tikv-jemallocator
      2     crate://crates.io/tinyvec
      2     crate://crates.io/tokio-io-timeout
      2     crate://crates.io/tracing-core
      2     crate://crates.io/tracing-subscriber
      2     crate://crates.io/try-lock
      2     crate://crates.io/unicode-bidi
      2     crate://crates.io/unicode-normalization
      2     crate://crates.io/unicode-segmentation
      2     crate://crates.io/unicode-width
      2     crate://crates.io/utf-8
      2     crate://crates.io/version_check
      2     crate://crates.io/walkdir
      2     crate://crates.io/wasm-bindgen-futures
      2     crate://crates.io/web-sys
      3     crate://crates.io/cc
      3     crate://crates.io/hermit-abi
      3     crate://crates.io/ppv-lite86
      3     crate://crates.io/rustc-demangle
      3     crate://crates.io/termcolor
      3     crate://crates.io/which

This issue has also nasty side effect that which leads to ugly exception as reported in:
https://lists.openembedded.org/g/openembedded-core/message/179356
which is caused by race condition between sugar.do_unpack and solana-cli.do_fetch where
sugar already fetched and varified downloads/arrayvec-0.7.2.crate just fine, but then
solana-cli decides to rename this file to:
arrayvec-0.7.2.crate_bad-checksum_8da52d66c7071e2e3fa2a1e5c6d088fec47b593032b254f5e980de8ea54454d6
because of the checksum mismatch because it was seeing the checksum of 0.7.1 before they were
changed to be version specific:
-SRC_URI[arrayvec.sha256sum] = "8da52d66c7071e2e3fa2a1e5c6d088fec47b593032b254f5e980de8ea54454d6"
+SRC_URI[arrayvec-0.7.2.sha256sum] = "8da52d66c7071e2e3fa2a1e5c6d088fec47b593032b254f5e980de8ea54454d6"
-SRC_URI[arrayvec.sha256sum] = "be4dc07131ffa69b8072d35f5007352af944213cde02545e2103680baed38fcd"
+SRC_URI[arrayvec-0.7.1.sha256sum] = "be4dc07131ffa69b8072d35f5007352af944213cde02545e2103680baed38fcd"

NOTE: recipe sugar-1.1.0-r0: task do_unpack: Started
ERROR: sugar-1.1.0-r0 do_unpack: Error executing a python function in exec_func_python() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_func_python() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:base_do_unpack(d)
     0003:
File: '/OE/lge/build/webos/mickledore/oe-core/meta/classes-global/base.bbclass', lineno: 160, function: base_do_unpack
     0156:        return
     0157:
     0158:    try:
     0159:        fetcher = bb.fetch2.Fetch(src_uri, d)
 *** 0160:        fetcher.unpack(d.getVar('WORKDIR'))
     0161:    except bb.fetch2.BBFetchException as e:
     0162:        bb.fatal("Bitbake Fetcher Error: " + repr(e))
     0163:}
     0164:
File: '/OE/lge/build/webos/mickledore/bitbake/lib/bb/fetch2/__init__.py', lineno: 1882, function: unpack
     1878:
     1879:            if ud.lockfile:
     1880:                lf = bb.utils.lockfile(ud.lockfile)
     1881:
 *** 1882:            ud.method.unpack(ud, root, self.d)
     1883:
     1884:            if ud.lockfile:
     1885:                bb.utils.unlockfile(lf)
     1886:
File: '/OE/lge/build/webos/mickledore/bitbake/lib/bb/fetch2/crate.py', lineno: 84, function: unpack
     0080:        """
     0081:        Uses the crate to build the necessary paths for cargo to utilize it
     0082:        """
     0083:        if ud.type == 'crate':
 *** 0084:            return self._crate_unpack(ud, rootdir, d)
     0085:        else:
     0086:            super(Crate, self).unpack(ud, rootdir, d)
     0087:
     0088:    def _crate_unpack(self, ud, rootdir, d):
File: '/OE/lge/build/webos/mickledore/bitbake/lib/bb/fetch2/crate.py', lineno: 113, function: _crate_unpack
     0109:            # ensure we've got these paths made
     0110:            bb.utils.mkdirhier(cargo_bitbake)
     0111:
     0112:            # generate metadata necessary
 *** 0113:            with open(thefile, 'rb') as f:
     0114:                # get the SHA256 of the original tarball
     0115:                tarhash = hashlib.sha256(f.read()).hexdigest()
     0116:
     0117:            metadata['files'] = {}
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/OE/lge/build/webos/mickledore/downloads/arrayvec-0.7.2.crate'

ERROR: Logfile of failure stored in: /OE/lge/build/webos/mickledore/BUILD/work/qemux86_64-webos-linux/sugar/1.1.0-r0/temp/log.do_unpack.2600442
NOTE: recipe sugar-1.1.0-r0: task do_unpack: Failed

...

NOTE: recipe solana-cli-1.14.5-r0: task do_fetch: Started
WARNING: solana-cli-1.14.5-r0 do_fetch: Checksum failure encountered with download of crate://crates.io/arrayvec/0.7.2 - will attempt other sources if available
ERROR: solana-cli-1.14.5-r0 do_fetch: Fetcher failure for URL: 'https://crates.io/api/v1/crates/arrayvec/0.7.2/download'. Checksum mismatch!
File: '/OE/lge/build/webos/mickledore/downloads/arrayvec-0.7.2.crate.tmp' has sha256 checksum '8da52d66c7071e2e3fa2a1e5c6d088fec47b593032b254f5e980de8ea54454d6' when 'be4dc07131ffa69b8072d35f5007352af944213cde02545e2103680baed38fcd' was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[arrayvec.sha256sum] = "8da52d66c7071e2e3fa2a1e5c6d088fec47b593032b254f5e980de8ea54454d6"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I102e44c2f04344df29d651357170682e671ac107