mycroft, audit, glib-networking=webos1 (fix file-rdeps QA issue fix about /bin/bash)
:Release Notes:

:Detailed Notes:
glib-networking: added in:
https://git.openembedded.org/openembedded-core/commit/?id=12a9bb0feed96a0f3e0795106c6d95755ccb42b0
fixes:
ERROR: glib-networking-2.68.1-r0 do_package_qa: QA Issue: /usr/libexec/installed-tests/glib-networking/files/create-files.sh contained in package glib-networking-ptest requires /bin/bash, but no providers found in RDEPENDS_glib-networking-ptest? [file-rdeps]

mycroft: added in:
https://git.openembedded.org/meta-openembedded/commit/?id=4f0d10e870e265b7d014d80ac75cd6a83c5da836

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I82f1dccefd1d1393b00e81f1975a62f0eea1be9e