webos: libgcrypt: adjust 0002-libgcrypt-fix-building-error-with-O2-in-sysroot-path.patch to apply
:Release Notes:
Fails to apply on 1.10.2 version used since mickledore.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/816546

ERROR: Applying patch '0002-libgcrypt-fix-building-error-with-O2-in-sysroot-path.patch' on target directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/libgcrypt/1.10.2-r0/libgcrypt-1.10.2'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/qemux86_64-webos-linux/libgcrypt/1.10.2-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0002-libgcrypt-fix-building-error-with-O2-in-sysroot-path.patch
patching file cipher/Makefile.am
Hunk #1 succeeded at 153 (offset 3 lines).
patching file random/Makefile.am
patch: **** malformed patch at line 48: ./meta-webos/recipes-support/libgcrypt/libgcrypt

Patch 0002-libgcrypt-fix-building-error-with-O2-in-sysroot-path.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-693] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I665d13150858ef9acd154932755b186c0faaa71c