webos: node-gyp-packages-native: use UNPACKDIR
:Release Notes:
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/846714

ERROR: QA Issue: node-gyp-packages-native: LIC_FILES_CHKSUM points to an invalid file:
  TOPDIR/BUILD/work/x86_64-linux/node-gyp-packages-native/0.12.2/node-gyp-packages/abbrev_1.0.5/package/LICENSE [license-checksum]
...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: I48819c8e4c5aa2937f62673fe29b363379d90cbf