webos: pv=webos1 (remove glibc-binary-localedata-c ptest dependency)
:Release Notes:
We don't have these available in the build, due to:
webos-toolchain.inc:GLIBC_GENERATE_LOCALES = "en_US.UTF-8"

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1150391
ERROR: QA Issue: pv-ptest rdepends on glibc-binary-localedata-c, but it isn't a build dependency? [build-deps]

Added in:
https://git.openembedded.org/meta-openembedded/commit/?id=5756aa17e8cefc1be95b8fc6a9b8527570d1d683

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ic139fa02015a30f481b362d8b92e44a51d818b5c