WIP: test some reviews for scarthgap
:Release Notes:

:Detailed Notes:
python3-pydantic-core:
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
http://gecko.lge.com:8000/Errors/Details/902112
see https://lists.openembedded.org/g/openembedded-devel/message/111261"

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2117] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: Icbf1c719ae86d66789156f910706a6f50a6f0206