busybox: update the patches to apply on 1.35.0 version from oe-core
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: busybox-1.35.0-r0 do_patch: Fuzz detected:

Applying patch 0002-date-add-support-for-options-U-and-S.patch
patching file coreutils/date.c
Hunk #6 succeeded at 286 with fuzz 2 (offset 1 line).
Hunk #7 succeeded at 340 (offset 1 line).

The context lines in the patches can be updated with devtool:

    devtool modify busybox
    devtool finish --force-patch-refresh busybox <layer_path>

Don't forget to review changes done by devtool!

ERROR: busybox-1.35.0-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I4e7a7ba73aaa5304c753bf50e6483e2f5ed87560