webos: webos-nettools=r4 (use gnu17 even with gcc-15)
:Release Notes:
gcc-15 uses gnu23 standard for c since:
https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212
but this component isn't readly for it and fails to build.

:Detailed Notes:
This should be properly fixed by component owner, this is just temporary
work around.

http://gecko.lge.com:8000/Errors/Details/1142232
webos-nettools/1.1.0-43/git/src/main.c:51:13: error: too many arguments to function 'initialize_nettools_ls2_calls'; expected 0, have 1

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ib7841dc31efe1f51b735c67b7eb3404ab67784da