webos: images: replace debug-tweaks with allow-empty-password empty-root-password allow-root-login post-install-logging
:Release Notes:
This is just temporary work around to unblock the builds while keeping
everything as it was before. Later we should re-evaluate which features
we want to keep enabled where and take advantage of this separation.

:Detailed Notes:
See:
https://git.openembedded.org/openembedded-core/commit/?id=2c229f9542c6ba608912e14c9c3f783c3fa89349
https://git.openembedded.org/openembedded-core/commit/?id=6e572580164d06e3af88fd607d9ef32a5e84166a

Now all image builds were failing with:
ERROR: Nothing PROVIDES 'webos-image'
webos-image was skipped: 'debug-tweaks' in IMAGE_FEATURES is not a valid image feature. Valid features: allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs dev-pkgs doc doc-pkgs eclipse-debug empty-root-password hwcodecs lic-pkgs nfs-client nfs-server overlayfs-etc package-management post-install-logging ptest-pkgs read-only-rootfs read-only-rootfs-delayed-postinsts serial-autologin-root splash src-pkgs ssh-server-dropbear ssh-server-openssh stateless-rootfs staticdev-pkgs tools-debug tools-profile tools-sdk tools-testapps webos-checksec-scan webos-devel webos-devel webos-extended webos-extended webos-extract-ls2-api webos-minimal webos-minimal webos-production-image webos-systemapps webos-systemapps webos-systemservices webos-test webos-test webos-testapps webos-testapps webos-validate-ls2-conf weston x11 x11-base x11-sato
ERROR: Nothing PROVIDES 'webos-image-devel'
webos-image-devel was skipped: 'debug-tweaks' in IMAGE_FEATURES is not a valid image feature. Valid features: allow-empty-password allow-root-login bash-completion-pkgs dbg-pkgs dev-pkgs doc doc-pkgs eclipse-debug empty-root-password hwcodecs lic-pkgs nfs-client nfs-server overlayfs-etc package-management post-install-logging ptest-pkgs read-only-rootfs read-only-rootfs-delayed-postinsts serial-autologin-root splash src-pkgs ssh-server-dropbear ssh-server-openssh stateless-rootfs staticdev-pkgs tools-debug tools-profile tools-sdk tools-testapps webos-checksec-scan webos-devel webos-devel webos-extended webos-extended webos-extract-ls2-api webos-minimal webos-minimal webos-production-image webos-systemapps webos-systemapps webos-systemservices webos-test webos-test webos-testapps webos-testapps webos-validate-ls2-conf weston x11 x11-base x11-sato

as we have it enabled even in end-user images.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I97350e47f1f09390807713a2309ffdb1191d3093