webos: gstreamer1.0-plugins-bad: update patches to apply on 1.26.0
:Release Notes:
oe-core upgrade to 1.26.0:
https://git.openembedded.org/openembedded-core/log/?id=527f58c8d0aa0c1b516ae47feffa406e32dbd81f

:Detailed Notes:
Fixes:
ERROR: gstreamer1.0-plugins-bad-1.26.0-r0 do_patch: QA Issue: Fuzz detected:

Applying patch 0004-waylandsink-remove-unsupported-subcompositor.patch
patching file ext/wayland/gstwaylandsink.c
Hunk #8 succeeded at 715 (offset -27 lines).
Hunk #9 succeeded at 814 (offset -27 lines).
Hunk #10 succeeded at 914 (offset -25 lines).
Hunk #11 succeeded at 933 (offset -25 lines).
Hunk #12 succeeded at 944 (offset -25 lines).
Hunk #13 succeeded at 1139 with fuzz 1 (offset -25 lines).
Hunk #14 succeeded at 1222 (offset -21 lines).
Hunk #15 succeeded at 1234 (offset -21 lines).
patching file ext/wayland/gstwaylandsink.h
patching file gst-libs/gst/wayland/gstwldisplay.c
Hunk #3 succeeded at 302 (offset -3 lines).
Hunk #4 succeeded at 450 (offset -3 lines).
Hunk #5 succeeded at 611 (offset 11 lines).
patching file gst-libs/gst/waylan/gstwlwindow.c
Hunk #5 succeeded at 211 (offset -1 lines).
Hunk #6 succeeded at 221 (offset -1 lines).
Hunk #7 succeeded at 231 (offset -1 lines).
Hunk #8 succeeded at 240 (offset -1 lines).
Hunk #9 succeeded at 295 (offset -1 lines).
Hunk #10 succeeded at 307 (offset -1 lines).
Hunk #11 succeeded at 332 (offset -1 lines).
Hunk #12 succeeded at 347 (offset -1 lines).
Hunk #13 succeeded at 377 (offset -1 lines).
Hunk #14 succeeded at 416 (offset -1 lines).
Hunk #15 succeeded at 431 (offset -1 lines).
Hunk #16 succeeded at 475 (offset -1 lines).
Hunk #17 succeeded at 498 (offset -1 lines).
Hunk #18 succeeded at 550 (offset -1 lines).
Hunk #19 succeeded at 559 (offset -1 lines).
Hunk #20 succeeded at 576 (offset -1 lines).
Hunk #21 succeeded at 641 (offset -1 lines).
Hunk #22 succeeded at 656 (offset -1 lines).
Hunk #23 succeeded at 709 (offset -1 lines).

Applying patch 0005-h264parse-resolution-changed-event-support.patch
patching file gst/videoparsers/gsth264parse.c
Hunk #4 succeeded at 2156 (offset 38 lines).
Hunk #5 succeeded at 2228 (offset 38 lines).
Hunk #6 succeeded at 2267 (offset 38 lines).
patching file gst/videoparsers/gsth264parse.h
patching file gst/videoparsers/meson.build
Hunk #1 succeeded at 50 with fuzz 2 (offset 33 lines).

The context lines in the patches can be updated with devtool:

    devtool modify gstreamer1.0-plugins-bad
    devtool finish --force-patch-refresh gstreamer1.0-plugins-bad <layer_path>

Don't forget to review changes done by devtool!

Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I4a8f16593afa0f944220f6a216c48bb3f72c0e11