report-error.bbclass: use new oe.buildcfg module
:Release Notes:
old functions were removed in:
https://git.openembedded.org/openembedded-core/commit/?id=439cdf8a1e52fd2c4dc81dc40ce7e6af282ce7ac

:Detailed Notes:
Fixes:
ERROR: Execution of event handler 'defaulterrorreport_handler' failed
Traceback (most recent call last):
  File "/OE/lge/build/webos/langdale/meta-lg-webos/meta-webos/classes/report-error.bbclass", line 356, in defaulterrorreport_handler(e=<bb.event.BuildStarted object at 0x7fd82607d8d0>):
                 jsondata['target'] = targets
    >            jsondata['branch_commit'] = base_detect_branch(e.data) + ": " + base_detect_revision(e.data)
                 jsondata['build_started'] = round(time.time())
NameError: name 'base_detect_branch' is not defined

ERROR: Command execution failed: Traceback (most recent call last):
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/command.py", line 126, in runAsyncCommand
    commandmethod(self.cmds_async, self, options)
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/command.py", line 607, in buildTargets
    command.cooker.buildTargets(pkgs_to_build, task)
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/cooker.py", line 1578, in buildTargets
    bb.event.fire(bb.event.BuildStarted(buildname, ntargets), self.databuilder.mcdata[mc])
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/event.py", line 222, in fire
    fire_class_handlers(event, d)
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/event.py", line 123, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/OE/lge/build/webos/langdale/bitbake/lib/bb/event.py", line 93, in execute_handler
    ret = handler(event)
  File "/OE/lge/build/webos/langdale/meta-lg-webos/meta-webos/classes/report-error.bbclass", line 356, in defaulterrorreport_handler
    jsondata['branch_commit'] = base_detect_branch(e.data) + ": " + base_detect_revision(e.data)
NameError: name 'base_detect_branch' is not defined

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale

Change-Id: I6087683d2bfec98ac22b549b932a73c1dcd7d03b