qtbase=webos93 (inherit webos_pkgconfig)
:Release Notes:
Newer oe-core doesn't pull many default dependencies anymore:
https://lists.openembedded.org/g/openembedded-core/message/156185
add explicit dependency on pkgconfig through webos_pkgconfig.bbclass as
we're using it here.

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/241340
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
...
ERROR: Feature "zstd": Forcing to "ON" breaks its condition:
ERROR: Feature "libudev": Forcing to "ON" breaks its condition:

:Testing Performed:
Only build tested.

:QA Notes:
No change to the image.

:Issues Addressed:
[WRN-7597] CCC: Various build fixes

Change-Id: I4cc05e0106117d752f25bd1a73ced7bdb3cc2f0e