strace=webos1 gawk=webos1 (remove locale-base-en-us.iso-8859-1 runtime dependency)
:Release Notes:
Undo RDEPENDS_${PN}-ptest changes from:
https://git.openembedded.org/openembedded-core/commit/?id=ea6f27e35b6cac4db9e1ab0d9a888d15daba6c09
https://git.openembedded.org/openembedded-core/commit/?id=69ce1914484a86e9f440aeaab887cae671d679b9
because they aren't compatible with our locale settings.

:Detailed Notes:
Fixes:
ERROR: gawk-5.1.0-r0 do_package_qa: QA Issue: gawk-ptest rdepends on locale-base-en-us.iso-8859-1, but it isn't a build dependency? [build-deps]
ERROR: strace-5.10-r0 do_package_qa: QA Issue: strace-ptest rdepends on locale-base-en-us.iso-8859-1, but it isn't a build dependency? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-124341] Create GPVB with Yocto 3.3 Hardknott

Change-Id: I02c0c6ccd02a65f8bebec0bf9ad09b9ca70a245f