webos: webos.inc: disable return-type Werror for canopenterm
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1029672

FAILED: CMakeFiles/core.dir/src/core/can_linux.c.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-gcc --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot -DLUA_USE_C89 -DLUA_USE_LINUX -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot/usr/include/SDL2 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot/usr/include/pocketpy -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/PUBLIC -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/api -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/core -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/os -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/picoc -mcpu=cortex-a72+crc -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git=/usr/src/debug/canopenterm/1.0.8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git=/usr/src/debug/canopenterm/1.0.8  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/build=/usr/src/debug/canopenterm/1.0.8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/build=/usr/src/debug/canopenterm/1.0.8  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/recipe-sysroot-native=  -pipe  -std=gnu90 -MD -MT CMakeFiles/core.dir/src/core/can_linux.c.o -MF CMakeFiles/core.dir/src/core/can_linux.c.o.d -o CMakeFiles/core.dir/src/core/can_linux.c.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/core/can_linux.c
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/core/can_linux.c: In function 'can_print_channel_help':
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/canopenterm/1.0.8/git/src/core/can_linux.c:140:1: error: control reaches end of non-void function [-Werror=return-type]
  140 | }
      | ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I8ac53cb5e3fbe1d8f2df4590573fc6f69c41cdba