webos: nlohmann-json=webos1 (remove locale-base-de-de ptest dependency)
:Release Notes:
We don't have these available in the build, due to:
webos-toolchain.inc:GLIBC_GENERATE_LOCALES = "en_US.UTF-8"

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1182826
ERROR: QA Issue: nlohmann-json-ptest rdepends on locale-base-de-de, but it isn't a build dependency? [build-deps]

Added in:
nlohmann-json: Upgrade 3.11.3 -> 3.12.0

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I07fcac32d0b11f1d7882044108fa81ae27144c2e