webos.inc: add openssh to BAD_RECOMMENDATIONS
:Release Notes:
We were already doing that because of openssh-dbg, but now the openssh-ptest
is causing similar issue in devel images after:
https://git.openembedded.org/openembedded-core/commit/?id=a98188e83b2c027d99cc38e3367e1ec2a98efbb0

With openssh-9 which by default uses sftp, you need to use -O flag
to switch to old scp protocol and then we don't need RRECOMMENDed
openssh-sftp-server on target image.

:Detailed Notes:
Fixes:

ERROR: webos-image-devel-1.0-r2 do_rootfs: Unable to install packages. Command '/OE/lge/build/webosose/langdale/BUILD/work/qemux86_64-webos-linux/webos-image-devel/1.0-r2/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /OE/lge/build/webosose/langdale/BUILD/work/qemux86_64-webos-linux/webos-image-devel/1.0-r2/opkg.conf -t /OE/lge/build/webosose/langdale/BUILD/work/qemux86_64-webos-linux/webos-image-devel/1.0-r2/temp/ipktemp/ -o /OE/lge/build/webosose/langdale/BUILD/work/qemux86_64-webos-linux/webos-image-devel/1.0-r2/rootfs  --force_postinstall --prefer-arch-to-version   --add-ignore-recommends update-rc.d --no-install-recommends install acl-ptest attr-ptest babeltrace2-ptest bluez5-ptest busybox-ptest bzip2-ptest com.webos.service.videooutput-ptest coreutils-ptest curl-ptest dbus-ptest e2fsprogs-ptest elfutils-ptest gawk-ptest gettext-ptest glib-networking-ptest gstreamer1.0-ptest gzip-ptest keyutils-ptest leveldb-ptest libevent-2.1-ptest libexpat-ptest libgcrypt-ptest libgdbm-ptest libgdk-pixbuf-2.0-ptest libglib-2.0-ptest libgpg-error-ptest libnl-3-ptest libpcre-ptest libpopt-ptest libprotobuf-ptest libumi-ptest libusb-1.0-ptest libval-mock-ptest libxml++-2.6-ptest libxml2-ptest libz-ptest luna-service2-ptest nettle-ptest openssh-ptest openssl-ptest opkg-ptest packagegroup-core-boot-ptest packagegroup-core-ssh-dropbear-ptest packagegroup-core-tools-debug-ptest packagegroup-core-tools-profile-ptest packagegroup-webos-devel-ptest packagegroup-webos-extended-ptest packagegroup-webos-ml-ptest packagegroup-webos-test-ptest pango-ptest perl-ptest python3-bcrypt-ptest python3-cryptography-ptest python3-jsonpointer-ptest python3-more-itertools-ptest python3-numpy-ptest python3-ptest python3-pyasn1-ptest python3-wcwidth-ptest python3-webcolors-ptest qtbase-ptest qtdeclarative-ptest qtgraphicaleffects-ptest qtwayland-ptest slang-ptest strace-ptest tcl-ptest util-linux-ptest wayland-ptest' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package openssh-9.0p1-r0.0.qemux86_64 conflicts with dropbear provided by dropbear-2022.82-r0.0webos7.qemux86_64
 *   - package openssh-ptest-9.0p1-r0.0.qemux86_64 requires openssh, but none of the providers can be installed
 *   - package packagegroup-core-ssh-dropbear-1.0-r1.0.qemux86_64 requires dropbear, but none of the providers can be installed
 *   - conflicting requests
 *   - problem with installed package packagegroup-core-ssh-dropbear-1.0-r1.0.qemux86_64
 *
 * Solution 1:
 *   - allow deinstallation of packagegroup-core-ssh-dropbear-1.0-r1.0.qemux86_64

 * Solution 2:
 *   - do not ask to install a package providing openssh-ptest

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale