webos: systemd: update patches to apply on v255.1
:Release Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=ebafe463799b39025a0b24a0a14a2f02b6de9bac

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/767402

ERROR: Applying patch '0002-Add-webos-interface.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/systemd/255.1/git'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/systemd/255.1/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
Hunk #1 succeeded at 5 with fuzz 1.
Hunk #2 succeeded at 38 (offset 21 lines).
patching file src/oom/oomd-manager.c
Hunk #1 FAILED at 14.
Hunk #2 succeeded at 397 (offset 5 lines).
Hunk #3 succeeded at 523 (offset 5 lines).
1 out of 3 hunks FAILED -- rejects in file src/oom/oomd-manager.c
patching file src/oom/oomd.c
Hunk #2 succeeded at 189 (offset -5 lines).
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in
Hunk #1 FAILED at 28.
1 out of 1 hunk FAILED -- rejects in file units/systemd-oomd.service.in
Patch 0002-Add-webos-interface.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I50446cef3587a11e5781085bd2f848d371f63fe0