bluez5 (refresh patches to apply on 5.63 version)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: bluez5-5.63-r0 do_patch: Applying patch '0007-recievePassThrough-commad-support-required-for-webos.patch' on target directory '/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.63-r0/bluez-5.63'
CmdError('quilt --quiltrc /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.63-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0007-recievePassThrough-commad-support-required-for-webos.patch
patching file profiles/audio/avctp.c
patching file src/device.c
Hunk #1 succeeded at 172 (offset 1 line).
Hunk #2 FAILED at 279.
Hunk #3 succeeded at 1388 (offset 77 lines).
Hunk #4 succeeded at 1418 (offset 77 lines).
Hunk #5 succeeded at 1432 (offset 77 lines).
Hunk #6 succeeded at 2045 (offset 105 lines).
Hunk #7 succeeded at 3263 (offset 119 lines).
Hunk #8 succeeded at 4501 (offset 165 lines).
1 out of 8 hunks FAILED -- rejects in file src/device.c
patching file src/device.h
Hunk #1 succeeded at 180 (offset 1 line).
Patch 0007-recievePassThrough-commad-support-required-for-webos.patch does not apply (enforce with -f)

stderr: ')
ERROR: Logfile of failure stored in: /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/bluez5/5.63-r0/temp/log.do_patch.405525

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: Ib353e654e5c18bbbe2494526e53784a6e2bb2eaf