ptmalloc3: fix LIC_FILES_CHKSUM
:Release Notes:
LIC_FILES_CHKSUM usually shouldn't point to COMMON_LICENSE_DIR.

:Detailed Notes:
The generic BSD license was removed in:
https://github.com/openembedded/openembedded-core/commit/14d4c007c49652d836d325a12bdbcd3bfa42e6d5
and the license text doesn't seem to exactly match any other
BSD license.

Fixes:
NOTE: recipe ptmalloc3-1.0-r4: task do_populate_lic: Started
WARNING: ptmalloc3-1.0-r4 do_populate_lic: Could not copy license file /OE/lge/build/webos/kirkstone/oe-core/meta/files/common-licenses/BSD to /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/ptmalloc3/1.0-r4/license-destdir/ptmalloc3/BSD: [Errno 2] No such file or directory: '/OE/lge/build/webos/kirkstone/oe-core/meta/files/common-licenses/BSD'
EacRROR: ptmalloc3-1.0-r4 do_populate_lic: QA Issue: ptmalloc3: LIC_FILES_CHKSUM points to an invalid file: /OE/lge/build/webos/kirkstone/oe-core/meta/files/common-licenses/BSD [license-checksum]
ERROR: ptmalloc3-1.0-r4 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/ptmalloc3/1.0-r4/temp/log.do_populate_lic.2152815

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I9a5f6cbe8b4a4b451a9450c89c1137a52362823c