webos: webos.inc: disable return-type Werror for python3-multidict
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1165425

x86_64-webos-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-all -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot -O2 -g -fcanon-prefix-map -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/git=/usr/src/debug/python3-multidict/6.3.2+git -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/git=/usr/src/debug/python3-multidict/6.3.2+git -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/git=/usr/src/debug/python3-multidict/6.3.2+git -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/git=/usr/src/debug/python3-multidict/6.3.2+git -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot= -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot= -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot-native= -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot-native= -pipe -fPIC -ITOPDIR/BUILD/work/qemux86_64-webos-linux/python3-multidict/6.3.2+git/recipe-sysroot/usr/include/python3.13 -c multidict/_multidict.c -o build/temp.linux-x86_64-cpython-313/multidict/_multidict.o -O3 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
In file included from multidict/_multidict.c:9:
multidict/_multilib/pair_list.h: In function 'pair_list_repr':
multidict/_multilib/pair_list.h:1579:1: error: control reaches end of non-void function [-Werror=return-type]
 1579 | }
      | ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: If164d6aafaa60fd709d307ad285306bf052bad2d