webos: systemd=webos19 (refresh patches to apply on 252.4 version)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: systemd-1_252.4-r0 do_patch: Fuzz detected:

Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
patching file src/oom/oomd-manager.c
Hunk #2 succeeded at 394 (offset -5 lines).
Hunk #3 succeeded at 520 (offset 4 lines).
patching file src/oom/oomd.c
Hunk #1 succeeded at 16 with fuzz 1 (offset 1 line).
Hunk #2 succeeded at 193 (offset 1 line).
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in

The context lines in the patches can be updated with devtool:

    devtool modify systemd
    devtool finish --force-patch-refresh systemd <layer_path>

Don't forget to review changes done by devtool!

ERROR: systemd-1_252.4-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-16197] CCC: Upgrade to Yocto 4.2 Mickledore
[WRR-2118] Create GPVB with Yocto 4.2 Mickledore

Cherry-picked-from-commit: f21b0a283c8030d7f3435072c0a7ccc4fbf0da33
Cherry-picked-from-branch: