webos: fluentbit=webos6
:Release Notes:
Drop incorrect installed-vs-shipped and fix it properly.

:Detailed Notes:
Backport a fix to respect libdir and systemd_system_unitdir (e.g. when
libdir is /usr/lib instead of just /lib with usrmerge in
DISTRO_FEATURES) instead of checking /lib/systemd/system existence on
build host and installing always to such directory.

Fixes:
http://gecko.lge.com:8000/Errors/Details/1000342

ERROR: QA Issue: lib32-fluentbit: Files/directories were installed but not shipped in any package:
  /lib
  /lib/systemd
  /lib/systemd/system
  /lib/systemd/system/fluent-bit.service
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-fluentbit: 4 installed and not shipped files. [installed-vs-shipped]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-8245] CCC: fluentbit=webos6
[WRR-8222] Fix webos4tv sync up

Change-Id: Ie9369807d404cdf5e9a1e52f9b951e41fbb60143
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/452877
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>