qtwayland-webos: fix parsing with newer meta-qt6
:Release Notes:
QT_VERSION is now defined in meta-qt6/conf/layer.conf:
https://code.qt.io/cgit/yocto/meta-qt6.git/commit/?h=6.4&id=cd751f5ae2a0aa0a6641e56a2c524906fd0ea8fb
but unlike:
meta-webos/conf/distro/include/webos.inc:QT_VERSION ?= "6"
it contains whole version, e.g. "6.4.3".

To make both QT_VERSION values work here, check just the first
character from the version.

:Detailed Notes:
Fixes:
ERROR: ParseError at /OE/lge/build/webos/kirkstone/meta-lg-webos/meta-webos/recipes-webos/qtwayland-webos/qtwayland-webos_qmake.inc:3: Could not inherit file classes/webos_qmake5.bbclass
ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: I6bf761b2e095865cbaa31eda2adbc5598507c5cf
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/344512
Reviewed-by: Multi Layer Checker <multi_layer@lge.com>
Reviewed-by: Hyunjae Shin <hyunjae92.shin@lgepartner.com>
Tested-by: Hyunjae Shin <hyunjae92.shin@lgepartner.com>