docker-simple-webserver: WIP install docker.json in /etc/docker instead of /media/internal
:Release Notes:
I don't know why /media/internal was used, but with new Yocto it triggers new
QA error empty-dirs

:Detailed Notes:
Fixes:
ERROR: docker-simple-webserver-0.1.0-r1 do_package_qa: QA Issue: docker-simple-webserver installs files in /media, but it is expected to be empty [empty-dirs]
ERROR: docker-simple-webserver-0.1.0-r1 do_package_qa: Fatal QA errors were found, failing task.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I18faf988449f74ceb130e2a297705d7c7366efc0