gator=r3,v6.9
:Release Notes:
Cleanup recipe and upgrade to slightly newer version, otherwise
gator fails to build with x86 kernel even after enabling profiling
in qemux86 kernel and with 5.10 kernel on rpi.

:Detailed Notes:
Nobody will probably use ARM gator on x86, but there is no COMPATIBLE_MACHINE
restriction in gator recipe and currently it fails for qemux86 with:
work/qemux86-webos-linux/gator/6.7+gitAUTOINC+3ff46fedd4-r2/git/driver/gator_main.c:1399:41: error: initialization of 'struct tracepoint * const*' from incompatible pointer type 'const tracepoint_ptr_t *' {aka 'const int *'} [-Werror=incompatible-pointer-types]
 1399 |     struct tracepoint * const * begin = tp_mod->mod->tracepoints_ptrs;
      |                                         ^~~~~~
work/qemux86-webos-linux/gator/6.7+gitAUTOINC+3ff46fedd4-r2/git/driver/gator_main.c:1400:39: error: initialization of 'struct tracepoint * const*' from incompatible pointer type 'const tracepoint_ptr_t *' {aka 'const int *'} [-Werror=incompatible-pointer-types]
 1400 |     struct tracepoint * const * end = tp_mod->mod->tracepoints_ptrs + tp_mod->mod->num_tracepoints;
      |                                       ^~~~~~

| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_annotate.c:54:9: error: implicit declaration of function 'pr_warning'; did you mean 'pr_warn'? [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_annotate.c:54:9: error: implicit declaration of function 'pr_warning'; did you mean 'pr_warn'? [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:18:81: error: too many arguments to function 'get_user_pages_remote'
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:18:81: error: too many arguments to function 'get_user_pages_remote'
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:265:20: error: 'struct mm_struct' has no member named 'mmap_sem'; did you mean 'mmap_base'?
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:265:20: error: 'struct mm_struct' has no member named 'mmap_sem'; did you mean 'mmap_base'?
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:35: error: passing argument 1 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:35: error: passing argument 1 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:60: error: passing argument 6 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:60: error: passing argument 6 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:67: error: passing argument 7 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:267:67: error: passing argument 7 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:295:18: error: 'struct mm_struct' has no member named 'mmap_sem'; did you mean 'mmap_base'?
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_cookies.c:295:18: error: 'struct mm_struct' has no member named 'mmap_sem'; did you mean 'mmap_base'?
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_meminfo.c:252:49: error: 'NR_SLAB_RECLAIMABLE' undeclared (first use in this function); did you mean 'NR_SLAB_RECLAIMABLE_B'?
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_meminfo.c:252:49: error: 'NR_SLAB_RECLAIMABLE' undeclared (first use in this function); did you mean 'NR_SLAB_RECLAIMABLE_B'?
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_meminfo.c:252:95: error: 'NR_SLAB_UNRECLAIMABLE' undeclared (first use in this function); did you mean 'NR_SLAB_UNRECLAIMABLE_B'?
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_meminfo.c:252:95: error: 'NR_SLAB_UNRECLAIMABLE' undeclared (first use in this function); did you mean 'NR_SLAB_UNRECLAIMABLE_B'?
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:165:21: error: storage size of 'ts' isn't known
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:165:21: error: storage size of 'ts' isn't known
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:77:21: error: storage size of 'ts' isn't known
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:77:21: error: storage size of 'ts' isn't known
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:79:5: error: implicit declaration of function 'getnstimeofday' [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:79:5: error: implicit declaration of function 'getnstimeofday' [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:80:17: error: implicit declaration of function 'timespec_to_ns'; did you mean 'timespec64_to_ns'? [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_events_mmapped.c:80:17: error: implicit declaration of function 'timespec_to_ns'; did you mean 'timespec64_to_ns'? [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:1469:17: error: implicit declaration of function 'cpu_up' [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:1469:17: error: implicit declaration of function 'cpu_up' [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:593:21: error: storage size of 'ts' isn't known
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:593:21: error: storage size of 'ts' isn't known
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:600:5: error: implicit declaration of function 'getrawmonotonic' [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:600:5: error: implicit declaration of function 'getrawmonotonic' [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:601:17: error: implicit declaration of function 'timespec_to_ns'; did you mean 'timespec64_to_ns'? [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:601:17: error: implicit declaration of function 'timespec_to_ns'; did you mean 'timespec64_to_ns'? [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:720:21: error: storage size of 'ts' isn't known
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:720:21: error: storage size of 'ts' isn't known
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:733:9: error: implicit declaration of function 'getnstimeofday' [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:733:9: error: implicit declaration of function 'getnstimeofday' [-Werror=implicit-function-declaration]
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:781:21: error: storage size of 'ts' isn't known
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:781:21: error: storage size of 'ts' isn't known
| /jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:807:10: error: implicit declaration of function 'timespec64_to_timespec'; did you mean 'timespec64_to_ktime'? [-Werror=implicit-function-declaration]
/jenkins/mjansa/build/ose-github/hardknott/BUILD/work/raspberrypi4-webos-linux-gnueabi/gator/6.7+gitAUTOINC+3ff46fedd4-r3/git/driver/gator_main.c:807:10: error: implicit declaration of function 'timespec64_to_timespec'; did you mean 'timespec64_to_ktime'? [-Werror=implicit-function-declaration]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-121806] CCC: various build issues

Change-Id: Idb89766c021d79b265f8eebd7bd4f3be672c92c9