iotivity org.ocf.webossample.oc{client,server}basicops: fix branch name
:Release Notes:
Use correct branch to fix build failure without pre-populated premirror.

:Detailed Notes:
Fixes:
ERROR: iotivity-1.3.99+gitAUTOINC+255060695e-r7 do_fetch: Fetcher failure: Unable to find revision 59ae96f167a19f4d04dc6db61f6587b37ccd429f in branch mbedtls-2.4 even from upstream
ERROR: iotivity-1.3.99+gitAUTOINC+255060695e-r7 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.',
  'git://github.com/ARMmbed/mbedtls.git;destsuffix=git/extlibs/mbedtls/mbedtls;protocol=https;branch=mbedtls-2.4;name=mbedtls')
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ose-github/dunfell/BUILD/work/raspberrypi4_64-webos-linux/iotivity/1.3.99+gitAUTOINC+255060695e-r7/temp/log.do_fetch.1489629
ERROR: Task (/jenkins/mjansa/build/ose-github/dunfell/meta-webosose/meta-webos/recipes-core/iotivity/iotivity_git.bb:do_fetch) failed with exit code '1'
ERROR: org.ocf.webossample.occlientbasicops-1.0-r5 do_fetch: Fetcher failure: Unable to find revision 59ae96f167a19f4d04dc6db61f6587b37ccd429f in branch mbedtls-2.4 even from upstream
ERROR: org.ocf.webossample.occlientbasicops-1.0-r5 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.',
  'git://github.com/ARMmbed/mbedtls.git;destsuffix=iotivity/extlibs/mbedtls/mbedtls;protocol=https;branch=mbedtls-2.4;name=mbedtls')
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ose-github/dunfell/BUILD/work/raspberrypi4_64-webos-linux/org.ocf.webossample.occlientbasicops/1.0-r5/temp/log.do_fetch.1828956
ERROR: Task (/jenkins/mjansa/build/ose-github/dunfell/meta-webosose/meta-webos/recipes-webos/org.ocf.webossample.occlientbasicops/org.ocf.webossample.occlientbasicops.bb:do_fetch) failed with exit code '1'
ERROR: org.ocf.webossample.ocserverbasicops-1.0-r5 do_fetch: Fetcher failure: Unable to find revision 59ae96f167a19f4d04dc6db61f6587b37ccd429f in branch mbedtls-2.4 even from upstream
ERROR: org.ocf.webossample.ocserverbasicops-1.0-r5 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.',
  'git://github.com/ARMmbed/mbedtls.git;destsuffix=iotivity/extlibs/mbedtls/mbedtls;protocol=https;branch=mbedtls-2.4;name=mbedtls')
ERROR: Logfile of failure stored in: /jenkins/mjansa/build/ose-github/dunfell/BUILD/work/raspberrypi4_64-webos-linux/org.ocf.webossample.ocserverbasicops/1.0-r5/temp/log.do_fetch.1844344
ERROR: Task (/jenkins/mjansa/build/ose-github/dunfell/meta-webosose/meta-webos/recipes-webos/org.ocf.webossample.ocserverbasicops/org.ocf.webossample.ocserverbasicops.bb:do_fetch) failed with exit code '1'

:Testing Performed:
Build tested, no change in the image.

:Issues Addressed:
[WRN-16369] CCC: Upgrade to latest revisions from Yocto 3.1 Dunfell

Change-Id: I4a33e808fa8d60d65b55fac6f8a1af8bece5be8d