webos: enact-dev-native=v6.0.4
:Release Notes:
Upgrade to resolve strip-ansi and ansi-regex conflict.

Detailed Notes:
Use newer strip-ansi which contains this commit:
https://github.com/chalk/strip-ansi/commit/7cda68dcadde18b19bfa31b6223e9f0e60b3e319
to be compatible with ansi-regex-6 and avoid:

http://gecko.lge.com:8000/Errors/Details/781131

NOTE: Bundling Enact app to image/usr/palm/applications/com.webos.app.bugreport
Error [ERR_REQUIRE_ESM]: require() of ES Module recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/node_modules/ansi-regex/index.js from recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/index.js not supported.
Instead change the require of recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/node_modules/ansi-regex/index.js in recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/index.js:2:19)

I can update strip-ansi in npm-shrinkwrap to fix compatibility
with newer ansi-regex (used with npmsw fetcher), but that causes
enact/cli itself to fail:

NOTE: Bundling Enact app to /OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/image/usr/palm/applications/com.webos.app.bugreport
Error [ERR_REQUIRE_ESM]: require() of ES Module /OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/recipe-sysroot-native/usr/lib/node_modules/@enact/cli/node_modules/strip-ansi/index.js from /OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/recipe-sysroot-native/usr/lib/node_modules/@enact/cli/commands/pack.js not supported.
Instead change the require of index.js in /OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/recipe-sysroot-native/usr/lib/node_modules/@enact/cli/commands/pack.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/recipe-sysroot-native/usr/lib/node_modules/@enact/cli/commands/pack.js:21:19)
ERROR: No bundling results in /OE/lge/build/webos/scarthgap/BUILD/work/raspberrypi4_64-webos-linux/com.webos.app.bugreport/1.3.0-28/image/usr/palm/applications/com.webos.app.bugreport; exiting!
WARNING: exit code 1 from a shell command.

So upgrade to newer version which uses newer strip-ansi since 6.0.2 with:
https://github.com/enactjs/cli/commit/c92256505bef822429e13dcfeae097f9ef261100

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-12001] CCC: enact-dev-native=v6.0.4
[WRO-5448] Nodejs recipes should use bitbake fetcher to fetch
           sources in do_fetch instead of npm fetching them in
           do_install

Change-Id: I9c9c7b7a24eeba6a3cb9df76a0f1c1b6152f69c4