connman (refresh patches to apply on 1.40 version)
:Release Notes:

:Detailed Notes:
Fixes:
ERROR: connman-1.40-r0 do_patch: Command Error: 'quilt --quiltrc /jenkins/mjansa/build/ose-github/honister/BUILD/work/raspberrypi4-webos-linux-gnueabi/connman/1.40-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0011-Read-WpaSupplicantConfigFile-from-main-configuration.patch
patching file include/setting.h
Hunk #1 FAILED at 29.
1 out of 1 hunk FAILED -- rejects in file include/setting.h
patching file plugins/wifi.c
Hunk #1 succeeded at 1628 (offset 10 lines).
Hunk #2 succeeded at 1646 (offset 10 lines).
patching file src/main.c
Hunk #1 succeeded at 91 (offset 8 lines).
Hunk #2 succeeded at 117 (offset 11 lines).
Hunk #3 succeeded at 144 (offset 14 lines).
Hunk #4 succeeded at 171 (offset 17 lines).
Hunk #5 succeeded at 304 with fuzz 2 (offset 20 lines).
Hunk #6 succeeded at 443 (offset 20 lines).
Hunk #7 succeeded at 779 with fuzz 1 (offset 68 lines).
Patch 0011-Read-WpaSupplicantConfigFile-from-main-configuration.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister

Change-Id: I9a484682dfbe45c439d8bc7fca975e0cb586a407