webos: qml-webos-components=r22
:Release Notes:
Fix build error

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1095316

../../../git/pmtrace/plugin/pmtraceplugin.cpp:30:91: warning: cannot declare member function 'static QObject* PmTracePlugin::pmTraceProvider(QQmlEngine*, QJSEngine*)' to have static linkage [-fpermissive]
   30 | static QObject *PmTracePlugin::pmTraceProvider(QQmlEngine *engine, QJSEngine *scriptEngine)
      |                                                                                           ^
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qml-webos-components/1.0.0-59/recipe-sysroot/usr/include/lttng/tracepoint-rcu.h:10,
                 from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qml-webos-components/1.0.0-59/recipe-sysroot/usr/include/lttng/tracepoint.h:13,
                 from ../../../git/pmtrace/plugin/pmtrace_qmlplugin_provider.h:31,
                 from ../../../git/pmtrace/plugin/QmlPluginTracer.h:22,
                 from ../../../git/pmtrace/plugin/pmtrace.cpp:24:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/qml-webos-components/1.0.0-59/recipe-sysroot/usr/include/urcu/compiler.h:205:1: error: template with C linkage
  205 | template <typename T>

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-20814] [NANO] CCC: qml-webos-components=r22
[WRR-17603] Fix build with liburcu-0.15.0

Change-Id: I6f398e51e4eea9429fed09d341f8bec1afcfe797