webos: m4=webos2 (remove locale-base-fr-fr runtime dependency)
:Release Notes:

:Detailed Notes:
Added in:
https://git.openembedded.org/openembedded-core/commit/meta/recipes-devtools/m4?id=e15ad965f22fe14270274687eff9849256a74fec

Fixes:
http://gecko.lge.com/Errors/Details/508600
ERROR: QA Issue: lib32-m4-ptest rdepends on lib32-locale-base-fr-fr, but it isn't a build dependency? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-412] Create GPVB with Yocto 4.2 Mickedore

Change-Id: If9eb36f21f3407c4deba742e054b57aa1a68ccd0