meta-webos-updater: define LAYERDEPENDS
:Release Notes:
Define LAYERDEPENDS to fix layer parsing with yocto-check-layer tool.

:Detailed Notes:
INFO: ======================================================================
INFO: ERROR: test_parse (common.CommonCheckLayer)
INFO: ----------------------------------------------------------------------
INFO: Traceback (most recent call last):
  File "/OE/openembedded-core/scripts/lib/checklayer/cases/common.py", line 30, in test_parse
    check_command('Layer %s failed to parse.' % self.tc.layer['name'],
  File "/OE/openembedded-core/scripts/lib/checklayer/__init__.py", line 256, in check_command
    raise RuntimeError(msg)
RuntimeError: Layer meta-webos-updater failed to parse.
Command: bitbake -p
Output:
Loading cache...done.
Loaded 0 entries from dependency cache.
Parsing recipes...done.
ERROR: No recipes in default available for:
  /OE/meta-webosose/meta-webos-updater/recipes-core/images/initramfs-ostree-image.bbappend
  /OE/meta-webosose/meta-webos-updater/recipes-core/initscripts/webos-initscripts.bbappend
  /OE/meta-webosose/meta-webos-updater/recipes-sota/ostree-initrd/ostree-initrd.bbappend
  /OE/meta-webosose/meta-webos-updater/recipes-webos/com.webos.service.contextintentmgr/com.webos.service.contextintentmgr.bbappend
Parsing of 2613 .bb files complete (0 cached, 2613 parsed). 4086 targets, 277 skipped, 0 masked, 0 errors.

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: I37c3bd3b192b16ffd1da7f99ebaaee684a0c6515