webos: auto-luna-surface-manager=r8
:Release Notes:
Add ANY_OF_DISTRO_FEATURES restriction.

:Detailed Notes:
ERROR: Nothing PROVIDES 'luna-surfacemanager' (but /OE/lge/build/webos/kirkstone/meta-lg-webos/meta-webos/recipes-webos/auto-luna-surface-manager/auto-luna-surface-manager.bb DEPENDS on or otherwise requires it)
luna-surfacemanager was skipped: one of 'vulkan opengl' needs to be in DISTRO_FEATURES

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: auto-luna-surface-manager=r8
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Change-Id: Id9ace23cefb4cacdaac4fe46573c698d6c4bb241
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/404113
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>