rpi: u-boot: update patch to apply on v2023.07
:Release Notes:
Upgraded in oe-core with;
https://git.openembedded.org/openembedded-core/commit/?id=396f66ce025a5b2ae15cc82f2ac53664fd3d9dad

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/637085

ERROR: Applying patch '0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch' on target directory 'TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/1_2023.07-r0/git'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/u-boot/1_2023.07-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch
patching file configs/rpi_3_32b_defconfig
Hunk #1 succeeded at 14 (offset 1 line).
Hunk #2 FAILED at 50.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_32b_defconfig
patching file configs/rpi_3_b_plus_defconfig
Hunk #1 succeeded at 13 (offset 1 line).
Hunk #2 FAILED at 49.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_b_plus_defconfig
patching file configs/rpi_3_defconfig
Hunk #1 succeeded at 13 (offset 1 line).
Hunk #2 FAILED at 49.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_3_defconfig
patching file configs/rpi_4_32b_defconfig
Hunk #1 succeeded at 13 with fuzz 1 (offset 2 lines).
Hunk #2 FAILED at 66.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_32b_defconfig
patching file configs/rpi_4_defconfig
Hunk #1 succeeded at 13 with fuzz 1 (offset 2 lines).
Hunk #2 FAILED at 64.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_4_defconfig
patching file configs/rpi_arm64_defconfig
Hunk #1 succeeded at 13 with fuzz 1 (offset 2 lines).
Hunk #2 FAILED at 56.
1 out of 2 hunks FAILED -- rejects in file configs/rpi_arm64_defconfig
patching file include/configs/rpi.h
Patch 0001-Speed-up-boot-by-disable-usb-and-enable-bootcount.patch does not apply (enforce with -f)

CONFIG_OF_LIBFDT_OVERLAY=y
was moved to right place in:
  commit c358af81d0df0ba5eadda585577425345dae55ed
  Author: Tom Rini <trini@konsulko.com>
  Date:   Mon Mar 27 13:39:17 2023 -0400

    configs: Resync with savedefconfig

    Rsync all defconfig files using moveconfig.py

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I0b1f61b8913b236b8c3c325cc70371ffc0b2bf77