webos: qtbase: drop libgles3-mesa-dev RRECOMMENDS
:Release Notes:
GL ES 3 packages were folded into GL ES 2 in:
https://git.openembedded.org/openembedded-core/commit/?id=7c0e9c170db93d9af7cc505dcd71c4f3d6c4e9c5

:Detailed Notes:
Fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'libgles3-mesa-dev-native' (but virtual:native:meta-qt6/recipes-qt/qt6/qtbase_git.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'libgles3-mesa-dev-native' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libgles3-mesa-dev-native']
NOTE: Runtime target 'auto-luna-surface-manager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['auto-luna-surface-manager', 'luna-surfacemanager', 'qtbase-native', 'libgles3-mesa-dev-native']
NOTE: Runtime target 'packagegroup-webos-graphics' is unbuildable, removing...
....

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I210480f0906ca512d04d4c56c1c00bf6f6a7c18b