webos: systemd: update patches to apply on v253.1
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/551316

ERROR: QA Issue: Fuzz detected:

Applying patch 0002-Add-webos-interface.patch
patching file src/oom/com.webos.MemoryManager1.conf
patching file src/oom/meson.build
Hunk #1 succeeded at 5 with fuzz 2 (offset -3 lines).
Hunk #2 succeeded at 17 (offset -3 lines).
patching file src/oom/oomd-manager.c
patching file src/oom/oomd.c
Hunk #1 succeeded at 17 (offset 1 line).
Hunk #2 succeeded at 194 (offset 1 line).
patching file src/oom/webos-manager-bus.c
patching file src/oom/webos-manager-bus.h
patching file src/oom/webos-manager.c
patching file src/oom/webos-manager.h
patching file units/systemd-oomd.service.in

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-693] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I9d7cdc5fc8111156601b80cf739e79a5af0dbda5