webos: umediaserver=r29.* (python: fix build with python-3.13)
:Release Notes:
python-native was upgraded to 3.13 in:
https://git.openembedded.org/openembedded-core/commit/?id=0b49c9aa31279ecda565cc66b63d1d61723b37b8
now umediaserver is failing to build.

:Detailed Notes:
See https://docs.python.org/3/whatsnew/3.13.html
Remove the PyEval_ThreadsInitialized() function, deprecated in Python
3.9. Since Python 3.7, Py_Initialize() always creates the GIL: calling
PyEval_InitThreads() does nothing and PyEval_ThreadsInitialized() always
returns non-zero. (Contributed by Victor Stinner in gh-105182.)

Fixes:
http://gecko.lge.com:8000/Errors/Details/999924

TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx: In constructor 'uMediaServer::MediaPlayer::MediaPlayer()':
TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx:3369:22: error: 'PyEval_ThreadsInitialized' was not declared in this scope
 3369 |                 if (!PyEval_ThreadsInitialized())
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/umediaserver/1.0.0-gav.50/build/test/python/binding/CMakeFiles/_uMediaClient.dir/uMediaClientPYTHON_wrap.cxx:3370:43: warning: 'void PyEval_InitThreads()' is deprecated [-Wdeprecated-declarations]
 3370 |                         PyEval_InitThreads();
      |                         ~~~~~~~~~~~~~~~~~~^~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-8245] CCC: umediaserver=r29.* (python: fix build with python-3.13)
[WRR-7552] Apply provided reviews to fix build with python-3.13
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: Ia800095439dbd79ca6b3d81384de6e306240c5c1
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/453198
Reviewed-by: Ghane Simit <simit.ghane@lge.com>
Reviewed-by: Abdul Khader <abdul.khader@lge.com>
Reviewed-by: Hieu Van Nguyen <hieu2.nguyen@lge.com>
Reviewed-by: Jaekyu Lee <jaekyu.lee@lge.com>
Reviewed-by: Yangwoo Byun <yw.byun@lge.com>