webos: npmsw: use destsuffix
:Release Notes:
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

Now the node_modules end in UNPACKDIR while npm.bbclass expects it in ${S}/node_modules.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/847162

Exception: FileNotFoundError: [Errno 2] No such file or directory: 'TOPDIR/BUILD/work/x86_64-linux/enact-dev-native/6.0.4/sources-unpack/git/node_modules/@aashutoshrathi/word-wrap/package.json'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: Ib0f0134d81073640ae7903ba74a399561ddab1c6