webos: luna-surfacemanager=r67
:Release Notes:
Fix build error.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1096867

In file included from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/recipe-sysroot/usr/include/lttng/tracepoint-rcu.h:10,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/recipe-sysroot/usr/include/lttng/tracepoint.h:13,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/git/modules/weboscompositor/pmtrace_surfacemanager_provider.h:30,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/git/modules/weboscompositor/weboscompositortracer.h:22,
                 from TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/git/modules/weboscompositor/weboswindowmodel.cpp:20:
TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/recipe-sysroot/usr/include/urcu/compiler.h:205:1: error: template with C linkage
  205 | template <typename T>
      | ^~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/luna-surfacemanager/2.0.0-420/git/modules/weboscompositor/pmtrace_surfacemanager_provider.h:24:1: note: 'extern "C"' linkage started here
   24 | extern "C"{
      | ^~~~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-20814] [NANO] CCC: luna-surfacemanager=r67
[WRR-17603] Fix build with liburcu-0.15.0

Change-Id: Ie6d4c2818989eef5cc40b592b0389c71a47b9763