webos: arm-compute-library=r4 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:

http://gecko.lge.com:8000/Errors/Details/1142193

In file included from src/runtime/Allocator.cpp:25:
./arm_compute/runtime/MemoryRegion.h:105:21: error: 'uint8_t' was not declared in this scope
  105 |     std::shared_ptr<uint8_t> _mem;
      |                     ^~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I7f9e528ca47d23b9483c471af8305a968d50d34a