opkg: update patch to apply on new 0.6.1 version
:Release Notes:
Upgraded in:
https://git.openembedded.org/openembedded-core/commit/?id=037ff235fa8e369c0eac9f84cb82c9eaffba85f3

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/500723
ERROR: Applying patch '0001-Load-installed-files-before-update-file-ownership.patch' on target directory 'TOPDIR/BUILD/work/x86_64-linux/opkg-native/1_0.6.1-r0/opkg-0.6.1'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/x86_64-linux/opkg-native/1_0.6.1-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0001-Load-installed-files-before-update-file-ownership.patch
patching file libopkg/opkg_install.c
Hunk #1 succeeded at 961 (offset 14 lines).
patching file libopkg/pkg_hash.c
Hunk #1 FAILED at 906.
1 out of 1 hunk FAILED -- rejects in file libopkg/pkg_hash.c
Patch 0001-Load-installed-files-before-update-file-ownership.patch does not apply (enforce with -f)

stderr: ')

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-14883] Create GPVB with Yocto 4.2 Mickedore

Change-Id: Ic07d4ab94007c9300019fec86c75e464837be273