webruntime-repo_108.inc: set WEBOS_VERSION
:Release Notes:
With recent changes in bitbake fetcher and SRCPV handling the SRCREV
is mandatory even when it's not actively used in PV. Also set:
PREFERRED_VERSION_webruntime-clang = "94.%"
because now with PV set to 108+ it would try to build
webruntime-clang-108 which isn't available in OSE.

:Detailed Notes:
Follow changes from:
https://git.openembedded.org/bitbake/commit/?id=ae4dfa2a31c74c0c6c2b14cece822ed1f3d79723
https://git.openembedded.org/openembedded-core/commit/?id=a8e7b0f932b9ea69b3a218fca18041676c65aba0
https://git.openembedded.org/openembedded-core/commit/?id=843f82a246a535c353e08072f252d1dc78217872

Fixes:
ERROR: ExpansionError during parsing meta-webos/recipes-webos/chromium/mksnapshot-cross_108.bb
Traceback (most recent call last):
  File "bitbake/lib/bb/fetch2/__init__.py", line 1709, in Fetch.__init__(urls=['git://gpro.lge.com/webosose/chromium108;branch=master;protocol=ssh;name=main', 'file://0001-avcodec-x86-mathops-clip-constants-used-with-shift-i.patch', 'git://gpro.lge.com/webosose/chromium-v8;branch=@chromium108;protocol=ssh;destsuffix=git/src/v8;name=v8'], d=<bb.data_smart.DataSmart object at 0x7fcc4928f5d0>, cache=True, localonly=False, connection_cache=None):
                     try:
    >                    self.ud[url] = FetchData(url, d, localonly)
                     except NonLocalMethod:
  File "bitbake/lib/bb/fetch2/__init__.py", line 1338, in FetchData.__init__(url='git://gpro.lge.com/webosose/chromium108;branch=master;protocol=ssh;name=main', d=<bb.data_smart.DataSmart object at 0x7fcc4928f5d0>, localonly=False):
             if hasattr(self.method, "urldata_init"):
    >            self.method.urldata_init(self, d)

  File "bitbake/lib/bb/fetch2/git.py", line 253, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7fcc4954d450>, d=<bb.data_smart.DataSmart object at 0x7fcc4928f5d0>):

    >        ud.setup_revisions(d)

  File "bitbake/lib/bb/fetch2/__init__.py", line 1373, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7fcc4928f5d0>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)

  File "bitbake/lib/bb/fetch2/__init__.py", line 1237, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7fcc4954d450>, d=<bb.data_smart.DataSmart object at 0x7fcc4928f5d0>, name='main'):
         if srcrev == "INVALID" or not srcrev:
    >        raise FetchError("Please set a valid SRCREV for url %s (possible key names are %s, or use a ;rev=X URL parameter)" % (str(attempts), ud.url), ud.url)
         if srcrev == "AUTOINC":
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure for URL: 'git://gpro.lge.com/webosose/chromium108;branch=master;protocol=ssh;name=main'. Please set a valid SRCREV for url ['SRCREV_main:pn-mksnapshot-cross-x86_64', 'SRCREV_main', 'SRCREV:pn-mksnapshot-cross-x86_64', 'SRCREV'] (possible key names are git://gpro.lge.com/webosose/chromium108;branch=master;protocol=ssh;name=main, or use a ;rev=X URL parameter)
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above
WARNING: meta-webos/recipes-webos/chromium/webruntime-clang_108.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc
WARNING: meta-webos/recipes-webos/chromium/webruntime-clang_108.bb: Error during finalise of meta-webos/recipes-webos/chromium/webruntime-clang_108.bb
WARNING: meta-webos/recipes-webos/chromium/webruntime_108.bb: Exception during build_dependencies for fetcher_hashes_dummyfunc
WARNING: meta-webos/recipes-webos/chromium/webruntime_108.bb: Error during finalise of meta-webos/recipes-webos/chromium/webruntime_108.bb

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield
[WRP-26053] CCC: Various build fixes

Change-Id: If93659d80d2830fbe6fc51706796bbb99ef65114