webos: openssl: drop 0472-Fix-a-mem-leak-when-the-FIPS-provider-is-used-in-a-d.patch
:Release Notes:
Upstream-Status says:
openssl-3.2.0-alpha2 be203ea3d3a60a881993d1f7552084996d34ba0a
but it was also backported to 3.1.4 in:
https://github.com/openssl/openssl/commit/6b3f7f0b28afc3e25ce505e5fde2d9f2b50cdb9e
so we can drop it now.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/922593

ERROR: Applying patch '0472-Fix-a-mem-leak-when-the-FIPS-provider-is-used-in-a-d.patch' on target directory 'TOPDIR/BUILD/work/qemux86_64-webos-linux/openssl/3.1.4-r0/openssl-3.1.4'
CmdError('quilt --quiltrc TOPDIR/BUILD/work/qemux86_64-webos-linux/openssl/3.1.4-r0/recipe-sysroot-native/etc/quiltrc push', 0, 'stdout: Applying patch 0472-Fix-a-mem-leak-when-the-FIPS-provider-is-used-in-a-d.patch
patching file crypto/initthread.c
Hunk #1 FAILED at 248.
Hunk #2 succeeded at 273 with fuzz 2 (offset 7 lines).
Hunk #3 FAILED at 395.
2 out of 3 hunks FAILED -- rejects in file crypto/initthread.c
patching file include/crypto/cryptlib.h
patching file providers/fips/fipsprov.c
Hunk #1 succeeded at 699 with fuzz 2 (offset 26 lines).
Patch 0472-Fix-a-mem-leak-when-the-FIPS-provider-is-used-in-a-d.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2118] Create GPVB with Yocto 4.2 Mickledore

Change-Id: I0cc26ad53b746b0da802a71536ba211d68f0cd62