webos: webos.inc: clang: disable return-type Werror
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1186664
work-shared/llvm-project-source-20.1.3-r0/llvm-project-20.1.3.src/lldb/source/DataFormatters/TypeSummary.cpp: In member function 'virtual std::string lldb_private::TypeSummaryImpl::GetSummaryKindName()':
work-shared/llvm-project-source-20.1.3-r0/llvm-project-20.1.3.src/lldb/source/DataFormatters/TypeSummary.cpp:62:1: error: control reaches end of non-void function [-Werror=return-type]
   62 | }
      | ^
cc1plus: some warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2749] Create GPVB with Yocto 5.3 Whinlatter

Change-Id: I7709d5df463f026ec04906a38136ecfe614d50e0