webos: tensorflow-lite=r12 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:

http://gecko.lge.com:8000/Errors/Details/1142262

FAILED: tools/benchmark/CMakeFiles/benchmark_model.dir/__/__/profiling/profile_summary_formatter.cc.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++ --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot -DEIGEN_MPL2_ONLY -DNOMINMAX=1 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git/tensorflow/lite/schema -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/eigen -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/neon2sse -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/farmhash/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/flatbuffers/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/gemmlowp/public -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/gemmlowp -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build/ruy -mbranch-protection=standard -fstack-protector-all  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -funwind-tables  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git=/usr/src/debug/benchmark-model/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git=/usr/src/debug/benchmark-model/2.9.3  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build=/usr/src/debug/benchmark-model/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/build=/usr/src/debug/benchmark-model/2.9.3  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot-native=  -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden  -flax-vector-conversions -DNDEBUG -std=c++17 -fPIE -DTFLITE_BUILD_WITH_XNNPACK_DELEGATE -DTFL_STATIC_LIBRARY_BUILD -pthread -MD -MT tools/benchmark/CMakeFiles/benchmark_model.dir/__/__/profiling/profile_summary_formatter.cc.o -MF tools/benchmark/CMakeFiles/benchmark_model.dir/__/__/profiling/profile_summary_formatter.cc.o.d -o tools/benchmark/CMakeFiles/benchmark_model.dir/__/__/profiling/profile_summary_formatter.cc.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git/tensorflow/lite/profiling/profile_summary_formatter.cc
In file included from TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git/tensorflow/lite/profiling/profile_summary_formatter.cc:16:
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/benchmark-model/2.9.3/git/tensorflow/lite/profiling/profile_summary_formatter.h:38:22: error: 'uint32_t' was not declared in this scope
   38 |       const std::map<uint32_t, std::unique_ptr<tensorflow::StatsCalculator>>&
      |                      ^~~~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I02e58be608850fc9035384627781bee1f688935b