qtgrpc: backport fixes for build with newer protobuf and gcc-13
:Release Notes:
Backport 2 commits from newer qtgrpc to fix build.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/723535

FAILED: src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/clientdeclarationprinter.cpp.o
TOPDIR/BUILD/hosttools/g++ -DPROTOBUF_USE_DLLS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_NO_AS_CONST=1 -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/build/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/lib/mkspecs/linux-g++ -isystemTOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -O2 -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -pthread -Wsuggest-override -MD -MT src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/clientdeclarationprinter.cpp.o -MF src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/clientdeclarationprinter.cpp.o.d -o src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/clientdeclarationprinter.cpp.o -c TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/clientdeclarationprinter.cpp
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/clientdeclarationprinter.cpp:11:10: fatal error: google/protobuf/stubs/logging.h: No such file or directory
   11 | #include <google/protobuf/stubs/logging.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

TOPDIR/BUILD/hosttools/g++ -DPROTOBUF_USE_DLLS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_NO_AS_CONST=1 -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/build/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/lib/mkspecs/linux-g++ -isystemTOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -O2 -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -pthread -Wsuggest-override -MD -MT src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/qgrpcgenerator.cpp.o -MF src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/qgrpcgenerator.cpp.o.d -o src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/qgrpcgenerator.cpp.o -c TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/qgrpcgenerator.cpp
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/qgrpcgenerator.cpp:15:10: fatal error: google/protobuf/stubs/logging.h: No such file or directory
   15 | #include <google/protobuf/stubs/logging.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

TOPDIR/BUILD/hosttools/g++ -DPROTOBUF_USE_DLLS -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon -isystemTOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -O2 -std=gnu++17 -fPIC -Wall -Wextra -pthread -MD -MT src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o -MF src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o.d -o src/tools/qtprotoccommon/CMakeFiles/QtProtocCommon.dir/generatorbase.cpp.o -c TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon/generatorbase.cpp
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon/generatorbase.cpp:8:10: fatal error: google/protobuf/stubs/logging.h: No such file or directory
    8 | #include <google/protobuf/stubs/logging.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

FAILED: src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/main.cpp.o
TOPDIR/BUILD/hosttools/g++ -DPROTOBUF_USE_DLLS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_NO_AS_CONST=1 -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/build/src/tools/qtgrpcgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/lib/mkspecs/linux-g++ -isystemTOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -O2 -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -pthread -Wsuggest-override -MD -MT src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/main.cpp.o -MF src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/main.cpp.o.d -o src/tools/qtgrpcgen/CMakeFiles/qtgrpcgen.dir/main.cpp.o -c TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/main.cpp
In file included from TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/main.cpp:6:
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/qgrpcgenerator.h:40:17: error: âsetâ in namespace âstdâ does not name a template type
   40 |     static std::set<std::string> GetInternalIncludes(
      |                 ^~~
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtgrpcgen/qgrpcgenerator.h:9:1: note: âstd::setâ is defined in header â<set>â; did you forget to â#include <set>â?
    8 | #include "generatorbase.h"
  +++ |+#include <set>
    9 |

http://gecko.lge.com:8000/Errors/Details/724403

FAILED: src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o
TOPDIR/BUILD/hosttools/g++ -DPROTOBUF_USE_DLLS -DQT_DISABLE_DEPRECATED_UP_TO=0x050000 -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_NO_AS_CONST=1 -DQT_NO_DEBUG -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_USE_QSTRINGBUILDER -DQT_WARN_DEPRECATED_UP_TO=0x070000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotobufgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/build/src/tools/qtprotobufgen -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotoccommon -ITOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/lib/mkspecs/linux-g++ -isystemTOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/recipe-sysroot-native/usr/include -O2 -pipe -DNDEBUG -O2 -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -fno-exceptions -Wsuggest-override -fcf-protection=full -MD -MT src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o -MF src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o.d -o src/tools/qtprotobufgen/CMakeFiles/qtprotobufgen.dir/qprotobufgenerator.cpp.o -c TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotobufgen/qprotobufgenerator.cpp
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotobufgen/qprotobufgenerator.cpp: In member function âvirtual bool QtProtobuf::QProtobufGenerator::Generate(const google::protobuf::FileDescriptor*, const std::string&, google::protobuf::compiler::GeneratorContext*, std::string*) constâ:
TOPDIR/BUILD/work/x86_64-linux/qtgrpc-native/6.5.2/git/src/tools/qtprotobufgen/qprotobufgenerator.cpp:42:21: error: âgoogle::protobuf::FileDescriptor::Syntax google::protobuf::FileDescriptor::syntax() constâ is private within this context
   42 |     if (file->syntax() != FileDescriptor::SYNTAX_PROTO3) {
      |         ~~~~~~~~~~~~^~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: Ieda2bf3e87d8e87db6376fcdcad3eadd2b973df9