webos: polkit: use refreshed 0004-Make-netgroup-support-optional.patch
:Release Notes:
Use refreshed
0004-Make-netgroup-support-optional.patch to avoid patch-fuzz
it's fixed in kirkstone:
https://git.openembedded.org/meta-openembedded/commit/?h=kirkstone&id=0b0086ca9acc1a5dc682c93217b9f8996214ae4c
but not in langdale

:Detailed Notes:
Fixes:
ERROR: polkit-0.119-r0 do_patch: Fuzz detected:

Applying patch 0004-Make-netgroup-support-optional.patch
patching file configure.ac
Hunk #1 succeeded at 117 with fuzz 2 (offset 17 lines).
patching file meson.build
patching file src/polkit/polkitidentity.c
patching file src/polkit/polkitunixnetgroup.c
patching file src/polkitbackend/polkitbackendinteractiveauthority.c
patching file src/polkitbackend/polkitbackendjsauthority.cpp
Hunk #1 succeeded at 1291 (offset -233 lines).
Hunk #2 succeeded at 1306 (offset -233 lines).
patching file test/polkit/polkitidentitytest.c
patching file test/polkit/polkitunixnetgrouptest.c
patching file test/polkitbackend/test-polkitbackendjsauthority.c

The context lines in the patches can be updated with devtool:

    devtool modify polkit
    devtool finish --force-patch-refresh polkit <layer_path>

Don't forget to review changes done by devtool!

ERROR: polkit-0.119-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2115] Create GPVB with Yocto 4.1 Langdale

Change-Id: Id7e2448aa2b24b0af3b4bd7e9059bad172207e93