webos: wireguard-tools=webos2 (respect VIRTUAL-RUNTIME_bash in PACKAGECONFIG)
:Release Notes:
After:
https://git.openembedded.org/meta-openembedded/commit/?id=865411fbde1f3489e77ad186e669b5c315485ce1
this fails again with:
ERROR: QA Issue: lib32-wireguard-tools rdepends on lib32-bash, but it isn't a build dependency, missing lib32-bash in DEPENDS or PACKAGECONFIG? [build-deps]
in multilib builds.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/730044

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-29491] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I3a7474b5ec51d46ae243e5543e13ce1e9522d71a