ose: com.webos.app.camera: enable openssl-legacy-provider in nodejs
:Release Notes:

:Detailed Notes:
Works around issues with openssl-3 until webpack is updated
to some supported hash function.

Unfortunately this is another example where the errors in do_install
aren't fatal and only hint that something is wrong was:
WARNING: com.webos.app.camera-0.0.1-8-r0
  do_convert_webos_preferred_gfx_image_format:
  Could not find com.webos.app.camera:appinfo.json,
  no conversion will be performed

But the issue is actually caused by do_install:

grep Error: BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/temp/log.do_install
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported

10%  building 1/2 modules  src/index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:417:16)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:452:10
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/webpack/lib/NormalModule.js:323:13
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /OE/lge/build/webos/kirkstone/BUILD/work/qemux86_64-webos-linux/com.webos.app.camera/0.0.1-8-r0/recipe-sysroot-native/opt/cli-legacy/node_modules/eslint-loader/dist/cacheLoader.js:48:12

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: I2c4a7c88c9316d4b6b6e26c9d719de6c7bae9f50