webos: systemd=webos17 (drop cgroupv2 PACKAGECONFIG)
:Release Notes:
The 'cgroupv2' PACKAGECONFIG is dropped as systemd now only supports
cgroupv2 since 256 upgrade in:
https://git.openembedded.org/openembedded-core/commit/?id=89b75b46371d5e9172cb496b461824d8551a2af5

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/893030
ERROR: QA Issue: systemd: invalid PACKAGECONFIG: cgroupv2 [invalid-packageconfig]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-17959] Create GPVB with Yocto 5.1 Styhead

Change-Id: I3f43532c94153d4911c4262c7fed5d7f837bfd18