webos: packagegroup-webos-minimal=r5 packagegroup-webos-graphics=r4
:Release Notes:
Keep the minimal really minimal, by moving:
fontconfig-utils
VIRTUAL-RUNTIME_webos-ime
VIRTUAL-RUNTIME_browser_fonts
to packagegroup-webos-graphics as we probably don't need browser_fonts
and fontconfig-utils without webappmanager which is already pulled only
by packagegroup-webos-graphics and imemanager also depends on opengl
or vulkan in DISTRO_FEATURES.

:Detailed Notes:
Don't include packagegroup-webos-graphics in
packagegroup-webos-minimal as the webos_image will include
it when DISTRO_FEATURES allow:
meta-webos/classes/webos_image.bbclass:
  ${@bb.utils.contains_any('DISTRO_FEATURES', 'webos-graphics webos-graphics-extended', 'packagegroup-webos-graphics', '', d)} \

ERROR: Nothing RPROVIDES 'imemanager' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-minimal.bb
  RDEPENDS on or otherwise requires it)
imemanager was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'imemanager' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['imemanager']
ERROR: Nothing RPROVIDES 'packagegroup-webos-minimal' (but
  meta-webos/recipes-core/packagegroups/packagegroup-webos-minimal.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'packagegroup-webos-minimal'
NOTE: Runtime target 'packagegroup-webos-minimal' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-webos-minimal']
ERROR: Nothing PROVIDES 'virtual/webruntime' (but
  meta-webos/recipes-webos/wam/wam-clang.bb DEPENDS on or otherwise requires it)
webruntime-clang PROVIDES virtual/webruntime but was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
webruntime PROVIDES virtual/webruntime but was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
webruntime PROVIDES virtual/webruntime but was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
webruntime-clang PROVIDES virtual/webruntime but was skipped: one of 'opengl vulkan' needs to be in DISTRO_FEATURES
NOTE: Runtime target 'wam-clang' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wam-clang', 'virtual/webruntime']
ERROR: Nothing RPROVIDES 'wam-clang-dev' (but
  meta-webos/recipes-webos/wam/wam-clang.bb
  RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'wam-clang-dev'
NOTE: Runtime target 'wam-clang-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['wam-clang-dev']

:Testing Performed:
Build test done.

:QA Notes:
N/A

:Issues Addressed:
[WRQ-22410] CCC: packagegroup-webos-minimal=r5 packagegroup-webos-graphics=r4
[WRQ-7027] ...
[WRQ-8249] ...
[WRQ-7034] ...
[WRQ-17413] ...

Change-Id: I4363976740b2d4f983fb5aa78c0e16596efc3c37