webos.inc: use new oe.buildcfg module
:Release Notes:
old functions were removed in:
https://git.openembedded.org/openembedded-core/commit/?id=439cdf8a1e52fd2c4dc81dc40ce7e6af282ce7ac

:Detailed Notes:
Fixes:
arsing recipes...WARNING: /OE/lge/build/webos/langdale/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_94.bb: Exception during build_dependencies for do_exportbuildscript
ERROR: ExpansionError during parsing /OE/lge/build/webos/langdale/meta-lg-webos/meta-webos/recipes-webos/chromium/webruntime_94.bb
Traceback (most recent call last):
  File "Var <WEBOS_DISTRO_TOPDIR_REVISION>", line 1, in <module>
bb.data_smart.ExpansionError: Failure expanding variable WEBOS_DISTRO_TOPDIR_REVISION, expression was ${@base_get_metadata_git_revision('/OE/lge/build/webos/langdale', None).strip()} which triggered exception NameError: name 'base_get_metadata_git_revision' is not defined
The variable dependency chain for the failure is: WEBOS_DISTRO_TOPDIR_REVISION -> do_exportbuildscript

ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRO-4709] Create GPVB with Yocto 4.1 Langdale