webos: googletest-clang: rename to match googletest recipe name from meta-oe
:Release Notes:
require doesn't support any wildcards in filename so we need
to require the matching one and it was recently renamed from
_1.13.0.bb to _1.14.0.bb.

:Detailed Notes:
Fixes parsing error:

  ERROR: ParseError at meta-webos/recipes-test/googletest/googletest-clang_1.13.0.bb:5:
  Could not include required file recipes-test/googletest/googletest_1.13.0.bb
  ERROR: Parsing halted due to errors, see error messages above

after:
https://git.openembedded.org/meta-openembedded/commit/?id=bdeb3ecf73e8994ac90e30d1f032f45580640871

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I527cf9725d7da115ab2a01eae852609d146674f6