packagegroup-webos-extended: define VIRTUAL-RUNTIME_bluetooth_service/VIRTUAL-RUNTIME_com.webos.app.browser before use
:Release Notes:
Every VIRTUAL-RUNTIME* needs to have some default value before
being used.

:Detailed Notes:
Fixes parsing with yocto-check-layer:

NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for initscripts (initscripts, webos-initscripts)
Consider defining a PREFERRED_PROVIDER entry to match initscripts
ERROR: Nothing RPROVIDES ''${VIRTUAL-RUNTIME_bluetooth_service}',' (but /OE/meta-webosose/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target ''${VIRTUAL-RUNTIME_bluetooth_service}',' is unbuildable, removing...
Missing or unbuildable dependency chain was: ["'${VIRTUAL-RUNTIME_bluetooth_service}',"]
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-webos-extended', "'${VIRTUAL-RUNTIME_bluetooth_service}',"]

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

WARNING: No bb files in default matched BBFILE_PATTERN_meta-qt5-compat '^/OE/meta-webosose/meta-qt5-compat/'
NOTE: Resolving any missing task queue dependencies
NOTE: Multiple providers are available for initscripts (initscripts, webos-initscripts)
Consider defining a PREFERRED_PROVIDER entry to match initscripts
ERROR: Nothing RPROVIDES '${VIRTUAL-RUNTIME_com.webos.app.browser}' (but /OE/meta-webosose/meta-webos/recipes-core/packagegroups/packagegroup-webos-extended.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${VIRTUAL-RUNTIME_com.webos.app.browser}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${VIRTUAL-RUNTIME_com.webos.app.browser}']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'packagegroup-webos-extended', '${VIRTUAL-RUNTIME_com.webos.app.browser}']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122674] CCC: build fixes for host-user-contaminated QA issues

Change-Id: Ie8bdc32e176502957d499c89d331be86b0f1942a