webos-backports-4.3: opengl-es-cts: Fix dependencies for multilib builds
:Release Notes:
Backport changes from:
https://lists.openembedded.org/g/openembedded-devel/message/104699

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/685074
ERROR: QA Issue: lib32-opengl-es-cts package lib32-opengl-es-cts-dev - suspicious values 'wayland-dev wayland-protocols-dev' in RRECOMMENDS [multilib]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-20118] Bitbake world issues 2023-07
[WRP-26053] CCC: Various build fixes

Change-Id: I3c1488c5f466c68db526c94f3db0406afcac7a35