webos: nodejs-module-usocket: upgrade nan dependency to latest 2.22.0
:Release Notes:
Fixes build with nodejs-22 from meta-oe.

:Detailed Notes:
https://github.com/nodejs/nan/commit/6bd62c9a0004339d5d1e18a945c84929d0f6b808
fixes:
http://gecko.lge.com:8000/Errors/Details/1008012

npm error ../node_modules/nan/nan.h: In function 'void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, GetterCallback, SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
npm error ../node_modules/nan/nan.h:2594:19: error: no matching function for call to 'v8::ObjectTemplate::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)'
npm error  2594 |   tpl->SetAccessor(
npm error       |   ~~~~~~~~~~~~~~~~^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I4c48a78ad69312526381081029d8abd2d54dda88