node-gyp-packages-native: use BPN instead of PN in SRC_URI
:Release Notes:
Fixes:
ERROR: node-gyp-packages-native-0.12.2-r0 do_unpack: QA Issue: node-gyp-packages-native: SRC_URI uses PN not BPN [src-uri-bad]

:Detailed Notes:
For other node-gyp-native fixes see:
https://github.com/webOS-ports/meta-webos-ports/commit/812672d4e513eccf0650a2f45a081e742e5e3e38
https://github.com/webOS-ports/meta-webos-ports/commit/29f569b41355ab533a97c27474f7a47037ca0249
https://github.com/webOS-ports/meta-webos-ports/commit/1c72a66d1b87007ba5b188b5ecdb27545d3af2ac
https://github.com/webOS-ports/meta-webos-ports/commit/7a2120372bdaaba14b3f1fc37101bddb92072b2e
https://github.com/webOS-ports/meta-webos-ports/commit/3af337e20a9ee5e53b645d22bbe98048798888cf
https://github.com/webOS-ports/meta-webos-ports/commit/094121841eb79612e2a7b793eb63acfc978fdbef
and
https://github.com/webOS-ports/meta-webos-ports/pull/465

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRN-9458] NPM registry should be accessed over https now
[WRN-9820] Create GPVB with Yocto 3.5 Kirkstone

Change-Id: If4c819d628fa9cb382ce682f160c1820508384d5