webos: webos.inc: disable return-type Werror for python3-fastnumbers
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/749006

src/cpp/parser.cpp: In member function 'virtual NumberFlags CharacterParser::get_number_type() const':
src/cpp/parser.cpp:463:1: error: control reaches end of non-void function [-Werror=return-type]
  463 | }
      | ^
cc1plus: some warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I37da2f7ca604fb70684553d42ac3555be7a41891