webos: qtwayland-webos=r24
:Release Notes:
Fix build error

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1095224

compiling qwayland-qt-key-unstable-v1.cpp
In file included from TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/recipe-sysroot/usr/include/lttng/tracepoint-rcu.h:10,
                 from TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/recipe-sysroot/usr/include/lttng/tracepoint.h:13,
                 from TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/git/src/client/pmtrace_qtwaylandclient_provider.h:28,
                 from TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/git/src/client/qtwaylandclienttracer.h:14,
                 from TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/git/src/hardwareintegration/client/wayland-egl/qwaylandglcontext.cpp:49:
TOPDIR/BUILD/work/o22-webos-linux/qtwayland/5.12.4-174/recipe-sysroot/usr/include/urcu/compiler.h:205:1: error: template with C linkage
  205 | template <typename T>

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-20814] [NANO] CCC: qtwayland-webos=r24
[WRR-17603] Fix build with liburcu-0.15.0

Change-Id: Id3882978825f46e89b5500fa253b4583fa8d8dec