qemu: Revert "qemu/osdep: Remove fallback for MAP_FIXED_NOREPLACE"
:Release Notes:
This reverts commit c42e77a90d9244c8caf76fe0e54f84200430a4e1.
For qemu-8.1 we need newer libc than 2.27 used in ubuntu-18.04 to
support MAP_FIXED_NOREPLACE after qemu removed fallback for it in:
https://github.com/qemu/qemu/commit/c42e77a90d9244c8caf76fe0e54f84200430a4e1
but after switching from buildtools to buildtools-extended which
include gcc and libc the gdk-pixbuf-native started to fail.

:Detailed Notes:
gdk-pixbuf-native issue can be avoided by patching glib-2.0 not to
use close_range even with newer glib as shown in:
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/370231 glib-2.0-native: gspawn: avoid close_range

But that's not all there are more failures caused by buildtools-extended
in our multilib builds (because buildtools-extended doesn't include
lib32-glibc and some of our components pass -m32 in native builds e.g.:

1) lib32-ntllib-11.5.1-r0 do_compile
   meta-webos-pro/recipes-webos/ntllib/ntllib_11.5.1.bb
   HOST_CXX_append = "${@ '' if '${TARGET_ARCH}' == 'aarch64' or '${TARGET_ARCH}' == 'x86_64' else '-m32'}"

   causing http://gecko.lge.com:8000/Errors/Details/690072

   TOPDIR/buildtools-4.2.3/sysroots/x86_64-pokysdk-linux/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~

2) lib32-luajit-2.1.0~beta3-220721-r0 do_compile
   http://gecko.lge.com:8000/Errors/Details/690073

   TOPDIR/buildtools-4.2.3/sysroots/x86_64-pokysdk-linux/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
    7 | # include <gnu/stubs-32.h>
      |           ^~~~~~~~~~~~~~~~

So it might be better to get back to revert qemu commit to remove fallback
and continue to use regular buildtools until SWP infra is updated to
supported OS.

Also need MAP_SHARED_VALIDATE in syscall.c since v8.1.0-rc3

libc defines it in mman.h:
linux-headers/linux/mman.h:#define MAP_SHARED_VALIDATE 0x03     /* share + validate extension flags */
and for non-linux systems there is fallback in mmap-alloc.c:
util/mmap-alloc.c:#define MAP_SHARED_VALIDATE   0x0
but since:
https://github.com/qemu/qemu/commit/9ab8d0714964abce6f5b8bcac49d6239c548ed12
it's also used in syscall.c for systems with old linux-libc-headers
as this was added with 4.15.

It's a bit weird because even ubuntu 18.04 has:
ii  linux-libc-dev:amd64                                  4.15.0-167.175

and it is defined in there (on the 18.04 docker container where it was failing to build):
enkins@LGEACJS03P:~$ grep -R MAP_SHARED_VALIDATE /usr/include/
/usr/include/asm-generic/mman-common.h:#define MAP_SHARED_VALIDATE 0x03	/* share + validate extension flags *

Fixes:
http://gecko.lge.com:8000/Errors/Details/690250

FAILED: libqemu-arm-linux-user.fa.p/linux-user_syscall.c.o
gcc -m64 -mcx16 -Ilibqemu-arm-linux-user.fa.p -I. -I../qemu-8.1.0 -Itarget/arm -I../qemu-8.1.0/target/arm -I../qemu-8.1.0/common-user/host/x86_64 -I../qemu-8.1.0/linux-user/include/host/x86_64 -I../qemu-8.1.0/linux-user/include -Ilinux-user -I../qemu-8.1.0/linux-user -Ilinux-user/arm -I../qemu-8.1.0/linux-user/arm -Iqapi -Itrace -Iui/shader -ITOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include -ITOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/include/glib-2.0 -ITOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/recipe-sysroot-native/usr/lib/pkgconfig/../../../usr/lib/glib-2.0/include -fdiagnostics-color=auto -Wall -Winvalid-pch -std=gnu11 -O2 -g -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Wundef -Wwrite-strings -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wold-style-declaration -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=2 -Wmissing-format-attribute -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -isystem TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0/linux-headers -isystem linux-headers -iquote . -iquote TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0 -iquote TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0/include -iquote TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0/host/include/x86_64 -iquote TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0/host/include/generic -iquote TOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/qemu-8.1.0/tcg/i386 -pthread -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -O2 -pipe -isystemTOPDIR/BUILD/work/x86_64-linux/qemu-native/8.1.0/recipe-sysroot-native/usr/include -O2 -fPIE -isystem../qemu-8.1.0/linux-headers -isystemlinux-headers -DNEED_CPU_H '-DCONFIG_TARGET="arm-linux-user-config-target.h"' '-DCONFIG_DEVICES="arm-linux-user-config-devices.h"' -MD -MQ libqemu-arm-linux-user.fa.p/linux-user_syscall.c.o -MF libqemu-arm-linux-user.fa.p/linux-user_syscall.c.o.d -o libqemu-arm-linux-user.fa.p/linux-user_syscall.c.o -c ../qemu-8.1.0/linux-user/syscall.c
../qemu-8.1.0/linux-user/syscall.c: In function âdo_mmapâ:
../qemu-8.1.0/linux-user/syscall.c:6066:22: error: âMAP_SHARED_VALIDATEâ undeclared (first use in this function); did you mean âTARGET_MAP_SHARED_VALIDATEâ?
 6066 |         host_flags = MAP_SHARED_VALIDATE;
      |                      ^~~~~~~~~~~~~~~~~~~
      |                      TARGET_MAP_SHARED_VALIDATE

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I6e0745c57f1dd3ced2bc83ba18cae898bac7c688