webos-recipe-blacklist.inc: blacklist cargo because of libssh2
:Release Notes:
Fix issues detected by yocto-check-layer.
ceph depends on already blacklisted xfsprogs.

:Detailed Notes:
ERROR: Nothing PROVIDES 'libssh2' (but meta-rust/recipes-devtools/cargo/cargo_1.43.0.bb DEPENDS on or otherwise requires it)
libssh2 was skipped: Recipe is blacklisted: Depends on blacklisted man-db since https://git.openembedded.org/meta-openembedded/commit/?id=b3e9b51c9ba58b01e55c5b0a9a9bec3f7f06d07a
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'cargo', 'libssh2']

:Testing Performed:
Build test done
CAT was passed

:QA Notes:
N/A

:Issues Addressed:
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth

Change-Id: Id6b6d3edac643009f2dd770adeada8c1ba43c010