webos: jsoncpp-clang: rename to match new recipe version
:Release Notes:
Updated in:
https://git.openembedded.org/meta-openembedded/commit/?id=f556659ec36275eca15bf4999e5daa7c5a44452e

:Detailed Notes:
Fixes:
ERROR: ParseError at meta-webos/recipes-devtools/jsoncpp/jsoncpp-clang_1.9.5.bb:3: Could not include required file recipes-devtools/jsoncpp/jsoncpp_1.9.5.bb
ERROR: Parsing halted due to errors, see error messages above

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-2120] Create GPVB with Yocto 5.1 Styhead

Change-Id: Id974cb62ff3bf921f2832835bd4c5bf4d646aca3