{build-325} connman=webos15 (refresh patches to apply on 1.39 version)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/116853

ERROR: Command Error: 'quilt --quiltrc TOPDIR/BUILD/work/raspberrypi3_64-webos-linux/connman/1.39-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
stdout: Applying patch 0001-Add-support-for-the-WPS-PBS-and-PIN-mode.patch
patching file gsupplicant/gsupplicant.h
patching file gsupplicant/supplicant.c
patching file include/device.h
patching file include/technology.h
patching file plugins/wifi.c
Hunk #2 succeeded at 83 (offset 2 lines).
Hunk #3 succeeded at 168 with fuzz 1 (offset 2 lines).
Hunk #4 succeeded at 224 (offset 7 lines).
Hunk #5 succeeded at 812 (offset 8 lines).
Hunk #6 succeeded at 2080 (offset 28 lines).
Hunk #7 succeeded at 2302 (offset 28 lines).
Hunk #8 succeeded at 2328 (offset 28 lines).
Hunk #9 succeeded at 2358 (offset 28 lines).
Hunk #10 succeeded at 2479 (offset 28 lines).
Hunk #11 succeeded at 2536 (offset 40 lines).
Hunk #12 FAILED at 2634.
Hunk #13 succeeded at 2756 (offset 54 lines).
Hunk #14 succeeded at 2822 (offset 54 lines).
Hunk #15 succeeded at 2859 (offset 54 lines).
Hunk #16 succeeded at 2887 (offset 54 lines).
Hunk #17 succeeded at 2897 (offset 54 lines).
Hunk #18 succeeded at 2906 (offset 54 lines).
Hunk #19 succeeded at 2952 (offset 51 lines).
Hunk #20 succeeded at 3633 (offset 51 lines).
1 out of 20 hunks FAILED -- rejects in file plugins/wifi.c
patching file src/connman.h
Hunk #1 succeeded at 573 (offset 7 lines).
patching file src/device.c
patching file src/service.c
patching file src/technology.c
Hunk #1 succeeded at 1099 (offset 5 lines).
Hunk #2 succeeded at 1151 (offset 5 lines).
Patch 0001-Add-support-for-the-WPS-PBS-and-PIN-mode.patch does not apply (enforce with -f)

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-122546] Create GPVB with Yocto 3.2 Gatesgarth
[PLAT-137851] CCC: connman=v1.39

Change-Id: I846bed5c386a0f8a5ebcd6453c0fa85f9f7dd4e2