webos: layer.conf: BBMASK old python3-watchdog from meta-qt6
:Release Notes:
It's not compatible with python 3.12 while meta-oe has recent version
which is compatible.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/763893

DEBUG: Executing shell function do_compile
Traceback (most recent call last):
  File "TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/python3-watchdog/0.9.0/watchdog-0.9.0/setup.py", line 20, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
ERROR: 'python3 setup.py bdist_wheel ' execution failed.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-504] Create GPVB with Yocto 5.0 Scarthgap

Change-Id: I2c926219c487a9ca9434f3edb392592181534989