webos: armnn=r4 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:

http://gecko.lge.com:8000/Errors/Details/1144153
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/armnn/22.08/git/profiling/common/include/Packet.hpp:29:20: error: expected ')' before 'header'
   29 |     Packet(uint32_t header)
      |           ~        ^~~~~~~
      |                    )
...

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[GBW-2612] [NANO] CCC: Yocto 5.0 Scarthgap
[GBW-2601] Fix build with gcc-15 and clang-20
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I55d75882b1b07b9ae120564f5a594f66b644ac6b