webos: libspdm spdm-utils: lower SECURITY_STACK_PROTECTOR from all to strong
:Release Notes:
spdm-utils fails with -fstack-protector-all from:
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/426367
which changed it from default (from security_flags.inc)
-fstack-protector-strong to -fstack-protector-all.

:Detailed Notes:
Avoid the build failure:
http://gecko.lge.com:8000/Errors/Details/1124671
note: gcc/aarch64-webos-linux/14.2.0/ld: spdm-utils/0.7.2/recipe-sysroot/usr/lib/libmemlib.a(zero_mem.c.o): undefined reference to symbol '__stack_chk_guard@@GLIBC_2.17'
      gcc/aarch64-webos-linux/14.2.0/ld: spdm-utils/0.7.2/recipe-sysroot/usr/lib/ld-linux-aarch64.so.1: error adding symbols: DSO missing from command line
is is caused by:
meta-webos/conf/distro/include/webos.inc:SECURITY_STACK_PROTECTOR = "-fstack-protector-all"

Still fails with newer version http://gecko.lge.com:8000/Errors/Details/1165819

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I7d5c931a078a75f43e1ab720093ab2d96ad69d99