webos: glib-2.0: update work around for QA issues
:Release Notes:
Another locale was added in:
https://git.openembedded.org/openembedded-core/commit/?id=e9b318408bd6e68e4d7f7d4f74abf6d55f2dae09

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/1136278

ERROR: QA Issue: glib-2.0-ptest rdepends on locale-base-c, but it isn't a build dependency? [build-deps]

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar

Change-Id: I89e130f51f31ff6d9d26247ea97b7c5a429921a4