leveldb-tl=r4 (fix build with gcc-13)
:Release Notes:

:Detailed Notes:
Fixes:
http://gecko.lge.com/Errors/Details/529425

FAILED: test/CMakeFiles/all-tests.dir/simple.cpp.o
TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++  -ITOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git/include -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot/usr/src/gtest/include -isystem TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot/usr/src/gtest -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git=/usr/src/debug/leveldb-tl/0.1.6-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git=/usr/src/debug/leveldb-tl/0.1.6-r3  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/build=/usr/src/debug/leveldb-tl/0.1.6-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/build=/usr/src/debug/leveldb-tl/0.1.6-r3  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot=  -fmacro-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot=  -fdebug-prefix-map=TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++0x -Wall -Wextra -Wconversion -Werror -pthread -MD -MT test/CMakeFiles/all-tests.dir/simple.cpp.o -MF test/CMakeFiles/all-tests.dir/simple.cpp.o.d -o test/CMakeFiles/all-tests.dir/simple.cpp.o -c TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git/test/simple.cpp
TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git/test/simple.cpp: In member function 'virtual void Simple_sandwich_move_issue14_Test::TestBody()':
TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git/test/simple.cpp:353:24: error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
  353 |     auto db = std::move(leveldb::SandwichDB<leveldb::MemoryDB> {});
      |               ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TOPDIR/BUILD/work/qemux86_64-webos-linux/leveldb-tl/0.1.6-r3/git/test/simple.cpp:353:24: note: remove 'std::move' call
cc1plus: all warnings being treated as errors

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-8053] CCC: Various build fixes

Change-Id: Iae8550514bc073b96e9560610d95c096d4f2f2f5
Reviewed-on: http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/344546
Reviewed-by: Multi Layer Checker <multi_layer@lge.com>
Reviewed-by: Hyunjae Shin <hyunjae92.shin@lgepartner.com>
Tested-by: Hyunjae Shin <hyunjae92.shin@lgepartner.com>