webos: com.webos.service.location=r6 (fix build with gcc-15)
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:

FAILED: CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o
/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-g++ --sysroot=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot -DUSE_PMLOG_DECLARATION -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git=/usr/src/debug/com.webos.service.location/1.0.0-105  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/build=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/build=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot=  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot=  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native=  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native=  -pipe -fvisibility-inlines-hidden -Wall -std=c++11 -DNDEBUG   -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -pthread -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/libmount -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/blkid -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -pthread -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/json-c -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/libxml2 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/loc-utils -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -MD -MT CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o -MF CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o.d -o CMakeFiles/location.dir/src/handler/lbs/geoservices/MapServicesImpl.cpp.o -c /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/src/handler/lbs/geoservices/MapServicesImpl.cpp
In file included from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/MapServicesInterface.h:25,
                 from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/MapServicesImpl.h:28,
                 from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/src/handler/lbs/geoservices/MapServicesImpl.cpp:18:
/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/location_errors.h:25:9: error: 'uint32_t' does not name a type
   25 | typedef uint32_t LocationError_t;
      |         ^~~~~~~~
/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/location_errors.h:1:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
  +++ |+#include <cstdint>
    1 | // Copyright (c) 2020 LG Electronics, Inc.

cannot use cstdint because the same header file is also used from GpsMockLocation.c built by gcc not g++

FAILED: CMakeFiles/location.dir/src/mock/GpsMockLocation.c.o
/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native/usr/bin/x86_64-webos-linux/x86_64-webos-linux-gcc --sysroot=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot -DUSE_PMLOG_DECLARATION -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2  --sysroot=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot  -O2 -g -fcanon-prefix-map  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git=/usr/src/debug/com.webos.service.location/1.0.0-105  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/build=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/build=/usr/src/debug/com.webos.service.location/1.0.0-105  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot=  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot=  -fdebug-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native=  -fmacro-prefix-map=/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot-native=  -pipe -Wall -DNDEBUG   -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -pthread -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/libmount -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/blkid -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -pthread -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/luneos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/json-c -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/libxml2 -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include/loc-utils -I/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/recipe-sysroot/usr/include -MD -MT CMakeFiles/location.dir/src/mock/GpsMockLocation.c.o -MF CMakeFiles/location.dir/src/mock/GpsMockLocation.c.o.d -o CMakeFiles/location.dir/src/mock/GpsMockLocation.c.o -c /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/src/mock/GpsMockLocation.c
In file included from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/Location.h:23,
                 from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/MockLocation.h:22,
                 from /OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/src/mock/GpsMockLocation.c:21:
/OE/build/webos-walnascar/tmp/work/corei7-64-webos-linux/com.webos.service.location/1.0.0-105/git/include/location_errors.h:21:10: fatal error: cstdint: No such file or directory
   21 | #include <cstdint>
      |          ^~~~~~~~~
compilation terminated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRR-5443] Create GPVB with Yocto 5.2 Walnascar